/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "protocol/simpleble.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(simpleble_UUID16Bit, simpleble_UUID16Bit, AUTO)


PB_BIND(simpleble_UUID32Bit, simpleble_UUID32Bit, AUTO)


PB_BIND(simpleble_UUID128Bit, simpleble_UUID128Bit, AUTO)


PB_BIND(simpleble_UUID, simpleble_UUID, AUTO)


PB_BIND(simpleble_ManufacturerDataEntry, simpleble_ManufacturerDataEntry, AUTO)


PB_BIND(simpleble_ServiceDataEntry, simpleble_ServiceDataEntry, AUTO)


PB_BIND(simpleble_CharacteristicProperties, simpleble_CharacteristicProperties, AUTO)


PB_BIND(simpleble_Service, simpleble_Service, AUTO)


PB_BIND(simpleble_Characteristic, simpleble_Characteristic, AUTO)


PB_BIND(simpleble_Descriptor, simpleble_Descriptor, AUTO)


PB_BIND(simpleble_Attribute, simpleble_Attribute, AUTO)


PB_BIND(simpleble_InitCmd, simpleble_InitCmd, AUTO)


PB_BIND(simpleble_ScanStartCmd, simpleble_ScanStartCmd, AUTO)


PB_BIND(simpleble_ScanStopCmd, simpleble_ScanStopCmd, AUTO)


PB_BIND(simpleble_ConnectCmd, simpleble_ConnectCmd, AUTO)


PB_BIND(simpleble_DisconnectCmd, simpleble_DisconnectCmd, AUTO)


PB_BIND(simpleble_InitRsp, simpleble_InitRsp, AUTO)


PB_BIND(simpleble_ScanStartRsp, simpleble_ScanStartRsp, AUTO)


PB_BIND(simpleble_ScanStopRsp, simpleble_ScanStopRsp, AUTO)


PB_BIND(simpleble_ConnectRsp, simpleble_ConnectRsp, AUTO)


PB_BIND(simpleble_DisconnectRsp, simpleble_DisconnectRsp, AUTO)


PB_BIND(simpleble_AdvEvt, simpleble_AdvEvt, 2)


PB_BIND(simpleble_ConnectionEvt, simpleble_ConnectionEvt, AUTO)


PB_BIND(simpleble_DisconnectionEvt, simpleble_DisconnectionEvt, AUTO)


PB_BIND(simpleble_AttributeFoundEvt, simpleble_AttributeFoundEvt, 2)


PB_BIND(simpleble_Command, simpleble_Command, AUTO)


PB_BIND(simpleble_Response, simpleble_Response, AUTO)


PB_BIND(simpleble_Event, simpleble_Event, 2)





