/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "protocol/simpleble.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(simpleble_InitCmd, simpleble_InitCmd, AUTO)


PB_BIND(simpleble_InitRsp, simpleble_InitRsp, AUTO)


PB_BIND(simpleble_Command, simpleble_Command, AUTO)


PB_BIND(simpleble_Response, simpleble_Response, AUTO)



