/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "protocol/softdevice.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(sd_Command, sd_Command, 2)


PB_BIND(sd_Response, sd_Response, 2)


PB_BIND(sd_Event, sd_Event, 2)



