/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "protocol/softdevice_gap.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(sd_GapAddrSetCmd, sd_GapAddrSetCmd, AUTO)


PB_BIND(sd_GapAddrGetCmd, sd_GapAddrGetCmd, AUTO)


PB_BIND(sd_GapWhitelistSetCmd, sd_GapWhitelistSetCmd, AUTO)


PB_BIND(sd_GapDeviceIdentitiesSetCmd, sd_GapDeviceIdentitiesSetCmd, 2)


PB_BIND(sd_GapPrivacySetCmd, sd_GapPrivacySetCmd, AUTO)


PB_BIND(sd_GapPrivacyGetCmd, sd_GapPrivacyGetCmd, AUTO)


PB_BIND(sd_GapAdvSetConfigureCmd, sd_GapAdvSetConfigureCmd, 2)


PB_BIND(sd_GapAdvStartCmd, sd_GapAdvStartCmd, AUTO)


PB_BIND(sd_GapAdvStopCmd, sd_GapAdvStopCmd, AUTO)


PB_BIND(sd_GapConnParamUpdateCmd, sd_GapConnParamUpdateCmd, AUTO)


PB_BIND(sd_GapDisconnectCmd, sd_GapDisconnectCmd, AUTO)


PB_BIND(sd_GapTxPowerSetCmd, sd_GapTxPowerSetCmd, AUTO)


PB_BIND(sd_GapAppearanceSetCmd, sd_GapAppearanceSetCmd, AUTO)


PB_BIND(sd_GapAppearanceGetCmd, sd_GapAppearanceGetCmd, AUTO)


PB_BIND(sd_GapPpcpSetCmd, sd_GapPpcpSetCmd, AUTO)


PB_BIND(sd_GapPpcpGetCmd, sd_GapPpcpGetCmd, AUTO)


PB_BIND(sd_GapDeviceNameSetCmd, sd_GapDeviceNameSetCmd, 2)


PB_BIND(sd_GapDeviceNameGetCmd, sd_GapDeviceNameGetCmd, AUTO)


PB_BIND(sd_GapAuthenticateCmd, sd_GapAuthenticateCmd, AUTO)


PB_BIND(sd_GapSecParamsReplyCmd, sd_GapSecParamsReplyCmd, 2)


PB_BIND(sd_GapAuthKeyReplyCmd, sd_GapAuthKeyReplyCmd, AUTO)


PB_BIND(sd_GapLescDhkeyReplyCmd, sd_GapLescDhkeyReplyCmd, AUTO)


PB_BIND(sd_GapKeypressNotifyCmd, sd_GapKeypressNotifyCmd, AUTO)


PB_BIND(sd_GapLescOobDataGetCmd, sd_GapLescOobDataGetCmd, AUTO)


PB_BIND(sd_GapLescOobDataSetCmd, sd_GapLescOobDataSetCmd, AUTO)


PB_BIND(sd_GapEncryptCmd, sd_GapEncryptCmd, AUTO)


PB_BIND(sd_GapSecInfoReplyCmd, sd_GapSecInfoReplyCmd, AUTO)


PB_BIND(sd_GapConnSecGetCmd, sd_GapConnSecGetCmd, AUTO)


PB_BIND(sd_GapRssiStartCmd, sd_GapRssiStartCmd, AUTO)


PB_BIND(sd_GapRssiStopCmd, sd_GapRssiStopCmd, AUTO)


PB_BIND(sd_GapScanStartCmd, sd_GapScanStartCmd, AUTO)


PB_BIND(sd_GapScanStopCmd, sd_GapScanStopCmd, AUTO)


PB_BIND(sd_GapConnectCmd, sd_GapConnectCmd, AUTO)


PB_BIND(sd_GapConnectCancelCmd, sd_GapConnectCancelCmd, AUTO)


PB_BIND(sd_GapRssiGetCmd, sd_GapRssiGetCmd, AUTO)


PB_BIND(sd_BleGapPhysCmd, sd_BleGapPhysCmd, AUTO)


PB_BIND(sd_GapPhyUpdateCmd, sd_GapPhyUpdateCmd, AUTO)


PB_BIND(sd_GapDataLengthUpdateCmd, sd_GapDataLengthUpdateCmd, AUTO)


PB_BIND(sd_GapQosChannelSurveyStartCmd, sd_GapQosChannelSurveyStartCmd, AUTO)


PB_BIND(sd_GapQosChannelSurveyStopCmd, sd_GapQosChannelSurveyStopCmd, AUTO)


PB_BIND(sd_GapAdvAddrGetCmd, sd_GapAdvAddrGetCmd, AUTO)


PB_BIND(sd_GapNextConnEvtCounterGetCmd, sd_GapNextConnEvtCounterGetCmd, AUTO)


PB_BIND(sd_GapConnEvtTriggerStartCmd, sd_GapConnEvtTriggerStartCmd, AUTO)


PB_BIND(sd_GapConnEvtTriggerStopCmd, sd_GapConnEvtTriggerStopCmd, AUTO)


PB_BIND(sd_GapAddrSetRsp, sd_GapAddrSetRsp, AUTO)


PB_BIND(sd_GapAddrGetRsp, sd_GapAddrGetRsp, AUTO)


PB_BIND(sd_GapWhitelistSetRsp, sd_GapWhitelistSetRsp, AUTO)


PB_BIND(sd_GapDeviceIdentitiesSetRsp, sd_GapDeviceIdentitiesSetRsp, AUTO)


PB_BIND(sd_GapPrivacySetRsp, sd_GapPrivacySetRsp, AUTO)


PB_BIND(sd_GapPrivacyGetRsp, sd_GapPrivacyGetRsp, AUTO)


PB_BIND(sd_GapAdvSetConfigureRsp, sd_GapAdvSetConfigureRsp, AUTO)


PB_BIND(sd_GapAdvStartRsp, sd_GapAdvStartRsp, AUTO)


PB_BIND(sd_GapAdvStopRsp, sd_GapAdvStopRsp, AUTO)


PB_BIND(sd_GapConnParamUpdateRsp, sd_GapConnParamUpdateRsp, AUTO)


PB_BIND(sd_GapDisconnectRsp, sd_GapDisconnectRsp, AUTO)


PB_BIND(sd_GapTxPowerSetRsp, sd_GapTxPowerSetRsp, AUTO)


PB_BIND(sd_GapAppearanceSetRsp, sd_GapAppearanceSetRsp, AUTO)


PB_BIND(sd_GapAppearanceGetRsp, sd_GapAppearanceGetRsp, AUTO)


PB_BIND(sd_GapPpcpSetRsp, sd_GapPpcpSetRsp, AUTO)


PB_BIND(sd_GapPpcpGetRsp, sd_GapPpcpGetRsp, AUTO)


PB_BIND(sd_GapDeviceNameSetRsp, sd_GapDeviceNameSetRsp, AUTO)


PB_BIND(sd_GapDeviceNameGetRsp, sd_GapDeviceNameGetRsp, 2)


PB_BIND(sd_GapAuthenticateRsp, sd_GapAuthenticateRsp, AUTO)


PB_BIND(sd_GapSecParamsReplyRsp, sd_GapSecParamsReplyRsp, AUTO)


PB_BIND(sd_GapAuthKeyReplyRsp, sd_GapAuthKeyReplyRsp, AUTO)


PB_BIND(sd_GapLescDhkeyReplyRsp, sd_GapLescDhkeyReplyRsp, AUTO)


PB_BIND(sd_GapKeypressNotifyRsp, sd_GapKeypressNotifyRsp, AUTO)


PB_BIND(sd_GapLescOobDataGetRsp, sd_GapLescOobDataGetRsp, AUTO)


PB_BIND(sd_GapLescOobDataSetRsp, sd_GapLescOobDataSetRsp, AUTO)


PB_BIND(sd_GapEncryptRsp, sd_GapEncryptRsp, AUTO)


PB_BIND(sd_GapSecInfoReplyRsp, sd_GapSecInfoReplyRsp, AUTO)


PB_BIND(sd_GapConnSecGetRsp, sd_GapConnSecGetRsp, AUTO)


PB_BIND(sd_GapRssiStartRsp, sd_GapRssiStartRsp, AUTO)


PB_BIND(sd_GapRssiStopRsp, sd_GapRssiStopRsp, AUTO)


PB_BIND(sd_GapScanStartRsp, sd_GapScanStartRsp, AUTO)


PB_BIND(sd_GapScanStopRsp, sd_GapScanStopRsp, AUTO)


PB_BIND(sd_GapConnectRsp, sd_GapConnectRsp, AUTO)


PB_BIND(sd_GapConnectCancelRsp, sd_GapConnectCancelRsp, AUTO)


PB_BIND(sd_GapRssiGetRsp, sd_GapRssiGetRsp, AUTO)


PB_BIND(sd_GapPhyUpdateRsp, sd_GapPhyUpdateRsp, AUTO)


PB_BIND(sd_GapDataLengthUpdateRsp, sd_GapDataLengthUpdateRsp, AUTO)


PB_BIND(sd_GapQosChannelSurveyStartRsp, sd_GapQosChannelSurveyStartRsp, AUTO)


PB_BIND(sd_GapQosChannelSurveyStopRsp, sd_GapQosChannelSurveyStopRsp, AUTO)


PB_BIND(sd_GapAdvAddrGetRsp, sd_GapAdvAddrGetRsp, AUTO)


PB_BIND(sd_GapNextConnEvtCounterGetRsp, sd_GapNextConnEvtCounterGetRsp, AUTO)


PB_BIND(sd_GapConnEvtTriggerStartRsp, sd_GapConnEvtTriggerStartRsp, AUTO)


PB_BIND(sd_GapConnEvtTriggerStopRsp, sd_GapConnEvtTriggerStopRsp, AUTO)


PB_BIND(sd_GapEvtConnected, sd_GapEvtConnected, 2)


PB_BIND(sd_GapEvtDisconnected, sd_GapEvtDisconnected, AUTO)


PB_BIND(sd_GapEvtConnParamUpdate, sd_GapEvtConnParamUpdate, AUTO)


PB_BIND(sd_GapEvtSecParamsRequest, sd_GapEvtSecParamsRequest, AUTO)


PB_BIND(sd_GapEvtSecInfoRequest, sd_GapEvtSecInfoRequest, AUTO)


PB_BIND(sd_GapEvtPasskeyDisplay, sd_GapEvtPasskeyDisplay, AUTO)


PB_BIND(sd_GapEvtKeyPressed, sd_GapEvtKeyPressed, AUTO)


PB_BIND(sd_GapEvtAuthKeyRequest, sd_GapEvtAuthKeyRequest, AUTO)


PB_BIND(sd_GapEvtLescDhkeyRequest, sd_GapEvtLescDhkeyRequest, AUTO)


PB_BIND(sd_GapEvtAuthStatus, sd_GapEvtAuthStatus, AUTO)


PB_BIND(sd_GapEvtConnSecUpdate, sd_GapEvtConnSecUpdate, AUTO)


PB_BIND(sd_GapEvtTimeout, sd_GapEvtTimeout, 2)


PB_BIND(sd_GapEvtRssiChanged, sd_GapEvtRssiChanged, AUTO)


PB_BIND(sd_GapEvtAdvReport, sd_GapEvtAdvReport, 2)


PB_BIND(sd_GapEvtSecRequest, sd_GapEvtSecRequest, AUTO)


PB_BIND(sd_GapEvtConnParamUpdateRequest, sd_GapEvtConnParamUpdateRequest, AUTO)


PB_BIND(sd_GapEvtScanReqReport, sd_GapEvtScanReqReport, AUTO)


PB_BIND(sd_GapEvtPhyUpdateRequest, sd_GapEvtPhyUpdateRequest, AUTO)


PB_BIND(sd_GapEvtPhyUpdate, sd_GapEvtPhyUpdate, AUTO)


PB_BIND(sd_GapEvtDataLengthUpdateRequest, sd_GapEvtDataLengthUpdateRequest, AUTO)


PB_BIND(sd_GapEvtDataLengthUpdate, sd_GapEvtDataLengthUpdate, AUTO)


PB_BIND(sd_GapEvtQosChannelSurveyReport, sd_GapEvtQosChannelSurveyReport, AUTO)


PB_BIND(sd_GapEvtAdvSetTerminated, sd_GapEvtAdvSetTerminated, 2)



