/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SD_SOFTDEVICE_GAP_PB_H_INCLUDED
#define PB_SD_SOFTDEVICE_GAP_PB_H_INCLUDED
#include "nanopb/pb.h"
#include "protocol/softdevice_types.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* SoftDevice GAP command messages */
typedef struct _sd_GapAddrSetCmd {
    bool has_addr;
    sd_types_BleGapAddr addr;
} sd_GapAddrSetCmd;

typedef struct _sd_GapAddrGetCmd { /* No input parameters */
    char dummy_field;
} sd_GapAddrGetCmd;

typedef struct _sd_GapWhitelistSetCmd {
    pb_size_t wl_addrs_count;
    sd_types_BleGapAddr wl_addrs[8]; /* BLE_GAP_WHITELIST_ADDR_MAX_COUNT = 8 */
    uint8_t len;
} sd_GapWhitelistSetCmd;

typedef struct _sd_GapDeviceIdentitiesSetCmd {
    pb_size_t id_keys_count;
    sd_types_BleGapIdKey id_keys[8]; /* BLE_GAP_DEVICE_IDENTITIES_MAX_COUNT = 8 */
    pb_size_t local_irks_count;
    sd_types_BleGapIrk local_irks[8]; /* BLE_GAP_DEVICE_IDENTITIES_MAX_COUNT = 8 */
    uint8_t len;
} sd_GapDeviceIdentitiesSetCmd;

typedef struct _sd_GapPrivacySetCmd {
    bool has_privacy_params;
    sd_types_BleGapPrivacyParams privacy_params;
} sd_GapPrivacySetCmd;

typedef struct _sd_GapPrivacyGetCmd { /* No input parameters */
    char dummy_field;
} sd_GapPrivacyGetCmd;

typedef struct _sd_GapAdvSetConfigureCmd {
    uint8_t adv_handle; /* Input/output */
    bool has_adv_data;
    sd_types_BleGapAdvData adv_data; /* Optional */
    bool has_adv_params;
    sd_types_BleGapAdvParams adv_params; /* Optional */
} sd_GapAdvSetConfigureCmd;

typedef struct _sd_GapAdvStartCmd {
    uint8_t adv_handle;
    uint8_t conn_cfg_tag;
} sd_GapAdvStartCmd;

typedef struct _sd_GapAdvStopCmd {
    uint8_t adv_handle;
} sd_GapAdvStopCmd;

typedef struct _sd_GapConnParamUpdateCmd {
    uint16_t conn_handle;
    bool has_conn_params;
    sd_types_BleGapConnParams conn_params; /* Optional */
} sd_GapConnParamUpdateCmd;

typedef struct _sd_GapDisconnectCmd {
    uint16_t conn_handle;
    uint8_t hci_ret_code_code;
} sd_GapDisconnectCmd;

typedef struct _sd_GapTxPowerSetCmd {
    uint8_t role;
    uint16_t handle;
    int8_t tx_power;
} sd_GapTxPowerSetCmd;

typedef struct _sd_GapAppearanceSetCmd {
    uint16_t appearance;
} sd_GapAppearanceSetCmd;

typedef struct _sd_GapAppearanceGetCmd { /* No input parameters */
    char dummy_field;
} sd_GapAppearanceGetCmd;

typedef struct _sd_GapPpcpSetCmd {
    bool has_conn_params;
    sd_types_BleGapConnParams conn_params;
} sd_GapPpcpSetCmd;

typedef struct _sd_GapPpcpGetCmd { /* No input parameters */
    char dummy_field;
} sd_GapPpcpGetCmd;

typedef PB_BYTES_ARRAY_T(248) sd_GapDeviceNameSetCmd_dev_name_t;
typedef struct _sd_GapDeviceNameSetCmd {
    bool has_write_perm;
    sd_types_BleGapConnSecMode write_perm;
    sd_GapDeviceNameSetCmd_dev_name_t dev_name; /* BLE_GAP_DEVNAME_MAX_LEN = 248 */
    uint16_t len;
} sd_GapDeviceNameSetCmd;

typedef struct _sd_GapDeviceNameGetCmd { /* No input parameters */
    char dummy_field;
} sd_GapDeviceNameGetCmd;

typedef struct _sd_GapAuthenticateCmd {
    uint16_t conn_handle;
    bool has_sec_params;
    sd_types_BleGapSecParams sec_params; /* Optional */
} sd_GapAuthenticateCmd;

typedef struct _sd_GapSecParamsReplyCmd {
    uint16_t conn_handle;
    sd_types_BleGapSecStatus sec_ret_code;
    bool has_sec_params;
    sd_types_BleGapSecParams sec_params; /* Optional */
    bool has_sec_keyset;
    sd_types_BleGapSecKeyset sec_keyset;
} sd_GapSecParamsReplyCmd;

typedef PB_BYTES_ARRAY_T(16) sd_GapAuthKeyReplyCmd_key_t;
typedef struct _sd_GapAuthKeyReplyCmd {
    uint16_t conn_handle;
    sd_types_BleGapAuthKeyType key_type;
    sd_GapAuthKeyReplyCmd_key_t key; /* Max for OOB key */
} sd_GapAuthKeyReplyCmd;

typedef struct _sd_GapLescDhkeyReplyCmd {
    uint16_t conn_handle;
    bool has_dhkey;
    sd_types_BleGapLescDhkey dhkey;
} sd_GapLescDhkeyReplyCmd;

typedef struct _sd_GapKeypressNotifyCmd {
    uint16_t conn_handle;
    sd_types_BleGapKpNotType kp_not;
} sd_GapKeypressNotifyCmd;

typedef struct _sd_GapLescOobDataGetCmd {
    uint16_t conn_handle;
    bool has_pk_own;
    sd_types_BleGapLescP256Pk pk_own;
} sd_GapLescOobDataGetCmd;

typedef struct _sd_GapLescOobDataSetCmd {
    uint16_t conn_handle;
    bool has_oobd_own;
    sd_types_BleGapLescOobData oobd_own; /* Optional */
    bool has_oobd_peer;
    sd_types_BleGapLescOobData oobd_peer; /* Optional */
} sd_GapLescOobDataSetCmd;

typedef struct _sd_GapEncryptCmd {
    uint16_t conn_handle;
    bool has_master_id;
    sd_types_BleGapMasterId master_id;
    bool has_enc_info;
    sd_types_BleGapEncInfo enc_info;
} sd_GapEncryptCmd;

typedef struct _sd_GapSecInfoReplyCmd {
    uint16_t conn_handle;
    bool has_enc_info;
    sd_types_BleGapEncInfo enc_info; /* Optional */
    bool has_id_info;
    sd_types_BleGapIrk id_info; /* Optional */
    bool has_sign_info;
    sd_types_BleGapSignInfo sign_info; /* Optional */
} sd_GapSecInfoReplyCmd;

typedef struct _sd_GapConnSecGetCmd {
    uint16_t conn_handle;
} sd_GapConnSecGetCmd;

typedef struct _sd_GapRssiStartCmd {
    uint16_t conn_handle;
    uint8_t threshold_dbm;
    uint8_t skip_count;
} sd_GapRssiStartCmd;

typedef struct _sd_GapRssiStopCmd {
    uint16_t conn_handle;
} sd_GapRssiStopCmd;

typedef struct _sd_GapScanStartCmd {
    bool has_scan_params;
    sd_types_BleGapScanParams scan_params; /* Optional */
} sd_GapScanStartCmd;

typedef struct _sd_GapScanStopCmd { /* No input parameters */
    char dummy_field;
} sd_GapScanStopCmd;

typedef struct _sd_GapConnectCmd {
    bool has_peer_addr;
    sd_types_BleGapAddr peer_addr;
    bool has_scan_params;
    sd_types_BleGapScanParams scan_params;
    bool has_conn_params;
    sd_types_BleGapConnParams conn_params;
    uint8_t conn_cfg_tag;
} sd_GapConnectCmd;

typedef struct _sd_GapConnectCancelCmd { /* No input parameters */
    char dummy_field;
} sd_GapConnectCancelCmd;

typedef struct _sd_GapRssiGetCmd {
    uint16_t conn_handle;
} sd_GapRssiGetCmd;

typedef struct _sd_BleGapPhysCmd {
    sd_types_BleGapPhy tx_phys;
    sd_types_BleGapPhy rx_phys;
} sd_BleGapPhysCmd;

typedef struct _sd_GapPhyUpdateCmd {
    uint16_t conn_handle;
    bool has_phys;
    sd_BleGapPhysCmd phys;
} sd_GapPhyUpdateCmd;

typedef struct _sd_GapDataLengthUpdateCmd {
    uint16_t conn_handle;
    bool has_dl_params;
    sd_types_BleGapDataLengthParams dl_params; /* Optional */
    bool has_dl_limitation;
    sd_types_BleGapDataLengthLimitation dl_limitation; /* Optional */
} sd_GapDataLengthUpdateCmd;

typedef struct _sd_GapQosChannelSurveyStartCmd {
    uint32_t interval_us;
} sd_GapQosChannelSurveyStartCmd;

typedef struct _sd_GapQosChannelSurveyStopCmd { /* No input parameters */
    char dummy_field;
} sd_GapQosChannelSurveyStopCmd;

typedef struct _sd_GapAdvAddrGetCmd {
    uint8_t adv_handle;
} sd_GapAdvAddrGetCmd;

typedef struct _sd_GapNextConnEvtCounterGetCmd {
    uint16_t conn_handle;
} sd_GapNextConnEvtCounterGetCmd;

typedef struct _sd_GapConnEvtTriggerStartCmd {
    uint16_t conn_handle;
    bool has_params;
    sd_types_BleGapConnEventTrigger params;
} sd_GapConnEvtTriggerStartCmd;

typedef struct _sd_GapConnEvtTriggerStopCmd {
    uint16_t conn_handle;
} sd_GapConnEvtTriggerStopCmd;

/* SoftDevice GAP response messages */
typedef struct _sd_GapAddrSetRsp {
    uint32_t ret_code;
} sd_GapAddrSetRsp;

typedef struct _sd_GapAddrGetRsp {
    uint32_t ret_code;
    bool has_addr;
    sd_types_BleGapAddr addr;
} sd_GapAddrGetRsp;

typedef struct _sd_GapWhitelistSetRsp {
    uint32_t ret_code;
} sd_GapWhitelistSetRsp;

typedef struct _sd_GapDeviceIdentitiesSetRsp {
    uint32_t ret_code;
} sd_GapDeviceIdentitiesSetRsp;

typedef struct _sd_GapPrivacySetRsp {
    uint32_t ret_code;
} sd_GapPrivacySetRsp;

typedef struct _sd_GapPrivacyGetRsp {
    uint32_t ret_code;
    bool has_privacy_params;
    sd_types_BleGapPrivacyParams privacy_params;
} sd_GapPrivacyGetRsp;

typedef struct _sd_GapAdvSetConfigureRsp {
    uint32_t ret_code;
    uint8_t adv_handle;
} sd_GapAdvSetConfigureRsp;

typedef struct _sd_GapAdvStartRsp {
    uint32_t ret_code;
} sd_GapAdvStartRsp;

typedef struct _sd_GapAdvStopRsp {
    uint32_t ret_code;
} sd_GapAdvStopRsp;

typedef struct _sd_GapConnParamUpdateRsp {
    uint32_t ret_code;
} sd_GapConnParamUpdateRsp;

typedef struct _sd_GapDisconnectRsp {
    uint32_t ret_code;
} sd_GapDisconnectRsp;

typedef struct _sd_GapTxPowerSetRsp {
    uint32_t ret_code;
} sd_GapTxPowerSetRsp;

typedef struct _sd_GapAppearanceSetRsp {
    uint32_t ret_code;
} sd_GapAppearanceSetRsp;

typedef struct _sd_GapAppearanceGetRsp {
    uint32_t ret_code;
    uint16_t appearance;
} sd_GapAppearanceGetRsp;

typedef struct _sd_GapPpcpSetRsp {
    uint32_t ret_code;
} sd_GapPpcpSetRsp;

typedef struct _sd_GapPpcpGetRsp {
    uint32_t ret_code;
    bool has_conn_params;
    sd_types_BleGapConnParams conn_params;
} sd_GapPpcpGetRsp;

typedef struct _sd_GapDeviceNameSetRsp {
    uint32_t ret_code;
} sd_GapDeviceNameSetRsp;

typedef PB_BYTES_ARRAY_T(248) sd_GapDeviceNameGetRsp_dev_name_t;
typedef struct _sd_GapDeviceNameGetRsp {
    uint32_t ret_code;
    sd_GapDeviceNameGetRsp_dev_name_t dev_name; /* BLE_GAP_DEVNAME_MAX_LEN = 248 */
    uint16_t len;
} sd_GapDeviceNameGetRsp;

typedef struct _sd_GapAuthenticateRsp {
    uint32_t ret_code;
} sd_GapAuthenticateRsp;

typedef struct _sd_GapSecParamsReplyRsp {
    uint32_t ret_code;
} sd_GapSecParamsReplyRsp;

typedef struct _sd_GapAuthKeyReplyRsp {
    uint32_t ret_code;
} sd_GapAuthKeyReplyRsp;

typedef struct _sd_GapLescDhkeyReplyRsp {
    uint32_t ret_code;
} sd_GapLescDhkeyReplyRsp;

typedef struct _sd_GapKeypressNotifyRsp {
    uint32_t ret_code;
} sd_GapKeypressNotifyRsp;

typedef struct _sd_GapLescOobDataGetRsp {
    uint32_t ret_code;
    bool has_oobd_own;
    sd_types_BleGapLescOobData oobd_own;
} sd_GapLescOobDataGetRsp;

typedef struct _sd_GapLescOobDataSetRsp {
    uint32_t ret_code;
} sd_GapLescOobDataSetRsp;

typedef struct _sd_GapEncryptRsp {
    uint32_t ret_code;
} sd_GapEncryptRsp;

typedef struct _sd_GapSecInfoReplyRsp {
    uint32_t ret_code;
} sd_GapSecInfoReplyRsp;

typedef struct _sd_GapConnSecGetRsp {
    uint32_t ret_code;
    bool has_conn_sec;
    sd_types_BleGapConnSec conn_sec;
} sd_GapConnSecGetRsp;

typedef struct _sd_GapRssiStartRsp {
    uint32_t ret_code;
} sd_GapRssiStartRsp;

typedef struct _sd_GapRssiStopRsp {
    uint32_t ret_code;
} sd_GapRssiStopRsp;

typedef struct _sd_GapScanStartRsp {
    uint32_t ret_code;
} sd_GapScanStartRsp;

typedef struct _sd_GapScanStopRsp {
    uint32_t ret_code;
} sd_GapScanStopRsp;

typedef struct _sd_GapConnectRsp {
    uint32_t ret_code;
} sd_GapConnectRsp;

typedef struct _sd_GapConnectCancelRsp {
    uint32_t ret_code;
} sd_GapConnectCancelRsp;

typedef struct _sd_GapRssiGetRsp {
    uint32_t ret_code;
    int8_t rssi;
} sd_GapRssiGetRsp;

typedef struct _sd_GapPhyUpdateRsp {
    uint32_t ret_code;
} sd_GapPhyUpdateRsp;

typedef struct _sd_GapDataLengthUpdateRsp {
    uint32_t ret_code;
    bool has_dl_params;
    sd_types_BleGapDataLengthParams dl_params; /* Optional */
    bool has_dl_limitation;
    sd_types_BleGapDataLengthLimitation dl_limitation; /* Optional */
} sd_GapDataLengthUpdateRsp;

typedef struct _sd_GapQosChannelSurveyStartRsp {
    uint32_t ret_code;
} sd_GapQosChannelSurveyStartRsp;

typedef struct _sd_GapQosChannelSurveyStopRsp {
    uint32_t ret_code;
} sd_GapQosChannelSurveyStopRsp;

typedef struct _sd_GapAdvAddrGetRsp {
    uint32_t ret_code;
    bool has_addr;
    sd_types_BleGapAddr addr;
} sd_GapAdvAddrGetRsp;

typedef struct _sd_GapNextConnEvtCounterGetRsp {
    uint32_t ret_code;
    uint16_t count;
} sd_GapNextConnEvtCounterGetRsp;

typedef struct _sd_GapConnEvtTriggerStartRsp {
    uint32_t ret_code;
} sd_GapConnEvtTriggerStartRsp;

typedef struct _sd_GapConnEvtTriggerStopRsp {
    uint32_t ret_code;
} sd_GapConnEvtTriggerStopRsp;

/* SoftDevice GAP event messages */
typedef struct _sd_GapEvtConnected {
    bool has_peer_addr;
    sd_types_BleGapAddr peer_addr;
    uint8_t role;
    bool has_conn_params;
    sd_types_BleGapConnParams conn_params;
    uint8_t adv_handle;
    bool has_adv_data;
    sd_types_BleGapAdvData adv_data;
} sd_GapEvtConnected;

typedef struct _sd_GapEvtDisconnected {
    uint8_t reason;
} sd_GapEvtDisconnected;

typedef struct _sd_GapEvtConnParamUpdate {
    bool has_conn_params;
    sd_types_BleGapConnParams conn_params;
} sd_GapEvtConnParamUpdate;

typedef struct _sd_GapEvtSecParamsRequest {
    bool has_peer_params;
    sd_types_BleGapSecParams peer_params;
} sd_GapEvtSecParamsRequest;

typedef struct _sd_GapEvtSecInfoRequest {
    bool has_peer_addr;
    sd_types_BleGapAddr peer_addr;
    bool has_master_id;
    sd_types_BleGapMasterId master_id;
    uint8_t enc_info; /* 1-bit field */
    uint8_t id_info; /* 1-bit field */
    uint8_t sign_info; /* 1-bit field */
} sd_GapEvtSecInfoRequest;

typedef struct _sd_GapEvtPasskeyDisplay {
    pb_byte_t passkey[6]; /* BLE_GAP_PASSKEY_LEN = 6 */
    bool match_request;
} sd_GapEvtPasskeyDisplay;

typedef struct _sd_GapEvtKeyPressed {
    sd_types_BleGapKpNotType kp_not;
} sd_GapEvtKeyPressed;

typedef struct _sd_GapEvtAuthKeyRequest {
    sd_types_BleGapAuthKeyType key_type;
} sd_GapEvtAuthKeyRequest;

typedef struct _sd_GapEvtLescDhkeyRequest {
    bool has_pk_peer;
    sd_types_BleGapLescP256Pk pk_peer; /* Optional */
    bool oobd_req;
} sd_GapEvtLescDhkeyRequest;

typedef struct _sd_GapEvtAuthStatus {
    sd_types_BleGapSecStatus auth_status;
    uint8_t error_src; /* 2-bit field */
    bool bonded;
    bool lesc;
    bool has_sm1_levels;
    sd_types_BleGapSecLevelsT sm1_levels;
    bool has_sm2_levels;
    sd_types_BleGapSecLevelsT sm2_levels;
    bool has_kdist_own;
    sd_types_BleGapSecKdist kdist_own;
    bool has_kdist_peer;
    sd_types_BleGapSecKdist kdist_peer;
} sd_GapEvtAuthStatus;

typedef struct _sd_GapEvtConnSecUpdate {
    bool has_conn_sec;
    sd_types_BleGapConnSec conn_sec;
} sd_GapEvtConnSecUpdate;

typedef struct _sd_GapEvtTimeout {
    sd_types_BleGapTimeoutSrc src;
    bool has_adv_report_buffer;
    sd_types_BleData adv_report_buffer; /* Optional */
} sd_GapEvtTimeout;

typedef struct _sd_GapEvtRssiChanged {
    int8_t rssi;
    uint8_t ch_index;
} sd_GapEvtRssiChanged;

typedef struct _sd_GapEvtAdvReport {
    bool has_type;
    sd_types_BleGapAdvReportTypeT type;
    bool has_peer_addr;
    sd_types_BleGapAddr peer_addr;
    bool has_direct_addr;
    sd_types_BleGapAddr direct_addr;
    sd_types_BleGapPhy primary_phy;
    sd_types_BleGapPhy secondary_phy;
    int8_t tx_power;
    int8_t rssi;
    uint8_t ch_index;
    uint8_t set_id;
    uint16_t data_id; /* 12-bit field */
    bool has_data;
    sd_types_BleData data;
    bool has_aux_pointer;
    sd_types_BleGapAuxPointer aux_pointer;
} sd_GapEvtAdvReport;

typedef struct _sd_GapEvtSecRequest {
    bool bond;
    bool mitm;
    bool lesc;
    bool keypress;
} sd_GapEvtSecRequest;

typedef struct _sd_GapEvtConnParamUpdateRequest {
    bool has_conn_params;
    sd_types_BleGapConnParams conn_params;
} sd_GapEvtConnParamUpdateRequest;

typedef struct _sd_GapEvtScanReqReport {
    uint8_t adv_handle;
    int8_t rssi;
    bool has_peer_addr;
    sd_types_BleGapAddr peer_addr;
} sd_GapEvtScanReqReport;

typedef struct _sd_GapEvtPhyUpdateRequest {
    sd_types_BleGapPhy tx_phys;
    sd_types_BleGapPhy rx_phys;
} sd_GapEvtPhyUpdateRequest;

typedef struct _sd_GapEvtPhyUpdate {
    uint16_t status; /* BLE_HCI_STATUS_CODES */
    sd_types_BleGapPhy tx_phy;
    sd_types_BleGapPhy rx_phy;
} sd_GapEvtPhyUpdate;

typedef struct _sd_GapEvtDataLengthUpdateRequest {
    bool has_peer_params;
    sd_types_BleGapDataLengthParams peer_params;
} sd_GapEvtDataLengthUpdateRequest;

typedef struct _sd_GapEvtDataLengthUpdate {
    bool has_effective_params;
    sd_types_BleGapDataLengthParams effective_params;
} sd_GapEvtDataLengthUpdate;

typedef struct _sd_GapEvtQosChannelSurveyReport {
    pb_size_t channel_energy_count;
    int32_t channel_energy[40]; /* BLE_GAP_CHANNEL_COUNT = 40 */
} sd_GapEvtQosChannelSurveyReport;

typedef struct _sd_GapEvtAdvSetTerminated {
    sd_types_BleGapAdvSetTerminatedReason reason;
    uint8_t adv_handle;
    uint8_t num_completed_adv_events;
    bool has_adv_data;
    sd_types_BleGapAdvData adv_data;
} sd_GapEvtAdvSetTerminated;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define sd_GapAddrSetCmd_init_default            {false, sd_types_BleGapAddr_init_default}
#define sd_GapAddrGetCmd_init_default            {0}
#define sd_GapWhitelistSetCmd_init_default       {0, {sd_types_BleGapAddr_init_default, sd_types_BleGapAddr_init_default, sd_types_BleGapAddr_init_default, sd_types_BleGapAddr_init_default, sd_types_BleGapAddr_init_default, sd_types_BleGapAddr_init_default, sd_types_BleGapAddr_init_default, sd_types_BleGapAddr_init_default}, 0}
#define sd_GapDeviceIdentitiesSetCmd_init_default {0, {sd_types_BleGapIdKey_init_default, sd_types_BleGapIdKey_init_default, sd_types_BleGapIdKey_init_default, sd_types_BleGapIdKey_init_default, sd_types_BleGapIdKey_init_default, sd_types_BleGapIdKey_init_default, sd_types_BleGapIdKey_init_default, sd_types_BleGapIdKey_init_default}, 0, {sd_types_BleGapIrk_init_default, sd_types_BleGapIrk_init_default, sd_types_BleGapIrk_init_default, sd_types_BleGapIrk_init_default, sd_types_BleGapIrk_init_default, sd_types_BleGapIrk_init_default, sd_types_BleGapIrk_init_default, sd_types_BleGapIrk_init_default}, 0}
#define sd_GapPrivacySetCmd_init_default         {false, sd_types_BleGapPrivacyParams_init_default}
#define sd_GapPrivacyGetCmd_init_default         {0}
#define sd_GapAdvSetConfigureCmd_init_default    {0, false, sd_types_BleGapAdvData_init_default, false, sd_types_BleGapAdvParams_init_default}
#define sd_GapAdvStartCmd_init_default           {0, 0}
#define sd_GapAdvStopCmd_init_default            {0}
#define sd_GapConnParamUpdateCmd_init_default    {0, false, sd_types_BleGapConnParams_init_default}
#define sd_GapDisconnectCmd_init_default         {0, 0}
#define sd_GapTxPowerSetCmd_init_default         {0, 0, 0}
#define sd_GapAppearanceSetCmd_init_default      {0}
#define sd_GapAppearanceGetCmd_init_default      {0}
#define sd_GapPpcpSetCmd_init_default            {false, sd_types_BleGapConnParams_init_default}
#define sd_GapPpcpGetCmd_init_default            {0}
#define sd_GapDeviceNameSetCmd_init_default      {false, sd_types_BleGapConnSecMode_init_default, {0, {0}}, 0}
#define sd_GapDeviceNameGetCmd_init_default      {0}
#define sd_GapAuthenticateCmd_init_default       {0, false, sd_types_BleGapSecParams_init_default}
#define sd_GapSecParamsReplyCmd_init_default     {0, _sd_types_BleGapSecStatus_MIN, false, sd_types_BleGapSecParams_init_default, false, sd_types_BleGapSecKeyset_init_default}
#define sd_GapAuthKeyReplyCmd_init_default       {0, _sd_types_BleGapAuthKeyType_MIN, {0, {0}}}
#define sd_GapLescDhkeyReplyCmd_init_default     {0, false, sd_types_BleGapLescDhkey_init_default}
#define sd_GapKeypressNotifyCmd_init_default     {0, _sd_types_BleGapKpNotType_MIN}
#define sd_GapLescOobDataGetCmd_init_default     {0, false, sd_types_BleGapLescP256Pk_init_default}
#define sd_GapLescOobDataSetCmd_init_default     {0, false, sd_types_BleGapLescOobData_init_default, false, sd_types_BleGapLescOobData_init_default}
#define sd_GapEncryptCmd_init_default            {0, false, sd_types_BleGapMasterId_init_default, false, sd_types_BleGapEncInfo_init_default}
#define sd_GapSecInfoReplyCmd_init_default       {0, false, sd_types_BleGapEncInfo_init_default, false, sd_types_BleGapIrk_init_default, false, sd_types_BleGapSignInfo_init_default}
#define sd_GapConnSecGetCmd_init_default         {0}
#define sd_GapRssiStartCmd_init_default          {0, 0, 0}
#define sd_GapRssiStopCmd_init_default           {0}
#define sd_GapScanStartCmd_init_default          {false, sd_types_BleGapScanParams_init_default}
#define sd_GapScanStopCmd_init_default           {0}
#define sd_GapConnectCmd_init_default            {false, sd_types_BleGapAddr_init_default, false, sd_types_BleGapScanParams_init_default, false, sd_types_BleGapConnParams_init_default, 0}
#define sd_GapConnectCancelCmd_init_default      {0}
#define sd_GapRssiGetCmd_init_default            {0}
#define sd_BleGapPhysCmd_init_default            {_sd_types_BleGapPhy_MIN, _sd_types_BleGapPhy_MIN}
#define sd_GapPhyUpdateCmd_init_default          {0, false, sd_BleGapPhysCmd_init_default}
#define sd_GapDataLengthUpdateCmd_init_default   {0, false, sd_types_BleGapDataLengthParams_init_default, false, sd_types_BleGapDataLengthLimitation_init_default}
#define sd_GapQosChannelSurveyStartCmd_init_default {0}
#define sd_GapQosChannelSurveyStopCmd_init_default {0}
#define sd_GapAdvAddrGetCmd_init_default         {0}
#define sd_GapNextConnEvtCounterGetCmd_init_default {0}
#define sd_GapConnEvtTriggerStartCmd_init_default {0, false, sd_types_BleGapConnEventTrigger_init_default}
#define sd_GapConnEvtTriggerStopCmd_init_default {0}
#define sd_GapAddrSetRsp_init_default            {0}
#define sd_GapAddrGetRsp_init_default            {0, false, sd_types_BleGapAddr_init_default}
#define sd_GapWhitelistSetRsp_init_default       {0}
#define sd_GapDeviceIdentitiesSetRsp_init_default {0}
#define sd_GapPrivacySetRsp_init_default         {0}
#define sd_GapPrivacyGetRsp_init_default         {0, false, sd_types_BleGapPrivacyParams_init_default}
#define sd_GapAdvSetConfigureRsp_init_default    {0, 0}
#define sd_GapAdvStartRsp_init_default           {0}
#define sd_GapAdvStopRsp_init_default            {0}
#define sd_GapConnParamUpdateRsp_init_default    {0}
#define sd_GapDisconnectRsp_init_default         {0}
#define sd_GapTxPowerSetRsp_init_default         {0}
#define sd_GapAppearanceSetRsp_init_default      {0}
#define sd_GapAppearanceGetRsp_init_default      {0, 0}
#define sd_GapPpcpSetRsp_init_default            {0}
#define sd_GapPpcpGetRsp_init_default            {0, false, sd_types_BleGapConnParams_init_default}
#define sd_GapDeviceNameSetRsp_init_default      {0}
#define sd_GapDeviceNameGetRsp_init_default      {0, {0, {0}}, 0}
#define sd_GapAuthenticateRsp_init_default       {0}
#define sd_GapSecParamsReplyRsp_init_default     {0}
#define sd_GapAuthKeyReplyRsp_init_default       {0}
#define sd_GapLescDhkeyReplyRsp_init_default     {0}
#define sd_GapKeypressNotifyRsp_init_default     {0}
#define sd_GapLescOobDataGetRsp_init_default     {0, false, sd_types_BleGapLescOobData_init_default}
#define sd_GapLescOobDataSetRsp_init_default     {0}
#define sd_GapEncryptRsp_init_default            {0}
#define sd_GapSecInfoReplyRsp_init_default       {0}
#define sd_GapConnSecGetRsp_init_default         {0, false, sd_types_BleGapConnSec_init_default}
#define sd_GapRssiStartRsp_init_default          {0}
#define sd_GapRssiStopRsp_init_default           {0}
#define sd_GapScanStartRsp_init_default          {0}
#define sd_GapScanStopRsp_init_default           {0}
#define sd_GapConnectRsp_init_default            {0}
#define sd_GapConnectCancelRsp_init_default      {0}
#define sd_GapRssiGetRsp_init_default            {0, 0}
#define sd_GapPhyUpdateRsp_init_default          {0}
#define sd_GapDataLengthUpdateRsp_init_default   {0, false, sd_types_BleGapDataLengthParams_init_default, false, sd_types_BleGapDataLengthLimitation_init_default}
#define sd_GapQosChannelSurveyStartRsp_init_default {0}
#define sd_GapQosChannelSurveyStopRsp_init_default {0}
#define sd_GapAdvAddrGetRsp_init_default         {0, false, sd_types_BleGapAddr_init_default}
#define sd_GapNextConnEvtCounterGetRsp_init_default {0, 0}
#define sd_GapConnEvtTriggerStartRsp_init_default {0}
#define sd_GapConnEvtTriggerStopRsp_init_default {0}
#define sd_GapEvtConnected_init_default          {false, sd_types_BleGapAddr_init_default, 0, false, sd_types_BleGapConnParams_init_default, 0, false, sd_types_BleGapAdvData_init_default}
#define sd_GapEvtDisconnected_init_default       {0}
#define sd_GapEvtConnParamUpdate_init_default    {false, sd_types_BleGapConnParams_init_default}
#define sd_GapEvtSecParamsRequest_init_default   {false, sd_types_BleGapSecParams_init_default}
#define sd_GapEvtSecInfoRequest_init_default     {false, sd_types_BleGapAddr_init_default, false, sd_types_BleGapMasterId_init_default, 0, 0, 0}
#define sd_GapEvtPasskeyDisplay_init_default     {{0}, 0}
#define sd_GapEvtKeyPressed_init_default         {_sd_types_BleGapKpNotType_MIN}
#define sd_GapEvtAuthKeyRequest_init_default     {_sd_types_BleGapAuthKeyType_MIN}
#define sd_GapEvtLescDhkeyRequest_init_default   {false, sd_types_BleGapLescP256Pk_init_default, 0}
#define sd_GapEvtAuthStatus_init_default         {_sd_types_BleGapSecStatus_MIN, 0, 0, 0, false, sd_types_BleGapSecLevelsT_init_default, false, sd_types_BleGapSecLevelsT_init_default, false, sd_types_BleGapSecKdist_init_default, false, sd_types_BleGapSecKdist_init_default}
#define sd_GapEvtConnSecUpdate_init_default      {false, sd_types_BleGapConnSec_init_default}
#define sd_GapEvtTimeout_init_default            {_sd_types_BleGapTimeoutSrc_MIN, false, sd_types_BleData_init_default}
#define sd_GapEvtRssiChanged_init_default        {0, 0}
#define sd_GapEvtAdvReport_init_default          {false, sd_types_BleGapAdvReportTypeT_init_default, false, sd_types_BleGapAddr_init_default, false, sd_types_BleGapAddr_init_default, _sd_types_BleGapPhy_MIN, _sd_types_BleGapPhy_MIN, 0, 0, 0, 0, 0, false, sd_types_BleData_init_default, false, sd_types_BleGapAuxPointer_init_default}
#define sd_GapEvtSecRequest_init_default         {0, 0, 0, 0}
#define sd_GapEvtConnParamUpdateRequest_init_default {false, sd_types_BleGapConnParams_init_default}
#define sd_GapEvtScanReqReport_init_default      {0, 0, false, sd_types_BleGapAddr_init_default}
#define sd_GapEvtPhyUpdateRequest_init_default   {_sd_types_BleGapPhy_MIN, _sd_types_BleGapPhy_MIN}
#define sd_GapEvtPhyUpdate_init_default          {0, _sd_types_BleGapPhy_MIN, _sd_types_BleGapPhy_MIN}
#define sd_GapEvtDataLengthUpdateRequest_init_default {false, sd_types_BleGapDataLengthParams_init_default}
#define sd_GapEvtDataLengthUpdate_init_default   {false, sd_types_BleGapDataLengthParams_init_default}
#define sd_GapEvtQosChannelSurveyReport_init_default {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define sd_GapEvtAdvSetTerminated_init_default   {_sd_types_BleGapAdvSetTerminatedReason_MIN, 0, 0, false, sd_types_BleGapAdvData_init_default}
#define sd_GapAddrSetCmd_init_zero               {false, sd_types_BleGapAddr_init_zero}
#define sd_GapAddrGetCmd_init_zero               {0}
#define sd_GapWhitelistSetCmd_init_zero          {0, {sd_types_BleGapAddr_init_zero, sd_types_BleGapAddr_init_zero, sd_types_BleGapAddr_init_zero, sd_types_BleGapAddr_init_zero, sd_types_BleGapAddr_init_zero, sd_types_BleGapAddr_init_zero, sd_types_BleGapAddr_init_zero, sd_types_BleGapAddr_init_zero}, 0}
#define sd_GapDeviceIdentitiesSetCmd_init_zero   {0, {sd_types_BleGapIdKey_init_zero, sd_types_BleGapIdKey_init_zero, sd_types_BleGapIdKey_init_zero, sd_types_BleGapIdKey_init_zero, sd_types_BleGapIdKey_init_zero, sd_types_BleGapIdKey_init_zero, sd_types_BleGapIdKey_init_zero, sd_types_BleGapIdKey_init_zero}, 0, {sd_types_BleGapIrk_init_zero, sd_types_BleGapIrk_init_zero, sd_types_BleGapIrk_init_zero, sd_types_BleGapIrk_init_zero, sd_types_BleGapIrk_init_zero, sd_types_BleGapIrk_init_zero, sd_types_BleGapIrk_init_zero, sd_types_BleGapIrk_init_zero}, 0}
#define sd_GapPrivacySetCmd_init_zero            {false, sd_types_BleGapPrivacyParams_init_zero}
#define sd_GapPrivacyGetCmd_init_zero            {0}
#define sd_GapAdvSetConfigureCmd_init_zero       {0, false, sd_types_BleGapAdvData_init_zero, false, sd_types_BleGapAdvParams_init_zero}
#define sd_GapAdvStartCmd_init_zero              {0, 0}
#define sd_GapAdvStopCmd_init_zero               {0}
#define sd_GapConnParamUpdateCmd_init_zero       {0, false, sd_types_BleGapConnParams_init_zero}
#define sd_GapDisconnectCmd_init_zero            {0, 0}
#define sd_GapTxPowerSetCmd_init_zero            {0, 0, 0}
#define sd_GapAppearanceSetCmd_init_zero         {0}
#define sd_GapAppearanceGetCmd_init_zero         {0}
#define sd_GapPpcpSetCmd_init_zero               {false, sd_types_BleGapConnParams_init_zero}
#define sd_GapPpcpGetCmd_init_zero               {0}
#define sd_GapDeviceNameSetCmd_init_zero         {false, sd_types_BleGapConnSecMode_init_zero, {0, {0}}, 0}
#define sd_GapDeviceNameGetCmd_init_zero         {0}
#define sd_GapAuthenticateCmd_init_zero          {0, false, sd_types_BleGapSecParams_init_zero}
#define sd_GapSecParamsReplyCmd_init_zero        {0, _sd_types_BleGapSecStatus_MIN, false, sd_types_BleGapSecParams_init_zero, false, sd_types_BleGapSecKeyset_init_zero}
#define sd_GapAuthKeyReplyCmd_init_zero          {0, _sd_types_BleGapAuthKeyType_MIN, {0, {0}}}
#define sd_GapLescDhkeyReplyCmd_init_zero        {0, false, sd_types_BleGapLescDhkey_init_zero}
#define sd_GapKeypressNotifyCmd_init_zero        {0, _sd_types_BleGapKpNotType_MIN}
#define sd_GapLescOobDataGetCmd_init_zero        {0, false, sd_types_BleGapLescP256Pk_init_zero}
#define sd_GapLescOobDataSetCmd_init_zero        {0, false, sd_types_BleGapLescOobData_init_zero, false, sd_types_BleGapLescOobData_init_zero}
#define sd_GapEncryptCmd_init_zero               {0, false, sd_types_BleGapMasterId_init_zero, false, sd_types_BleGapEncInfo_init_zero}
#define sd_GapSecInfoReplyCmd_init_zero          {0, false, sd_types_BleGapEncInfo_init_zero, false, sd_types_BleGapIrk_init_zero, false, sd_types_BleGapSignInfo_init_zero}
#define sd_GapConnSecGetCmd_init_zero            {0}
#define sd_GapRssiStartCmd_init_zero             {0, 0, 0}
#define sd_GapRssiStopCmd_init_zero              {0}
#define sd_GapScanStartCmd_init_zero             {false, sd_types_BleGapScanParams_init_zero}
#define sd_GapScanStopCmd_init_zero              {0}
#define sd_GapConnectCmd_init_zero               {false, sd_types_BleGapAddr_init_zero, false, sd_types_BleGapScanParams_init_zero, false, sd_types_BleGapConnParams_init_zero, 0}
#define sd_GapConnectCancelCmd_init_zero         {0}
#define sd_GapRssiGetCmd_init_zero               {0}
#define sd_BleGapPhysCmd_init_zero               {_sd_types_BleGapPhy_MIN, _sd_types_BleGapPhy_MIN}
#define sd_GapPhyUpdateCmd_init_zero             {0, false, sd_BleGapPhysCmd_init_zero}
#define sd_GapDataLengthUpdateCmd_init_zero      {0, false, sd_types_BleGapDataLengthParams_init_zero, false, sd_types_BleGapDataLengthLimitation_init_zero}
#define sd_GapQosChannelSurveyStartCmd_init_zero {0}
#define sd_GapQosChannelSurveyStopCmd_init_zero  {0}
#define sd_GapAdvAddrGetCmd_init_zero            {0}
#define sd_GapNextConnEvtCounterGetCmd_init_zero {0}
#define sd_GapConnEvtTriggerStartCmd_init_zero   {0, false, sd_types_BleGapConnEventTrigger_init_zero}
#define sd_GapConnEvtTriggerStopCmd_init_zero    {0}
#define sd_GapAddrSetRsp_init_zero               {0}
#define sd_GapAddrGetRsp_init_zero               {0, false, sd_types_BleGapAddr_init_zero}
#define sd_GapWhitelistSetRsp_init_zero          {0}
#define sd_GapDeviceIdentitiesSetRsp_init_zero   {0}
#define sd_GapPrivacySetRsp_init_zero            {0}
#define sd_GapPrivacyGetRsp_init_zero            {0, false, sd_types_BleGapPrivacyParams_init_zero}
#define sd_GapAdvSetConfigureRsp_init_zero       {0, 0}
#define sd_GapAdvStartRsp_init_zero              {0}
#define sd_GapAdvStopRsp_init_zero               {0}
#define sd_GapConnParamUpdateRsp_init_zero       {0}
#define sd_GapDisconnectRsp_init_zero            {0}
#define sd_GapTxPowerSetRsp_init_zero            {0}
#define sd_GapAppearanceSetRsp_init_zero         {0}
#define sd_GapAppearanceGetRsp_init_zero         {0, 0}
#define sd_GapPpcpSetRsp_init_zero               {0}
#define sd_GapPpcpGetRsp_init_zero               {0, false, sd_types_BleGapConnParams_init_zero}
#define sd_GapDeviceNameSetRsp_init_zero         {0}
#define sd_GapDeviceNameGetRsp_init_zero         {0, {0, {0}}, 0}
#define sd_GapAuthenticateRsp_init_zero          {0}
#define sd_GapSecParamsReplyRsp_init_zero        {0}
#define sd_GapAuthKeyReplyRsp_init_zero          {0}
#define sd_GapLescDhkeyReplyRsp_init_zero        {0}
#define sd_GapKeypressNotifyRsp_init_zero        {0}
#define sd_GapLescOobDataGetRsp_init_zero        {0, false, sd_types_BleGapLescOobData_init_zero}
#define sd_GapLescOobDataSetRsp_init_zero        {0}
#define sd_GapEncryptRsp_init_zero               {0}
#define sd_GapSecInfoReplyRsp_init_zero          {0}
#define sd_GapConnSecGetRsp_init_zero            {0, false, sd_types_BleGapConnSec_init_zero}
#define sd_GapRssiStartRsp_init_zero             {0}
#define sd_GapRssiStopRsp_init_zero              {0}
#define sd_GapScanStartRsp_init_zero             {0}
#define sd_GapScanStopRsp_init_zero              {0}
#define sd_GapConnectRsp_init_zero               {0}
#define sd_GapConnectCancelRsp_init_zero         {0}
#define sd_GapRssiGetRsp_init_zero               {0, 0}
#define sd_GapPhyUpdateRsp_init_zero             {0}
#define sd_GapDataLengthUpdateRsp_init_zero      {0, false, sd_types_BleGapDataLengthParams_init_zero, false, sd_types_BleGapDataLengthLimitation_init_zero}
#define sd_GapQosChannelSurveyStartRsp_init_zero {0}
#define sd_GapQosChannelSurveyStopRsp_init_zero  {0}
#define sd_GapAdvAddrGetRsp_init_zero            {0, false, sd_types_BleGapAddr_init_zero}
#define sd_GapNextConnEvtCounterGetRsp_init_zero {0, 0}
#define sd_GapConnEvtTriggerStartRsp_init_zero   {0}
#define sd_GapConnEvtTriggerStopRsp_init_zero    {0}
#define sd_GapEvtConnected_init_zero             {false, sd_types_BleGapAddr_init_zero, 0, false, sd_types_BleGapConnParams_init_zero, 0, false, sd_types_BleGapAdvData_init_zero}
#define sd_GapEvtDisconnected_init_zero          {0}
#define sd_GapEvtConnParamUpdate_init_zero       {false, sd_types_BleGapConnParams_init_zero}
#define sd_GapEvtSecParamsRequest_init_zero      {false, sd_types_BleGapSecParams_init_zero}
#define sd_GapEvtSecInfoRequest_init_zero        {false, sd_types_BleGapAddr_init_zero, false, sd_types_BleGapMasterId_init_zero, 0, 0, 0}
#define sd_GapEvtPasskeyDisplay_init_zero        {{0}, 0}
#define sd_GapEvtKeyPressed_init_zero            {_sd_types_BleGapKpNotType_MIN}
#define sd_GapEvtAuthKeyRequest_init_zero        {_sd_types_BleGapAuthKeyType_MIN}
#define sd_GapEvtLescDhkeyRequest_init_zero      {false, sd_types_BleGapLescP256Pk_init_zero, 0}
#define sd_GapEvtAuthStatus_init_zero            {_sd_types_BleGapSecStatus_MIN, 0, 0, 0, false, sd_types_BleGapSecLevelsT_init_zero, false, sd_types_BleGapSecLevelsT_init_zero, false, sd_types_BleGapSecKdist_init_zero, false, sd_types_BleGapSecKdist_init_zero}
#define sd_GapEvtConnSecUpdate_init_zero         {false, sd_types_BleGapConnSec_init_zero}
#define sd_GapEvtTimeout_init_zero               {_sd_types_BleGapTimeoutSrc_MIN, false, sd_types_BleData_init_zero}
#define sd_GapEvtRssiChanged_init_zero           {0, 0}
#define sd_GapEvtAdvReport_init_zero             {false, sd_types_BleGapAdvReportTypeT_init_zero, false, sd_types_BleGapAddr_init_zero, false, sd_types_BleGapAddr_init_zero, _sd_types_BleGapPhy_MIN, _sd_types_BleGapPhy_MIN, 0, 0, 0, 0, 0, false, sd_types_BleData_init_zero, false, sd_types_BleGapAuxPointer_init_zero}
#define sd_GapEvtSecRequest_init_zero            {0, 0, 0, 0}
#define sd_GapEvtConnParamUpdateRequest_init_zero {false, sd_types_BleGapConnParams_init_zero}
#define sd_GapEvtScanReqReport_init_zero         {0, 0, false, sd_types_BleGapAddr_init_zero}
#define sd_GapEvtPhyUpdateRequest_init_zero      {_sd_types_BleGapPhy_MIN, _sd_types_BleGapPhy_MIN}
#define sd_GapEvtPhyUpdate_init_zero             {0, _sd_types_BleGapPhy_MIN, _sd_types_BleGapPhy_MIN}
#define sd_GapEvtDataLengthUpdateRequest_init_zero {false, sd_types_BleGapDataLengthParams_init_zero}
#define sd_GapEvtDataLengthUpdate_init_zero      {false, sd_types_BleGapDataLengthParams_init_zero}
#define sd_GapEvtQosChannelSurveyReport_init_zero {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define sd_GapEvtAdvSetTerminated_init_zero      {_sd_types_BleGapAdvSetTerminatedReason_MIN, 0, 0, false, sd_types_BleGapAdvData_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define sd_GapAddrSetCmd_addr_tag                1
#define sd_GapWhitelistSetCmd_wl_addrs_tag       1
#define sd_GapWhitelistSetCmd_len_tag            2
#define sd_GapDeviceIdentitiesSetCmd_id_keys_tag 1
#define sd_GapDeviceIdentitiesSetCmd_local_irks_tag 2
#define sd_GapDeviceIdentitiesSetCmd_len_tag     3
#define sd_GapPrivacySetCmd_privacy_params_tag   1
#define sd_GapAdvSetConfigureCmd_adv_handle_tag  1
#define sd_GapAdvSetConfigureCmd_adv_data_tag    2
#define sd_GapAdvSetConfigureCmd_adv_params_tag  3
#define sd_GapAdvStartCmd_adv_handle_tag         1
#define sd_GapAdvStartCmd_conn_cfg_tag_tag       2
#define sd_GapAdvStopCmd_adv_handle_tag          1
#define sd_GapConnParamUpdateCmd_conn_handle_tag 1
#define sd_GapConnParamUpdateCmd_conn_params_tag 2
#define sd_GapDisconnectCmd_conn_handle_tag      1
#define sd_GapDisconnectCmd_hci_ret_code_code_tag 2
#define sd_GapTxPowerSetCmd_role_tag             1
#define sd_GapTxPowerSetCmd_handle_tag           2
#define sd_GapTxPowerSetCmd_tx_power_tag         3
#define sd_GapAppearanceSetCmd_appearance_tag    1
#define sd_GapPpcpSetCmd_conn_params_tag         1
#define sd_GapDeviceNameSetCmd_write_perm_tag    1
#define sd_GapDeviceNameSetCmd_dev_name_tag      2
#define sd_GapDeviceNameSetCmd_len_tag           3
#define sd_GapAuthenticateCmd_conn_handle_tag    1
#define sd_GapAuthenticateCmd_sec_params_tag     2
#define sd_GapSecParamsReplyCmd_conn_handle_tag  1
#define sd_GapSecParamsReplyCmd_sec_ret_code_tag 2
#define sd_GapSecParamsReplyCmd_sec_params_tag   3
#define sd_GapSecParamsReplyCmd_sec_keyset_tag   4
#define sd_GapAuthKeyReplyCmd_conn_handle_tag    1
#define sd_GapAuthKeyReplyCmd_key_type_tag       2
#define sd_GapAuthKeyReplyCmd_key_tag            3
#define sd_GapLescDhkeyReplyCmd_conn_handle_tag  1
#define sd_GapLescDhkeyReplyCmd_dhkey_tag        2
#define sd_GapKeypressNotifyCmd_conn_handle_tag  1
#define sd_GapKeypressNotifyCmd_kp_not_tag       2
#define sd_GapLescOobDataGetCmd_conn_handle_tag  1
#define sd_GapLescOobDataGetCmd_pk_own_tag       2
#define sd_GapLescOobDataSetCmd_conn_handle_tag  1
#define sd_GapLescOobDataSetCmd_oobd_own_tag     2
#define sd_GapLescOobDataSetCmd_oobd_peer_tag    3
#define sd_GapEncryptCmd_conn_handle_tag         1
#define sd_GapEncryptCmd_master_id_tag           2
#define sd_GapEncryptCmd_enc_info_tag            3
#define sd_GapSecInfoReplyCmd_conn_handle_tag    1
#define sd_GapSecInfoReplyCmd_enc_info_tag       2
#define sd_GapSecInfoReplyCmd_id_info_tag        3
#define sd_GapSecInfoReplyCmd_sign_info_tag      4
#define sd_GapConnSecGetCmd_conn_handle_tag      1
#define sd_GapRssiStartCmd_conn_handle_tag       1
#define sd_GapRssiStartCmd_threshold_dbm_tag     2
#define sd_GapRssiStartCmd_skip_count_tag        3
#define sd_GapRssiStopCmd_conn_handle_tag        1
#define sd_GapScanStartCmd_scan_params_tag       1
#define sd_GapConnectCmd_peer_addr_tag           1
#define sd_GapConnectCmd_scan_params_tag         2
#define sd_GapConnectCmd_conn_params_tag         3
#define sd_GapConnectCmd_conn_cfg_tag_tag        4
#define sd_GapRssiGetCmd_conn_handle_tag         1
#define sd_BleGapPhysCmd_tx_phys_tag             1
#define sd_BleGapPhysCmd_rx_phys_tag             2
#define sd_GapPhyUpdateCmd_conn_handle_tag       1
#define sd_GapPhyUpdateCmd_phys_tag              2
#define sd_GapDataLengthUpdateCmd_conn_handle_tag 1
#define sd_GapDataLengthUpdateCmd_dl_params_tag  2
#define sd_GapDataLengthUpdateCmd_dl_limitation_tag 3
#define sd_GapQosChannelSurveyStartCmd_interval_us_tag 1
#define sd_GapAdvAddrGetCmd_adv_handle_tag       1
#define sd_GapNextConnEvtCounterGetCmd_conn_handle_tag 1
#define sd_GapConnEvtTriggerStartCmd_conn_handle_tag 1
#define sd_GapConnEvtTriggerStartCmd_params_tag  2
#define sd_GapConnEvtTriggerStopCmd_conn_handle_tag 1
#define sd_GapAddrSetRsp_ret_code_tag            1
#define sd_GapAddrGetRsp_ret_code_tag            1
#define sd_GapAddrGetRsp_addr_tag                2
#define sd_GapWhitelistSetRsp_ret_code_tag       1
#define sd_GapDeviceIdentitiesSetRsp_ret_code_tag 1
#define sd_GapPrivacySetRsp_ret_code_tag         1
#define sd_GapPrivacyGetRsp_ret_code_tag         1
#define sd_GapPrivacyGetRsp_privacy_params_tag   2
#define sd_GapAdvSetConfigureRsp_ret_code_tag    1
#define sd_GapAdvSetConfigureRsp_adv_handle_tag  2
#define sd_GapAdvStartRsp_ret_code_tag           1
#define sd_GapAdvStopRsp_ret_code_tag            1
#define sd_GapConnParamUpdateRsp_ret_code_tag    1
#define sd_GapDisconnectRsp_ret_code_tag         1
#define sd_GapTxPowerSetRsp_ret_code_tag         1
#define sd_GapAppearanceSetRsp_ret_code_tag      1
#define sd_GapAppearanceGetRsp_ret_code_tag      1
#define sd_GapAppearanceGetRsp_appearance_tag    2
#define sd_GapPpcpSetRsp_ret_code_tag            1
#define sd_GapPpcpGetRsp_ret_code_tag            1
#define sd_GapPpcpGetRsp_conn_params_tag         2
#define sd_GapDeviceNameSetRsp_ret_code_tag      1
#define sd_GapDeviceNameGetRsp_ret_code_tag      1
#define sd_GapDeviceNameGetRsp_dev_name_tag      2
#define sd_GapDeviceNameGetRsp_len_tag           3
#define sd_GapAuthenticateRsp_ret_code_tag       1
#define sd_GapSecParamsReplyRsp_ret_code_tag     1
#define sd_GapAuthKeyReplyRsp_ret_code_tag       1
#define sd_GapLescDhkeyReplyRsp_ret_code_tag     1
#define sd_GapKeypressNotifyRsp_ret_code_tag     1
#define sd_GapLescOobDataGetRsp_ret_code_tag     1
#define sd_GapLescOobDataGetRsp_oobd_own_tag     2
#define sd_GapLescOobDataSetRsp_ret_code_tag     1
#define sd_GapEncryptRsp_ret_code_tag            1
#define sd_GapSecInfoReplyRsp_ret_code_tag       1
#define sd_GapConnSecGetRsp_ret_code_tag         1
#define sd_GapConnSecGetRsp_conn_sec_tag         2
#define sd_GapRssiStartRsp_ret_code_tag          1
#define sd_GapRssiStopRsp_ret_code_tag           1
#define sd_GapScanStartRsp_ret_code_tag          1
#define sd_GapScanStopRsp_ret_code_tag           1
#define sd_GapConnectRsp_ret_code_tag            1
#define sd_GapConnectCancelRsp_ret_code_tag      1
#define sd_GapRssiGetRsp_ret_code_tag            1
#define sd_GapRssiGetRsp_rssi_tag                2
#define sd_GapPhyUpdateRsp_ret_code_tag          1
#define sd_GapDataLengthUpdateRsp_ret_code_tag   1
#define sd_GapDataLengthUpdateRsp_dl_params_tag  2
#define sd_GapDataLengthUpdateRsp_dl_limitation_tag 3
#define sd_GapQosChannelSurveyStartRsp_ret_code_tag 1
#define sd_GapQosChannelSurveyStopRsp_ret_code_tag 1
#define sd_GapAdvAddrGetRsp_ret_code_tag         1
#define sd_GapAdvAddrGetRsp_addr_tag             2
#define sd_GapNextConnEvtCounterGetRsp_ret_code_tag 1
#define sd_GapNextConnEvtCounterGetRsp_count_tag 2
#define sd_GapConnEvtTriggerStartRsp_ret_code_tag 1
#define sd_GapConnEvtTriggerStopRsp_ret_code_tag 1
#define sd_GapEvtConnected_peer_addr_tag         1
#define sd_GapEvtConnected_role_tag              2
#define sd_GapEvtConnected_conn_params_tag       3
#define sd_GapEvtConnected_adv_handle_tag        4
#define sd_GapEvtConnected_adv_data_tag          5
#define sd_GapEvtDisconnected_reason_tag         1
#define sd_GapEvtConnParamUpdate_conn_params_tag 1
#define sd_GapEvtSecParamsRequest_peer_params_tag 1
#define sd_GapEvtSecInfoRequest_peer_addr_tag    1
#define sd_GapEvtSecInfoRequest_master_id_tag    2
#define sd_GapEvtSecInfoRequest_enc_info_tag     3
#define sd_GapEvtSecInfoRequest_id_info_tag      4
#define sd_GapEvtSecInfoRequest_sign_info_tag    5
#define sd_GapEvtPasskeyDisplay_passkey_tag      1
#define sd_GapEvtPasskeyDisplay_match_request_tag 2
#define sd_GapEvtKeyPressed_kp_not_tag           1
#define sd_GapEvtAuthKeyRequest_key_type_tag     1
#define sd_GapEvtLescDhkeyRequest_pk_peer_tag    1
#define sd_GapEvtLescDhkeyRequest_oobd_req_tag   2
#define sd_GapEvtAuthStatus_auth_status_tag      1
#define sd_GapEvtAuthStatus_error_src_tag        2
#define sd_GapEvtAuthStatus_bonded_tag           3
#define sd_GapEvtAuthStatus_lesc_tag             4
#define sd_GapEvtAuthStatus_sm1_levels_tag       5
#define sd_GapEvtAuthStatus_sm2_levels_tag       6
#define sd_GapEvtAuthStatus_kdist_own_tag        7
#define sd_GapEvtAuthStatus_kdist_peer_tag       8
#define sd_GapEvtConnSecUpdate_conn_sec_tag      1
#define sd_GapEvtTimeout_src_tag                 1
#define sd_GapEvtTimeout_adv_report_buffer_tag   2
#define sd_GapEvtRssiChanged_rssi_tag            1
#define sd_GapEvtRssiChanged_ch_index_tag        2
#define sd_GapEvtAdvReport_type_tag              1
#define sd_GapEvtAdvReport_peer_addr_tag         2
#define sd_GapEvtAdvReport_direct_addr_tag       3
#define sd_GapEvtAdvReport_primary_phy_tag       4
#define sd_GapEvtAdvReport_secondary_phy_tag     5
#define sd_GapEvtAdvReport_tx_power_tag          6
#define sd_GapEvtAdvReport_rssi_tag              7
#define sd_GapEvtAdvReport_ch_index_tag          8
#define sd_GapEvtAdvReport_set_id_tag            9
#define sd_GapEvtAdvReport_data_id_tag           10
#define sd_GapEvtAdvReport_data_tag              11
#define sd_GapEvtAdvReport_aux_pointer_tag       12
#define sd_GapEvtSecRequest_bond_tag             1
#define sd_GapEvtSecRequest_mitm_tag             2
#define sd_GapEvtSecRequest_lesc_tag             3
#define sd_GapEvtSecRequest_keypress_tag         4
#define sd_GapEvtConnParamUpdateRequest_conn_params_tag 1
#define sd_GapEvtScanReqReport_adv_handle_tag    1
#define sd_GapEvtScanReqReport_rssi_tag          2
#define sd_GapEvtScanReqReport_peer_addr_tag     3
#define sd_GapEvtPhyUpdateRequest_tx_phys_tag    1
#define sd_GapEvtPhyUpdateRequest_rx_phys_tag    2
#define sd_GapEvtPhyUpdate_status_tag            1
#define sd_GapEvtPhyUpdate_tx_phy_tag            2
#define sd_GapEvtPhyUpdate_rx_phy_tag            3
#define sd_GapEvtDataLengthUpdateRequest_peer_params_tag 1
#define sd_GapEvtDataLengthUpdate_effective_params_tag 1
#define sd_GapEvtQosChannelSurveyReport_channel_energy_tag 1
#define sd_GapEvtAdvSetTerminated_reason_tag     1
#define sd_GapEvtAdvSetTerminated_adv_handle_tag 2
#define sd_GapEvtAdvSetTerminated_num_completed_adv_events_tag 3
#define sd_GapEvtAdvSetTerminated_adv_data_tag   4

/* Struct field encoding specification for nanopb */
#define sd_GapAddrSetCmd_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  addr,              1)
#define sd_GapAddrSetCmd_CALLBACK NULL
#define sd_GapAddrSetCmd_DEFAULT NULL
#define sd_GapAddrSetCmd_addr_MSGTYPE sd_types_BleGapAddr

#define sd_GapAddrGetCmd_FIELDLIST(X, a) \

#define sd_GapAddrGetCmd_CALLBACK NULL
#define sd_GapAddrGetCmd_DEFAULT NULL

#define sd_GapWhitelistSetCmd_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  wl_addrs,          1) \
X(a, STATIC,   SINGULAR, UINT32,   len,               2)
#define sd_GapWhitelistSetCmd_CALLBACK NULL
#define sd_GapWhitelistSetCmd_DEFAULT NULL
#define sd_GapWhitelistSetCmd_wl_addrs_MSGTYPE sd_types_BleGapAddr

#define sd_GapDeviceIdentitiesSetCmd_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  id_keys,           1) \
X(a, STATIC,   REPEATED, MESSAGE,  local_irks,        2) \
X(a, STATIC,   SINGULAR, UINT32,   len,               3)
#define sd_GapDeviceIdentitiesSetCmd_CALLBACK NULL
#define sd_GapDeviceIdentitiesSetCmd_DEFAULT NULL
#define sd_GapDeviceIdentitiesSetCmd_id_keys_MSGTYPE sd_types_BleGapIdKey
#define sd_GapDeviceIdentitiesSetCmd_local_irks_MSGTYPE sd_types_BleGapIrk

#define sd_GapPrivacySetCmd_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  privacy_params,    1)
#define sd_GapPrivacySetCmd_CALLBACK NULL
#define sd_GapPrivacySetCmd_DEFAULT NULL
#define sd_GapPrivacySetCmd_privacy_params_MSGTYPE sd_types_BleGapPrivacyParams

#define sd_GapPrivacyGetCmd_FIELDLIST(X, a) \

#define sd_GapPrivacyGetCmd_CALLBACK NULL
#define sd_GapPrivacyGetCmd_DEFAULT NULL

#define sd_GapAdvSetConfigureCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   adv_handle,        1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  adv_data,          2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  adv_params,        3)
#define sd_GapAdvSetConfigureCmd_CALLBACK NULL
#define sd_GapAdvSetConfigureCmd_DEFAULT NULL
#define sd_GapAdvSetConfigureCmd_adv_data_MSGTYPE sd_types_BleGapAdvData
#define sd_GapAdvSetConfigureCmd_adv_params_MSGTYPE sd_types_BleGapAdvParams

#define sd_GapAdvStartCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   adv_handle,        1) \
X(a, STATIC,   SINGULAR, UINT32,   conn_cfg_tag,      2)
#define sd_GapAdvStartCmd_CALLBACK NULL
#define sd_GapAdvStartCmd_DEFAULT NULL

#define sd_GapAdvStopCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   adv_handle,        1)
#define sd_GapAdvStopCmd_CALLBACK NULL
#define sd_GapAdvStopCmd_DEFAULT NULL

#define sd_GapConnParamUpdateCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   conn_handle,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  conn_params,       2)
#define sd_GapConnParamUpdateCmd_CALLBACK NULL
#define sd_GapConnParamUpdateCmd_DEFAULT NULL
#define sd_GapConnParamUpdateCmd_conn_params_MSGTYPE sd_types_BleGapConnParams

#define sd_GapDisconnectCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   conn_handle,       1) \
X(a, STATIC,   SINGULAR, UINT32,   hci_ret_code_code,   2)
#define sd_GapDisconnectCmd_CALLBACK NULL
#define sd_GapDisconnectCmd_DEFAULT NULL

#define sd_GapTxPowerSetCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   role,              1) \
X(a, STATIC,   SINGULAR, UINT32,   handle,            2) \
X(a, STATIC,   SINGULAR, SINT32,   tx_power,          3)
#define sd_GapTxPowerSetCmd_CALLBACK NULL
#define sd_GapTxPowerSetCmd_DEFAULT NULL

#define sd_GapAppearanceSetCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   appearance,        1)
#define sd_GapAppearanceSetCmd_CALLBACK NULL
#define sd_GapAppearanceSetCmd_DEFAULT NULL

#define sd_GapAppearanceGetCmd_FIELDLIST(X, a) \

#define sd_GapAppearanceGetCmd_CALLBACK NULL
#define sd_GapAppearanceGetCmd_DEFAULT NULL

#define sd_GapPpcpSetCmd_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  conn_params,       1)
#define sd_GapPpcpSetCmd_CALLBACK NULL
#define sd_GapPpcpSetCmd_DEFAULT NULL
#define sd_GapPpcpSetCmd_conn_params_MSGTYPE sd_types_BleGapConnParams

#define sd_GapPpcpGetCmd_FIELDLIST(X, a) \

#define sd_GapPpcpGetCmd_CALLBACK NULL
#define sd_GapPpcpGetCmd_DEFAULT NULL

#define sd_GapDeviceNameSetCmd_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  write_perm,        1) \
X(a, STATIC,   SINGULAR, BYTES,    dev_name,          2) \
X(a, STATIC,   SINGULAR, UINT32,   len,               3)
#define sd_GapDeviceNameSetCmd_CALLBACK NULL
#define sd_GapDeviceNameSetCmd_DEFAULT NULL
#define sd_GapDeviceNameSetCmd_write_perm_MSGTYPE sd_types_BleGapConnSecMode

#define sd_GapDeviceNameGetCmd_FIELDLIST(X, a) \

#define sd_GapDeviceNameGetCmd_CALLBACK NULL
#define sd_GapDeviceNameGetCmd_DEFAULT NULL

#define sd_GapAuthenticateCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   conn_handle,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sec_params,        2)
#define sd_GapAuthenticateCmd_CALLBACK NULL
#define sd_GapAuthenticateCmd_DEFAULT NULL
#define sd_GapAuthenticateCmd_sec_params_MSGTYPE sd_types_BleGapSecParams

#define sd_GapSecParamsReplyCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   conn_handle,       1) \
X(a, STATIC,   SINGULAR, UENUM,    sec_ret_code,      2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sec_params,        3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sec_keyset,        4)
#define sd_GapSecParamsReplyCmd_CALLBACK NULL
#define sd_GapSecParamsReplyCmd_DEFAULT NULL
#define sd_GapSecParamsReplyCmd_sec_params_MSGTYPE sd_types_BleGapSecParams
#define sd_GapSecParamsReplyCmd_sec_keyset_MSGTYPE sd_types_BleGapSecKeyset

#define sd_GapAuthKeyReplyCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   conn_handle,       1) \
X(a, STATIC,   SINGULAR, UENUM,    key_type,          2) \
X(a, STATIC,   SINGULAR, BYTES,    key,               3)
#define sd_GapAuthKeyReplyCmd_CALLBACK NULL
#define sd_GapAuthKeyReplyCmd_DEFAULT NULL

#define sd_GapLescDhkeyReplyCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   conn_handle,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  dhkey,             2)
#define sd_GapLescDhkeyReplyCmd_CALLBACK NULL
#define sd_GapLescDhkeyReplyCmd_DEFAULT NULL
#define sd_GapLescDhkeyReplyCmd_dhkey_MSGTYPE sd_types_BleGapLescDhkey

#define sd_GapKeypressNotifyCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   conn_handle,       1) \
X(a, STATIC,   SINGULAR, UENUM,    kp_not,            2)
#define sd_GapKeypressNotifyCmd_CALLBACK NULL
#define sd_GapKeypressNotifyCmd_DEFAULT NULL

#define sd_GapLescOobDataGetCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   conn_handle,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pk_own,            2)
#define sd_GapLescOobDataGetCmd_CALLBACK NULL
#define sd_GapLescOobDataGetCmd_DEFAULT NULL
#define sd_GapLescOobDataGetCmd_pk_own_MSGTYPE sd_types_BleGapLescP256Pk

#define sd_GapLescOobDataSetCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   conn_handle,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  oobd_own,          2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  oobd_peer,         3)
#define sd_GapLescOobDataSetCmd_CALLBACK NULL
#define sd_GapLescOobDataSetCmd_DEFAULT NULL
#define sd_GapLescOobDataSetCmd_oobd_own_MSGTYPE sd_types_BleGapLescOobData
#define sd_GapLescOobDataSetCmd_oobd_peer_MSGTYPE sd_types_BleGapLescOobData

#define sd_GapEncryptCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   conn_handle,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  master_id,         2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  enc_info,          3)
#define sd_GapEncryptCmd_CALLBACK NULL
#define sd_GapEncryptCmd_DEFAULT NULL
#define sd_GapEncryptCmd_master_id_MSGTYPE sd_types_BleGapMasterId
#define sd_GapEncryptCmd_enc_info_MSGTYPE sd_types_BleGapEncInfo

#define sd_GapSecInfoReplyCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   conn_handle,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  enc_info,          2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  id_info,           3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sign_info,         4)
#define sd_GapSecInfoReplyCmd_CALLBACK NULL
#define sd_GapSecInfoReplyCmd_DEFAULT NULL
#define sd_GapSecInfoReplyCmd_enc_info_MSGTYPE sd_types_BleGapEncInfo
#define sd_GapSecInfoReplyCmd_id_info_MSGTYPE sd_types_BleGapIrk
#define sd_GapSecInfoReplyCmd_sign_info_MSGTYPE sd_types_BleGapSignInfo

#define sd_GapConnSecGetCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   conn_handle,       1)
#define sd_GapConnSecGetCmd_CALLBACK NULL
#define sd_GapConnSecGetCmd_DEFAULT NULL

#define sd_GapRssiStartCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   conn_handle,       1) \
X(a, STATIC,   SINGULAR, UINT32,   threshold_dbm,     2) \
X(a, STATIC,   SINGULAR, UINT32,   skip_count,        3)
#define sd_GapRssiStartCmd_CALLBACK NULL
#define sd_GapRssiStartCmd_DEFAULT NULL

#define sd_GapRssiStopCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   conn_handle,       1)
#define sd_GapRssiStopCmd_CALLBACK NULL
#define sd_GapRssiStopCmd_DEFAULT NULL

#define sd_GapScanStartCmd_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  scan_params,       1)
#define sd_GapScanStartCmd_CALLBACK NULL
#define sd_GapScanStartCmd_DEFAULT NULL
#define sd_GapScanStartCmd_scan_params_MSGTYPE sd_types_BleGapScanParams

#define sd_GapScanStopCmd_FIELDLIST(X, a) \

#define sd_GapScanStopCmd_CALLBACK NULL
#define sd_GapScanStopCmd_DEFAULT NULL

#define sd_GapConnectCmd_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  peer_addr,         1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  scan_params,       2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  conn_params,       3) \
X(a, STATIC,   SINGULAR, UINT32,   conn_cfg_tag,      4)
#define sd_GapConnectCmd_CALLBACK NULL
#define sd_GapConnectCmd_DEFAULT NULL
#define sd_GapConnectCmd_peer_addr_MSGTYPE sd_types_BleGapAddr
#define sd_GapConnectCmd_scan_params_MSGTYPE sd_types_BleGapScanParams
#define sd_GapConnectCmd_conn_params_MSGTYPE sd_types_BleGapConnParams

#define sd_GapConnectCancelCmd_FIELDLIST(X, a) \

#define sd_GapConnectCancelCmd_CALLBACK NULL
#define sd_GapConnectCancelCmd_DEFAULT NULL

#define sd_GapRssiGetCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   conn_handle,       1)
#define sd_GapRssiGetCmd_CALLBACK NULL
#define sd_GapRssiGetCmd_DEFAULT NULL

#define sd_BleGapPhysCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    tx_phys,           1) \
X(a, STATIC,   SINGULAR, UENUM,    rx_phys,           2)
#define sd_BleGapPhysCmd_CALLBACK NULL
#define sd_BleGapPhysCmd_DEFAULT NULL

#define sd_GapPhyUpdateCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   conn_handle,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  phys,              2)
#define sd_GapPhyUpdateCmd_CALLBACK NULL
#define sd_GapPhyUpdateCmd_DEFAULT NULL
#define sd_GapPhyUpdateCmd_phys_MSGTYPE sd_BleGapPhysCmd

#define sd_GapDataLengthUpdateCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   conn_handle,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  dl_params,         2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  dl_limitation,     3)
#define sd_GapDataLengthUpdateCmd_CALLBACK NULL
#define sd_GapDataLengthUpdateCmd_DEFAULT NULL
#define sd_GapDataLengthUpdateCmd_dl_params_MSGTYPE sd_types_BleGapDataLengthParams
#define sd_GapDataLengthUpdateCmd_dl_limitation_MSGTYPE sd_types_BleGapDataLengthLimitation

#define sd_GapQosChannelSurveyStartCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   interval_us,       1)
#define sd_GapQosChannelSurveyStartCmd_CALLBACK NULL
#define sd_GapQosChannelSurveyStartCmd_DEFAULT NULL

#define sd_GapQosChannelSurveyStopCmd_FIELDLIST(X, a) \

#define sd_GapQosChannelSurveyStopCmd_CALLBACK NULL
#define sd_GapQosChannelSurveyStopCmd_DEFAULT NULL

#define sd_GapAdvAddrGetCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   adv_handle,        1)
#define sd_GapAdvAddrGetCmd_CALLBACK NULL
#define sd_GapAdvAddrGetCmd_DEFAULT NULL

#define sd_GapNextConnEvtCounterGetCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   conn_handle,       1)
#define sd_GapNextConnEvtCounterGetCmd_CALLBACK NULL
#define sd_GapNextConnEvtCounterGetCmd_DEFAULT NULL

#define sd_GapConnEvtTriggerStartCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   conn_handle,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  params,            2)
#define sd_GapConnEvtTriggerStartCmd_CALLBACK NULL
#define sd_GapConnEvtTriggerStartCmd_DEFAULT NULL
#define sd_GapConnEvtTriggerStartCmd_params_MSGTYPE sd_types_BleGapConnEventTrigger

#define sd_GapConnEvtTriggerStopCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   conn_handle,       1)
#define sd_GapConnEvtTriggerStopCmd_CALLBACK NULL
#define sd_GapConnEvtTriggerStopCmd_DEFAULT NULL

#define sd_GapAddrSetRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GapAddrSetRsp_CALLBACK NULL
#define sd_GapAddrSetRsp_DEFAULT NULL

#define sd_GapAddrGetRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  addr,              2)
#define sd_GapAddrGetRsp_CALLBACK NULL
#define sd_GapAddrGetRsp_DEFAULT NULL
#define sd_GapAddrGetRsp_addr_MSGTYPE sd_types_BleGapAddr

#define sd_GapWhitelistSetRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GapWhitelistSetRsp_CALLBACK NULL
#define sd_GapWhitelistSetRsp_DEFAULT NULL

#define sd_GapDeviceIdentitiesSetRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GapDeviceIdentitiesSetRsp_CALLBACK NULL
#define sd_GapDeviceIdentitiesSetRsp_DEFAULT NULL

#define sd_GapPrivacySetRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GapPrivacySetRsp_CALLBACK NULL
#define sd_GapPrivacySetRsp_DEFAULT NULL

#define sd_GapPrivacyGetRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  privacy_params,    2)
#define sd_GapPrivacyGetRsp_CALLBACK NULL
#define sd_GapPrivacyGetRsp_DEFAULT NULL
#define sd_GapPrivacyGetRsp_privacy_params_MSGTYPE sd_types_BleGapPrivacyParams

#define sd_GapAdvSetConfigureRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1) \
X(a, STATIC,   SINGULAR, UINT32,   adv_handle,        2)
#define sd_GapAdvSetConfigureRsp_CALLBACK NULL
#define sd_GapAdvSetConfigureRsp_DEFAULT NULL

#define sd_GapAdvStartRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GapAdvStartRsp_CALLBACK NULL
#define sd_GapAdvStartRsp_DEFAULT NULL

#define sd_GapAdvStopRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GapAdvStopRsp_CALLBACK NULL
#define sd_GapAdvStopRsp_DEFAULT NULL

#define sd_GapConnParamUpdateRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GapConnParamUpdateRsp_CALLBACK NULL
#define sd_GapConnParamUpdateRsp_DEFAULT NULL

#define sd_GapDisconnectRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GapDisconnectRsp_CALLBACK NULL
#define sd_GapDisconnectRsp_DEFAULT NULL

#define sd_GapTxPowerSetRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GapTxPowerSetRsp_CALLBACK NULL
#define sd_GapTxPowerSetRsp_DEFAULT NULL

#define sd_GapAppearanceSetRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GapAppearanceSetRsp_CALLBACK NULL
#define sd_GapAppearanceSetRsp_DEFAULT NULL

#define sd_GapAppearanceGetRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1) \
X(a, STATIC,   SINGULAR, UINT32,   appearance,        2)
#define sd_GapAppearanceGetRsp_CALLBACK NULL
#define sd_GapAppearanceGetRsp_DEFAULT NULL

#define sd_GapPpcpSetRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GapPpcpSetRsp_CALLBACK NULL
#define sd_GapPpcpSetRsp_DEFAULT NULL

#define sd_GapPpcpGetRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  conn_params,       2)
#define sd_GapPpcpGetRsp_CALLBACK NULL
#define sd_GapPpcpGetRsp_DEFAULT NULL
#define sd_GapPpcpGetRsp_conn_params_MSGTYPE sd_types_BleGapConnParams

#define sd_GapDeviceNameSetRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GapDeviceNameSetRsp_CALLBACK NULL
#define sd_GapDeviceNameSetRsp_DEFAULT NULL

#define sd_GapDeviceNameGetRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1) \
X(a, STATIC,   SINGULAR, BYTES,    dev_name,          2) \
X(a, STATIC,   SINGULAR, UINT32,   len,               3)
#define sd_GapDeviceNameGetRsp_CALLBACK NULL
#define sd_GapDeviceNameGetRsp_DEFAULT NULL

#define sd_GapAuthenticateRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GapAuthenticateRsp_CALLBACK NULL
#define sd_GapAuthenticateRsp_DEFAULT NULL

#define sd_GapSecParamsReplyRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GapSecParamsReplyRsp_CALLBACK NULL
#define sd_GapSecParamsReplyRsp_DEFAULT NULL

#define sd_GapAuthKeyReplyRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GapAuthKeyReplyRsp_CALLBACK NULL
#define sd_GapAuthKeyReplyRsp_DEFAULT NULL

#define sd_GapLescDhkeyReplyRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GapLescDhkeyReplyRsp_CALLBACK NULL
#define sd_GapLescDhkeyReplyRsp_DEFAULT NULL

#define sd_GapKeypressNotifyRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GapKeypressNotifyRsp_CALLBACK NULL
#define sd_GapKeypressNotifyRsp_DEFAULT NULL

#define sd_GapLescOobDataGetRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  oobd_own,          2)
#define sd_GapLescOobDataGetRsp_CALLBACK NULL
#define sd_GapLescOobDataGetRsp_DEFAULT NULL
#define sd_GapLescOobDataGetRsp_oobd_own_MSGTYPE sd_types_BleGapLescOobData

#define sd_GapLescOobDataSetRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GapLescOobDataSetRsp_CALLBACK NULL
#define sd_GapLescOobDataSetRsp_DEFAULT NULL

#define sd_GapEncryptRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GapEncryptRsp_CALLBACK NULL
#define sd_GapEncryptRsp_DEFAULT NULL

#define sd_GapSecInfoReplyRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GapSecInfoReplyRsp_CALLBACK NULL
#define sd_GapSecInfoReplyRsp_DEFAULT NULL

#define sd_GapConnSecGetRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  conn_sec,          2)
#define sd_GapConnSecGetRsp_CALLBACK NULL
#define sd_GapConnSecGetRsp_DEFAULT NULL
#define sd_GapConnSecGetRsp_conn_sec_MSGTYPE sd_types_BleGapConnSec

#define sd_GapRssiStartRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GapRssiStartRsp_CALLBACK NULL
#define sd_GapRssiStartRsp_DEFAULT NULL

#define sd_GapRssiStopRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GapRssiStopRsp_CALLBACK NULL
#define sd_GapRssiStopRsp_DEFAULT NULL

#define sd_GapScanStartRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GapScanStartRsp_CALLBACK NULL
#define sd_GapScanStartRsp_DEFAULT NULL

#define sd_GapScanStopRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GapScanStopRsp_CALLBACK NULL
#define sd_GapScanStopRsp_DEFAULT NULL

#define sd_GapConnectRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GapConnectRsp_CALLBACK NULL
#define sd_GapConnectRsp_DEFAULT NULL

#define sd_GapConnectCancelRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GapConnectCancelRsp_CALLBACK NULL
#define sd_GapConnectCancelRsp_DEFAULT NULL

#define sd_GapRssiGetRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1) \
X(a, STATIC,   SINGULAR, SINT32,   rssi,              2)
#define sd_GapRssiGetRsp_CALLBACK NULL
#define sd_GapRssiGetRsp_DEFAULT NULL

#define sd_GapPhyUpdateRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GapPhyUpdateRsp_CALLBACK NULL
#define sd_GapPhyUpdateRsp_DEFAULT NULL

#define sd_GapDataLengthUpdateRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  dl_params,         2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  dl_limitation,     3)
#define sd_GapDataLengthUpdateRsp_CALLBACK NULL
#define sd_GapDataLengthUpdateRsp_DEFAULT NULL
#define sd_GapDataLengthUpdateRsp_dl_params_MSGTYPE sd_types_BleGapDataLengthParams
#define sd_GapDataLengthUpdateRsp_dl_limitation_MSGTYPE sd_types_BleGapDataLengthLimitation

#define sd_GapQosChannelSurveyStartRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GapQosChannelSurveyStartRsp_CALLBACK NULL
#define sd_GapQosChannelSurveyStartRsp_DEFAULT NULL

#define sd_GapQosChannelSurveyStopRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GapQosChannelSurveyStopRsp_CALLBACK NULL
#define sd_GapQosChannelSurveyStopRsp_DEFAULT NULL

#define sd_GapAdvAddrGetRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  addr,              2)
#define sd_GapAdvAddrGetRsp_CALLBACK NULL
#define sd_GapAdvAddrGetRsp_DEFAULT NULL
#define sd_GapAdvAddrGetRsp_addr_MSGTYPE sd_types_BleGapAddr

#define sd_GapNextConnEvtCounterGetRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1) \
X(a, STATIC,   SINGULAR, UINT32,   count,             2)
#define sd_GapNextConnEvtCounterGetRsp_CALLBACK NULL
#define sd_GapNextConnEvtCounterGetRsp_DEFAULT NULL

#define sd_GapConnEvtTriggerStartRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GapConnEvtTriggerStartRsp_CALLBACK NULL
#define sd_GapConnEvtTriggerStartRsp_DEFAULT NULL

#define sd_GapConnEvtTriggerStopRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GapConnEvtTriggerStopRsp_CALLBACK NULL
#define sd_GapConnEvtTriggerStopRsp_DEFAULT NULL

#define sd_GapEvtConnected_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  peer_addr,         1) \
X(a, STATIC,   SINGULAR, UINT32,   role,              2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  conn_params,       3) \
X(a, STATIC,   SINGULAR, UINT32,   adv_handle,        4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  adv_data,          5)
#define sd_GapEvtConnected_CALLBACK NULL
#define sd_GapEvtConnected_DEFAULT NULL
#define sd_GapEvtConnected_peer_addr_MSGTYPE sd_types_BleGapAddr
#define sd_GapEvtConnected_conn_params_MSGTYPE sd_types_BleGapConnParams
#define sd_GapEvtConnected_adv_data_MSGTYPE sd_types_BleGapAdvData

#define sd_GapEvtDisconnected_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   reason,            1)
#define sd_GapEvtDisconnected_CALLBACK NULL
#define sd_GapEvtDisconnected_DEFAULT NULL

#define sd_GapEvtConnParamUpdate_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  conn_params,       1)
#define sd_GapEvtConnParamUpdate_CALLBACK NULL
#define sd_GapEvtConnParamUpdate_DEFAULT NULL
#define sd_GapEvtConnParamUpdate_conn_params_MSGTYPE sd_types_BleGapConnParams

#define sd_GapEvtSecParamsRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  peer_params,       1)
#define sd_GapEvtSecParamsRequest_CALLBACK NULL
#define sd_GapEvtSecParamsRequest_DEFAULT NULL
#define sd_GapEvtSecParamsRequest_peer_params_MSGTYPE sd_types_BleGapSecParams

#define sd_GapEvtSecInfoRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  peer_addr,         1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  master_id,         2) \
X(a, STATIC,   SINGULAR, UINT32,   enc_info,          3) \
X(a, STATIC,   SINGULAR, UINT32,   id_info,           4) \
X(a, STATIC,   SINGULAR, UINT32,   sign_info,         5)
#define sd_GapEvtSecInfoRequest_CALLBACK NULL
#define sd_GapEvtSecInfoRequest_DEFAULT NULL
#define sd_GapEvtSecInfoRequest_peer_addr_MSGTYPE sd_types_BleGapAddr
#define sd_GapEvtSecInfoRequest_master_id_MSGTYPE sd_types_BleGapMasterId

#define sd_GapEvtPasskeyDisplay_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, passkey,           1) \
X(a, STATIC,   SINGULAR, BOOL,     match_request,     2)
#define sd_GapEvtPasskeyDisplay_CALLBACK NULL
#define sd_GapEvtPasskeyDisplay_DEFAULT NULL

#define sd_GapEvtKeyPressed_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    kp_not,            1)
#define sd_GapEvtKeyPressed_CALLBACK NULL
#define sd_GapEvtKeyPressed_DEFAULT NULL

#define sd_GapEvtAuthKeyRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    key_type,          1)
#define sd_GapEvtAuthKeyRequest_CALLBACK NULL
#define sd_GapEvtAuthKeyRequest_DEFAULT NULL

#define sd_GapEvtLescDhkeyRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pk_peer,           1) \
X(a, STATIC,   SINGULAR, BOOL,     oobd_req,          2)
#define sd_GapEvtLescDhkeyRequest_CALLBACK NULL
#define sd_GapEvtLescDhkeyRequest_DEFAULT NULL
#define sd_GapEvtLescDhkeyRequest_pk_peer_MSGTYPE sd_types_BleGapLescP256Pk

#define sd_GapEvtAuthStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    auth_status,       1) \
X(a, STATIC,   SINGULAR, UINT32,   error_src,         2) \
X(a, STATIC,   SINGULAR, BOOL,     bonded,            3) \
X(a, STATIC,   SINGULAR, BOOL,     lesc,              4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sm1_levels,        5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sm2_levels,        6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  kdist_own,         7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  kdist_peer,        8)
#define sd_GapEvtAuthStatus_CALLBACK NULL
#define sd_GapEvtAuthStatus_DEFAULT NULL
#define sd_GapEvtAuthStatus_sm1_levels_MSGTYPE sd_types_BleGapSecLevelsT
#define sd_GapEvtAuthStatus_sm2_levels_MSGTYPE sd_types_BleGapSecLevelsT
#define sd_GapEvtAuthStatus_kdist_own_MSGTYPE sd_types_BleGapSecKdist
#define sd_GapEvtAuthStatus_kdist_peer_MSGTYPE sd_types_BleGapSecKdist

#define sd_GapEvtConnSecUpdate_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  conn_sec,          1)
#define sd_GapEvtConnSecUpdate_CALLBACK NULL
#define sd_GapEvtConnSecUpdate_DEFAULT NULL
#define sd_GapEvtConnSecUpdate_conn_sec_MSGTYPE sd_types_BleGapConnSec

#define sd_GapEvtTimeout_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    src,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  adv_report_buffer,   2)
#define sd_GapEvtTimeout_CALLBACK NULL
#define sd_GapEvtTimeout_DEFAULT NULL
#define sd_GapEvtTimeout_adv_report_buffer_MSGTYPE sd_types_BleData

#define sd_GapEvtRssiChanged_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   rssi,              1) \
X(a, STATIC,   SINGULAR, UINT32,   ch_index,          2)
#define sd_GapEvtRssiChanged_CALLBACK NULL
#define sd_GapEvtRssiChanged_DEFAULT NULL

#define sd_GapEvtAdvReport_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  type,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  peer_addr,         2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  direct_addr,       3) \
X(a, STATIC,   SINGULAR, UENUM,    primary_phy,       4) \
X(a, STATIC,   SINGULAR, UENUM,    secondary_phy,     5) \
X(a, STATIC,   SINGULAR, SINT32,   tx_power,          6) \
X(a, STATIC,   SINGULAR, SINT32,   rssi,              7) \
X(a, STATIC,   SINGULAR, UINT32,   ch_index,          8) \
X(a, STATIC,   SINGULAR, UINT32,   set_id,            9) \
X(a, STATIC,   SINGULAR, UINT32,   data_id,          10) \
X(a, STATIC,   OPTIONAL, MESSAGE,  data,             11) \
X(a, STATIC,   OPTIONAL, MESSAGE,  aux_pointer,      12)
#define sd_GapEvtAdvReport_CALLBACK NULL
#define sd_GapEvtAdvReport_DEFAULT NULL
#define sd_GapEvtAdvReport_type_MSGTYPE sd_types_BleGapAdvReportTypeT
#define sd_GapEvtAdvReport_peer_addr_MSGTYPE sd_types_BleGapAddr
#define sd_GapEvtAdvReport_direct_addr_MSGTYPE sd_types_BleGapAddr
#define sd_GapEvtAdvReport_data_MSGTYPE sd_types_BleData
#define sd_GapEvtAdvReport_aux_pointer_MSGTYPE sd_types_BleGapAuxPointer

#define sd_GapEvtSecRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     bond,              1) \
X(a, STATIC,   SINGULAR, BOOL,     mitm,              2) \
X(a, STATIC,   SINGULAR, BOOL,     lesc,              3) \
X(a, STATIC,   SINGULAR, BOOL,     keypress,          4)
#define sd_GapEvtSecRequest_CALLBACK NULL
#define sd_GapEvtSecRequest_DEFAULT NULL

#define sd_GapEvtConnParamUpdateRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  conn_params,       1)
#define sd_GapEvtConnParamUpdateRequest_CALLBACK NULL
#define sd_GapEvtConnParamUpdateRequest_DEFAULT NULL
#define sd_GapEvtConnParamUpdateRequest_conn_params_MSGTYPE sd_types_BleGapConnParams

#define sd_GapEvtScanReqReport_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   adv_handle,        1) \
X(a, STATIC,   SINGULAR, SINT32,   rssi,              2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  peer_addr,         3)
#define sd_GapEvtScanReqReport_CALLBACK NULL
#define sd_GapEvtScanReqReport_DEFAULT NULL
#define sd_GapEvtScanReqReport_peer_addr_MSGTYPE sd_types_BleGapAddr

#define sd_GapEvtPhyUpdateRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    tx_phys,           1) \
X(a, STATIC,   SINGULAR, UENUM,    rx_phys,           2)
#define sd_GapEvtPhyUpdateRequest_CALLBACK NULL
#define sd_GapEvtPhyUpdateRequest_DEFAULT NULL

#define sd_GapEvtPhyUpdate_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   status,            1) \
X(a, STATIC,   SINGULAR, UENUM,    tx_phy,            2) \
X(a, STATIC,   SINGULAR, UENUM,    rx_phy,            3)
#define sd_GapEvtPhyUpdate_CALLBACK NULL
#define sd_GapEvtPhyUpdate_DEFAULT NULL

#define sd_GapEvtDataLengthUpdateRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  peer_params,       1)
#define sd_GapEvtDataLengthUpdateRequest_CALLBACK NULL
#define sd_GapEvtDataLengthUpdateRequest_DEFAULT NULL
#define sd_GapEvtDataLengthUpdateRequest_peer_params_MSGTYPE sd_types_BleGapDataLengthParams

#define sd_GapEvtDataLengthUpdate_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  effective_params,   1)
#define sd_GapEvtDataLengthUpdate_CALLBACK NULL
#define sd_GapEvtDataLengthUpdate_DEFAULT NULL
#define sd_GapEvtDataLengthUpdate_effective_params_MSGTYPE sd_types_BleGapDataLengthParams

#define sd_GapEvtQosChannelSurveyReport_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, SINT32,   channel_energy,    1)
#define sd_GapEvtQosChannelSurveyReport_CALLBACK NULL
#define sd_GapEvtQosChannelSurveyReport_DEFAULT NULL

#define sd_GapEvtAdvSetTerminated_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    reason,            1) \
X(a, STATIC,   SINGULAR, UINT32,   adv_handle,        2) \
X(a, STATIC,   SINGULAR, UINT32,   num_completed_adv_events,   3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  adv_data,          4)
#define sd_GapEvtAdvSetTerminated_CALLBACK NULL
#define sd_GapEvtAdvSetTerminated_DEFAULT NULL
#define sd_GapEvtAdvSetTerminated_adv_data_MSGTYPE sd_types_BleGapAdvData

extern const pb_msgdesc_t sd_GapAddrSetCmd_msg;
extern const pb_msgdesc_t sd_GapAddrGetCmd_msg;
extern const pb_msgdesc_t sd_GapWhitelistSetCmd_msg;
extern const pb_msgdesc_t sd_GapDeviceIdentitiesSetCmd_msg;
extern const pb_msgdesc_t sd_GapPrivacySetCmd_msg;
extern const pb_msgdesc_t sd_GapPrivacyGetCmd_msg;
extern const pb_msgdesc_t sd_GapAdvSetConfigureCmd_msg;
extern const pb_msgdesc_t sd_GapAdvStartCmd_msg;
extern const pb_msgdesc_t sd_GapAdvStopCmd_msg;
extern const pb_msgdesc_t sd_GapConnParamUpdateCmd_msg;
extern const pb_msgdesc_t sd_GapDisconnectCmd_msg;
extern const pb_msgdesc_t sd_GapTxPowerSetCmd_msg;
extern const pb_msgdesc_t sd_GapAppearanceSetCmd_msg;
extern const pb_msgdesc_t sd_GapAppearanceGetCmd_msg;
extern const pb_msgdesc_t sd_GapPpcpSetCmd_msg;
extern const pb_msgdesc_t sd_GapPpcpGetCmd_msg;
extern const pb_msgdesc_t sd_GapDeviceNameSetCmd_msg;
extern const pb_msgdesc_t sd_GapDeviceNameGetCmd_msg;
extern const pb_msgdesc_t sd_GapAuthenticateCmd_msg;
extern const pb_msgdesc_t sd_GapSecParamsReplyCmd_msg;
extern const pb_msgdesc_t sd_GapAuthKeyReplyCmd_msg;
extern const pb_msgdesc_t sd_GapLescDhkeyReplyCmd_msg;
extern const pb_msgdesc_t sd_GapKeypressNotifyCmd_msg;
extern const pb_msgdesc_t sd_GapLescOobDataGetCmd_msg;
extern const pb_msgdesc_t sd_GapLescOobDataSetCmd_msg;
extern const pb_msgdesc_t sd_GapEncryptCmd_msg;
extern const pb_msgdesc_t sd_GapSecInfoReplyCmd_msg;
extern const pb_msgdesc_t sd_GapConnSecGetCmd_msg;
extern const pb_msgdesc_t sd_GapRssiStartCmd_msg;
extern const pb_msgdesc_t sd_GapRssiStopCmd_msg;
extern const pb_msgdesc_t sd_GapScanStartCmd_msg;
extern const pb_msgdesc_t sd_GapScanStopCmd_msg;
extern const pb_msgdesc_t sd_GapConnectCmd_msg;
extern const pb_msgdesc_t sd_GapConnectCancelCmd_msg;
extern const pb_msgdesc_t sd_GapRssiGetCmd_msg;
extern const pb_msgdesc_t sd_BleGapPhysCmd_msg;
extern const pb_msgdesc_t sd_GapPhyUpdateCmd_msg;
extern const pb_msgdesc_t sd_GapDataLengthUpdateCmd_msg;
extern const pb_msgdesc_t sd_GapQosChannelSurveyStartCmd_msg;
extern const pb_msgdesc_t sd_GapQosChannelSurveyStopCmd_msg;
extern const pb_msgdesc_t sd_GapAdvAddrGetCmd_msg;
extern const pb_msgdesc_t sd_GapNextConnEvtCounterGetCmd_msg;
extern const pb_msgdesc_t sd_GapConnEvtTriggerStartCmd_msg;
extern const pb_msgdesc_t sd_GapConnEvtTriggerStopCmd_msg;
extern const pb_msgdesc_t sd_GapAddrSetRsp_msg;
extern const pb_msgdesc_t sd_GapAddrGetRsp_msg;
extern const pb_msgdesc_t sd_GapWhitelistSetRsp_msg;
extern const pb_msgdesc_t sd_GapDeviceIdentitiesSetRsp_msg;
extern const pb_msgdesc_t sd_GapPrivacySetRsp_msg;
extern const pb_msgdesc_t sd_GapPrivacyGetRsp_msg;
extern const pb_msgdesc_t sd_GapAdvSetConfigureRsp_msg;
extern const pb_msgdesc_t sd_GapAdvStartRsp_msg;
extern const pb_msgdesc_t sd_GapAdvStopRsp_msg;
extern const pb_msgdesc_t sd_GapConnParamUpdateRsp_msg;
extern const pb_msgdesc_t sd_GapDisconnectRsp_msg;
extern const pb_msgdesc_t sd_GapTxPowerSetRsp_msg;
extern const pb_msgdesc_t sd_GapAppearanceSetRsp_msg;
extern const pb_msgdesc_t sd_GapAppearanceGetRsp_msg;
extern const pb_msgdesc_t sd_GapPpcpSetRsp_msg;
extern const pb_msgdesc_t sd_GapPpcpGetRsp_msg;
extern const pb_msgdesc_t sd_GapDeviceNameSetRsp_msg;
extern const pb_msgdesc_t sd_GapDeviceNameGetRsp_msg;
extern const pb_msgdesc_t sd_GapAuthenticateRsp_msg;
extern const pb_msgdesc_t sd_GapSecParamsReplyRsp_msg;
extern const pb_msgdesc_t sd_GapAuthKeyReplyRsp_msg;
extern const pb_msgdesc_t sd_GapLescDhkeyReplyRsp_msg;
extern const pb_msgdesc_t sd_GapKeypressNotifyRsp_msg;
extern const pb_msgdesc_t sd_GapLescOobDataGetRsp_msg;
extern const pb_msgdesc_t sd_GapLescOobDataSetRsp_msg;
extern const pb_msgdesc_t sd_GapEncryptRsp_msg;
extern const pb_msgdesc_t sd_GapSecInfoReplyRsp_msg;
extern const pb_msgdesc_t sd_GapConnSecGetRsp_msg;
extern const pb_msgdesc_t sd_GapRssiStartRsp_msg;
extern const pb_msgdesc_t sd_GapRssiStopRsp_msg;
extern const pb_msgdesc_t sd_GapScanStartRsp_msg;
extern const pb_msgdesc_t sd_GapScanStopRsp_msg;
extern const pb_msgdesc_t sd_GapConnectRsp_msg;
extern const pb_msgdesc_t sd_GapConnectCancelRsp_msg;
extern const pb_msgdesc_t sd_GapRssiGetRsp_msg;
extern const pb_msgdesc_t sd_GapPhyUpdateRsp_msg;
extern const pb_msgdesc_t sd_GapDataLengthUpdateRsp_msg;
extern const pb_msgdesc_t sd_GapQosChannelSurveyStartRsp_msg;
extern const pb_msgdesc_t sd_GapQosChannelSurveyStopRsp_msg;
extern const pb_msgdesc_t sd_GapAdvAddrGetRsp_msg;
extern const pb_msgdesc_t sd_GapNextConnEvtCounterGetRsp_msg;
extern const pb_msgdesc_t sd_GapConnEvtTriggerStartRsp_msg;
extern const pb_msgdesc_t sd_GapConnEvtTriggerStopRsp_msg;
extern const pb_msgdesc_t sd_GapEvtConnected_msg;
extern const pb_msgdesc_t sd_GapEvtDisconnected_msg;
extern const pb_msgdesc_t sd_GapEvtConnParamUpdate_msg;
extern const pb_msgdesc_t sd_GapEvtSecParamsRequest_msg;
extern const pb_msgdesc_t sd_GapEvtSecInfoRequest_msg;
extern const pb_msgdesc_t sd_GapEvtPasskeyDisplay_msg;
extern const pb_msgdesc_t sd_GapEvtKeyPressed_msg;
extern const pb_msgdesc_t sd_GapEvtAuthKeyRequest_msg;
extern const pb_msgdesc_t sd_GapEvtLescDhkeyRequest_msg;
extern const pb_msgdesc_t sd_GapEvtAuthStatus_msg;
extern const pb_msgdesc_t sd_GapEvtConnSecUpdate_msg;
extern const pb_msgdesc_t sd_GapEvtTimeout_msg;
extern const pb_msgdesc_t sd_GapEvtRssiChanged_msg;
extern const pb_msgdesc_t sd_GapEvtAdvReport_msg;
extern const pb_msgdesc_t sd_GapEvtSecRequest_msg;
extern const pb_msgdesc_t sd_GapEvtConnParamUpdateRequest_msg;
extern const pb_msgdesc_t sd_GapEvtScanReqReport_msg;
extern const pb_msgdesc_t sd_GapEvtPhyUpdateRequest_msg;
extern const pb_msgdesc_t sd_GapEvtPhyUpdate_msg;
extern const pb_msgdesc_t sd_GapEvtDataLengthUpdateRequest_msg;
extern const pb_msgdesc_t sd_GapEvtDataLengthUpdate_msg;
extern const pb_msgdesc_t sd_GapEvtQosChannelSurveyReport_msg;
extern const pb_msgdesc_t sd_GapEvtAdvSetTerminated_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define sd_GapAddrSetCmd_fields &sd_GapAddrSetCmd_msg
#define sd_GapAddrGetCmd_fields &sd_GapAddrGetCmd_msg
#define sd_GapWhitelistSetCmd_fields &sd_GapWhitelistSetCmd_msg
#define sd_GapDeviceIdentitiesSetCmd_fields &sd_GapDeviceIdentitiesSetCmd_msg
#define sd_GapPrivacySetCmd_fields &sd_GapPrivacySetCmd_msg
#define sd_GapPrivacyGetCmd_fields &sd_GapPrivacyGetCmd_msg
#define sd_GapAdvSetConfigureCmd_fields &sd_GapAdvSetConfigureCmd_msg
#define sd_GapAdvStartCmd_fields &sd_GapAdvStartCmd_msg
#define sd_GapAdvStopCmd_fields &sd_GapAdvStopCmd_msg
#define sd_GapConnParamUpdateCmd_fields &sd_GapConnParamUpdateCmd_msg
#define sd_GapDisconnectCmd_fields &sd_GapDisconnectCmd_msg
#define sd_GapTxPowerSetCmd_fields &sd_GapTxPowerSetCmd_msg
#define sd_GapAppearanceSetCmd_fields &sd_GapAppearanceSetCmd_msg
#define sd_GapAppearanceGetCmd_fields &sd_GapAppearanceGetCmd_msg
#define sd_GapPpcpSetCmd_fields &sd_GapPpcpSetCmd_msg
#define sd_GapPpcpGetCmd_fields &sd_GapPpcpGetCmd_msg
#define sd_GapDeviceNameSetCmd_fields &sd_GapDeviceNameSetCmd_msg
#define sd_GapDeviceNameGetCmd_fields &sd_GapDeviceNameGetCmd_msg
#define sd_GapAuthenticateCmd_fields &sd_GapAuthenticateCmd_msg
#define sd_GapSecParamsReplyCmd_fields &sd_GapSecParamsReplyCmd_msg
#define sd_GapAuthKeyReplyCmd_fields &sd_GapAuthKeyReplyCmd_msg
#define sd_GapLescDhkeyReplyCmd_fields &sd_GapLescDhkeyReplyCmd_msg
#define sd_GapKeypressNotifyCmd_fields &sd_GapKeypressNotifyCmd_msg
#define sd_GapLescOobDataGetCmd_fields &sd_GapLescOobDataGetCmd_msg
#define sd_GapLescOobDataSetCmd_fields &sd_GapLescOobDataSetCmd_msg
#define sd_GapEncryptCmd_fields &sd_GapEncryptCmd_msg
#define sd_GapSecInfoReplyCmd_fields &sd_GapSecInfoReplyCmd_msg
#define sd_GapConnSecGetCmd_fields &sd_GapConnSecGetCmd_msg
#define sd_GapRssiStartCmd_fields &sd_GapRssiStartCmd_msg
#define sd_GapRssiStopCmd_fields &sd_GapRssiStopCmd_msg
#define sd_GapScanStartCmd_fields &sd_GapScanStartCmd_msg
#define sd_GapScanStopCmd_fields &sd_GapScanStopCmd_msg
#define sd_GapConnectCmd_fields &sd_GapConnectCmd_msg
#define sd_GapConnectCancelCmd_fields &sd_GapConnectCancelCmd_msg
#define sd_GapRssiGetCmd_fields &sd_GapRssiGetCmd_msg
#define sd_BleGapPhysCmd_fields &sd_BleGapPhysCmd_msg
#define sd_GapPhyUpdateCmd_fields &sd_GapPhyUpdateCmd_msg
#define sd_GapDataLengthUpdateCmd_fields &sd_GapDataLengthUpdateCmd_msg
#define sd_GapQosChannelSurveyStartCmd_fields &sd_GapQosChannelSurveyStartCmd_msg
#define sd_GapQosChannelSurveyStopCmd_fields &sd_GapQosChannelSurveyStopCmd_msg
#define sd_GapAdvAddrGetCmd_fields &sd_GapAdvAddrGetCmd_msg
#define sd_GapNextConnEvtCounterGetCmd_fields &sd_GapNextConnEvtCounterGetCmd_msg
#define sd_GapConnEvtTriggerStartCmd_fields &sd_GapConnEvtTriggerStartCmd_msg
#define sd_GapConnEvtTriggerStopCmd_fields &sd_GapConnEvtTriggerStopCmd_msg
#define sd_GapAddrSetRsp_fields &sd_GapAddrSetRsp_msg
#define sd_GapAddrGetRsp_fields &sd_GapAddrGetRsp_msg
#define sd_GapWhitelistSetRsp_fields &sd_GapWhitelistSetRsp_msg
#define sd_GapDeviceIdentitiesSetRsp_fields &sd_GapDeviceIdentitiesSetRsp_msg
#define sd_GapPrivacySetRsp_fields &sd_GapPrivacySetRsp_msg
#define sd_GapPrivacyGetRsp_fields &sd_GapPrivacyGetRsp_msg
#define sd_GapAdvSetConfigureRsp_fields &sd_GapAdvSetConfigureRsp_msg
#define sd_GapAdvStartRsp_fields &sd_GapAdvStartRsp_msg
#define sd_GapAdvStopRsp_fields &sd_GapAdvStopRsp_msg
#define sd_GapConnParamUpdateRsp_fields &sd_GapConnParamUpdateRsp_msg
#define sd_GapDisconnectRsp_fields &sd_GapDisconnectRsp_msg
#define sd_GapTxPowerSetRsp_fields &sd_GapTxPowerSetRsp_msg
#define sd_GapAppearanceSetRsp_fields &sd_GapAppearanceSetRsp_msg
#define sd_GapAppearanceGetRsp_fields &sd_GapAppearanceGetRsp_msg
#define sd_GapPpcpSetRsp_fields &sd_GapPpcpSetRsp_msg
#define sd_GapPpcpGetRsp_fields &sd_GapPpcpGetRsp_msg
#define sd_GapDeviceNameSetRsp_fields &sd_GapDeviceNameSetRsp_msg
#define sd_GapDeviceNameGetRsp_fields &sd_GapDeviceNameGetRsp_msg
#define sd_GapAuthenticateRsp_fields &sd_GapAuthenticateRsp_msg
#define sd_GapSecParamsReplyRsp_fields &sd_GapSecParamsReplyRsp_msg
#define sd_GapAuthKeyReplyRsp_fields &sd_GapAuthKeyReplyRsp_msg
#define sd_GapLescDhkeyReplyRsp_fields &sd_GapLescDhkeyReplyRsp_msg
#define sd_GapKeypressNotifyRsp_fields &sd_GapKeypressNotifyRsp_msg
#define sd_GapLescOobDataGetRsp_fields &sd_GapLescOobDataGetRsp_msg
#define sd_GapLescOobDataSetRsp_fields &sd_GapLescOobDataSetRsp_msg
#define sd_GapEncryptRsp_fields &sd_GapEncryptRsp_msg
#define sd_GapSecInfoReplyRsp_fields &sd_GapSecInfoReplyRsp_msg
#define sd_GapConnSecGetRsp_fields &sd_GapConnSecGetRsp_msg
#define sd_GapRssiStartRsp_fields &sd_GapRssiStartRsp_msg
#define sd_GapRssiStopRsp_fields &sd_GapRssiStopRsp_msg
#define sd_GapScanStartRsp_fields &sd_GapScanStartRsp_msg
#define sd_GapScanStopRsp_fields &sd_GapScanStopRsp_msg
#define sd_GapConnectRsp_fields &sd_GapConnectRsp_msg
#define sd_GapConnectCancelRsp_fields &sd_GapConnectCancelRsp_msg
#define sd_GapRssiGetRsp_fields &sd_GapRssiGetRsp_msg
#define sd_GapPhyUpdateRsp_fields &sd_GapPhyUpdateRsp_msg
#define sd_GapDataLengthUpdateRsp_fields &sd_GapDataLengthUpdateRsp_msg
#define sd_GapQosChannelSurveyStartRsp_fields &sd_GapQosChannelSurveyStartRsp_msg
#define sd_GapQosChannelSurveyStopRsp_fields &sd_GapQosChannelSurveyStopRsp_msg
#define sd_GapAdvAddrGetRsp_fields &sd_GapAdvAddrGetRsp_msg
#define sd_GapNextConnEvtCounterGetRsp_fields &sd_GapNextConnEvtCounterGetRsp_msg
#define sd_GapConnEvtTriggerStartRsp_fields &sd_GapConnEvtTriggerStartRsp_msg
#define sd_GapConnEvtTriggerStopRsp_fields &sd_GapConnEvtTriggerStopRsp_msg
#define sd_GapEvtConnected_fields &sd_GapEvtConnected_msg
#define sd_GapEvtDisconnected_fields &sd_GapEvtDisconnected_msg
#define sd_GapEvtConnParamUpdate_fields &sd_GapEvtConnParamUpdate_msg
#define sd_GapEvtSecParamsRequest_fields &sd_GapEvtSecParamsRequest_msg
#define sd_GapEvtSecInfoRequest_fields &sd_GapEvtSecInfoRequest_msg
#define sd_GapEvtPasskeyDisplay_fields &sd_GapEvtPasskeyDisplay_msg
#define sd_GapEvtKeyPressed_fields &sd_GapEvtKeyPressed_msg
#define sd_GapEvtAuthKeyRequest_fields &sd_GapEvtAuthKeyRequest_msg
#define sd_GapEvtLescDhkeyRequest_fields &sd_GapEvtLescDhkeyRequest_msg
#define sd_GapEvtAuthStatus_fields &sd_GapEvtAuthStatus_msg
#define sd_GapEvtConnSecUpdate_fields &sd_GapEvtConnSecUpdate_msg
#define sd_GapEvtTimeout_fields &sd_GapEvtTimeout_msg
#define sd_GapEvtRssiChanged_fields &sd_GapEvtRssiChanged_msg
#define sd_GapEvtAdvReport_fields &sd_GapEvtAdvReport_msg
#define sd_GapEvtSecRequest_fields &sd_GapEvtSecRequest_msg
#define sd_GapEvtConnParamUpdateRequest_fields &sd_GapEvtConnParamUpdateRequest_msg
#define sd_GapEvtScanReqReport_fields &sd_GapEvtScanReqReport_msg
#define sd_GapEvtPhyUpdateRequest_fields &sd_GapEvtPhyUpdateRequest_msg
#define sd_GapEvtPhyUpdate_fields &sd_GapEvtPhyUpdate_msg
#define sd_GapEvtDataLengthUpdateRequest_fields &sd_GapEvtDataLengthUpdateRequest_msg
#define sd_GapEvtDataLengthUpdate_fields &sd_GapEvtDataLengthUpdate_msg
#define sd_GapEvtQosChannelSurveyReport_fields &sd_GapEvtQosChannelSurveyReport_msg
#define sd_GapEvtAdvSetTerminated_fields &sd_GapEvtAdvSetTerminated_msg

/* Maximum encoded size of messages (where known) */
#define SD_SOFTDEVICE_GAP_PB_H_MAX_SIZE          sd_GapAdvSetConfigureCmd_size
#define sd_BleGapPhysCmd_size                    6
#define sd_GapAddrGetCmd_size                    0
#define sd_GapAddrGetRsp_size                    20
#define sd_GapAddrSetCmd_size                    14
#define sd_GapAddrSetRsp_size                    6
#define sd_GapAdvAddrGetCmd_size                 3
#define sd_GapAdvAddrGetRsp_size                 20
#define sd_GapAdvSetConfigureCmd_size            595
#define sd_GapAdvSetConfigureRsp_size            9
#define sd_GapAdvStartCmd_size                   6
#define sd_GapAdvStartRsp_size                   6
#define sd_GapAdvStopCmd_size                    3
#define sd_GapAdvStopRsp_size                    6
#define sd_GapAppearanceGetCmd_size              0
#define sd_GapAppearanceGetRsp_size              10
#define sd_GapAppearanceSetCmd_size              4
#define sd_GapAppearanceSetRsp_size              6
#define sd_GapAuthKeyReplyCmd_size               24
#define sd_GapAuthKeyReplyRsp_size               6
#define sd_GapAuthenticateCmd_size               44
#define sd_GapAuthenticateRsp_size               6
#define sd_GapConnEvtTriggerStartCmd_size        23
#define sd_GapConnEvtTriggerStartRsp_size        6
#define sd_GapConnEvtTriggerStopCmd_size         4
#define sd_GapConnEvtTriggerStopRsp_size         6
#define sd_GapConnParamUpdateCmd_size            22
#define sd_GapConnParamUpdateRsp_size            6
#define sd_GapConnSecGetCmd_size                 4
#define sd_GapConnSecGetRsp_size                 19
#define sd_GapConnectCancelCmd_size              0
#define sd_GapConnectCancelRsp_size              6
#define sd_GapConnectCmd_size                    70
#define sd_GapConnectRsp_size                    6
#define sd_GapDataLengthUpdateCmd_size           36
#define sd_GapDataLengthUpdateRsp_size           38
#define sd_GapDeviceIdentitiesSetCmd_size        451
#define sd_GapDeviceIdentitiesSetRsp_size        6
#define sd_GapDeviceNameGetCmd_size              0
#define sd_GapDeviceNameGetRsp_size              261
#define sd_GapDeviceNameSetCmd_size              263
#define sd_GapDeviceNameSetRsp_size              6
#define sd_GapDisconnectCmd_size                 7
#define sd_GapDisconnectRsp_size                 6
#define sd_GapEncryptCmd_size                    47
#define sd_GapEncryptRsp_size                    6
#define sd_GapEvtAdvReport_size                  342
#define sd_GapEvtAdvSetTerminated_size           541
#define sd_GapEvtAuthKeyRequest_size             2
#define sd_GapEvtAuthStatus_size                 50
#define sd_GapEvtConnParamUpdateRequest_size     18
#define sd_GapEvtConnParamUpdate_size            18
#define sd_GapEvtConnSecUpdate_size              13
#define sd_GapEvtConnected_size                  571
#define sd_GapEvtDataLengthUpdateRequest_size    18
#define sd_GapEvtDataLengthUpdate_size           18
#define sd_GapEvtDisconnected_size               3
#define sd_GapEvtKeyPressed_size                 2
#define sd_GapEvtLescDhkeyRequest_size           70
#define sd_GapEvtPasskeyDisplay_size             10
#define sd_GapEvtPhyUpdateRequest_size           6
#define sd_GapEvtPhyUpdate_size                  10
#define sd_GapEvtQosChannelSurveyReport_size     240
#define sd_GapEvtRssiChanged_size                6
#define sd_GapEvtScanReqReport_size              20
#define sd_GapEvtSecInfoRequest_size             39
#define sd_GapEvtSecParamsRequest_size           40
#define sd_GapEvtSecRequest_size                 8
#define sd_GapEvtTimeout_size                    267
#define sd_GapKeypressNotifyCmd_size             6
#define sd_GapKeypressNotifyRsp_size             6
#define sd_GapLescDhkeyReplyCmd_size             40
#define sd_GapLescDhkeyReplyRsp_size             6
#define sd_GapLescOobDataGetCmd_size             72
#define sd_GapLescOobDataGetRsp_size             58
#define sd_GapLescOobDataSetCmd_size             108
#define sd_GapLescOobDataSetRsp_size             6
#define sd_GapNextConnEvtCounterGetCmd_size      4
#define sd_GapNextConnEvtCounterGetRsp_size      10
#define sd_GapPhyUpdateCmd_size                  12
#define sd_GapPhyUpdateRsp_size                  6
#define sd_GapPpcpGetCmd_size                    0
#define sd_GapPpcpGetRsp_size                    24
#define sd_GapPpcpSetCmd_size                    18
#define sd_GapPpcpSetRsp_size                    6
#define sd_GapPrivacyGetCmd_size                 0
#define sd_GapPrivacyGetRsp_size                 36
#define sd_GapPrivacySetCmd_size                 30
#define sd_GapPrivacySetRsp_size                 6
#define sd_GapQosChannelSurveyStartCmd_size      6
#define sd_GapQosChannelSurveyStartRsp_size      6
#define sd_GapQosChannelSurveyStopCmd_size       0
#define sd_GapQosChannelSurveyStopRsp_size       6
#define sd_GapRssiGetCmd_size                    4
#define sd_GapRssiGetRsp_size                    9
#define sd_GapRssiStartCmd_size                  10
#define sd_GapRssiStartRsp_size                  6
#define sd_GapRssiStopCmd_size                   4
#define sd_GapRssiStopRsp_size                   6
#define sd_GapScanStartCmd_size                  35
#define sd_GapScanStartRsp_size                  6
#define sd_GapScanStopCmd_size                   0
#define sd_GapScanStopRsp_size                   6
#define sd_GapSecInfoReplyCmd_size               71
#define sd_GapSecInfoReplyRsp_size               6
#define sd_GapSecParamsReplyCmd_size             394
#define sd_GapSecParamsReplyRsp_size             6
#define sd_GapTxPowerSetCmd_size                 10
#define sd_GapTxPowerSetRsp_size                 6
#define sd_GapWhitelistSetCmd_size               115
#define sd_GapWhitelistSetRsp_size               6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
