/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "protocol/softdevice_types.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(sd_types_BleGapAddr, sd_types_BleGapAddr, AUTO)


PB_BIND(sd_types_BleGapConnParams, sd_types_BleGapConnParams, AUTO)


PB_BIND(sd_types_BleGapConnSecMode, sd_types_BleGapConnSecMode, AUTO)


PB_BIND(sd_types_BleGapIrk, sd_types_BleGapIrk, AUTO)


PB_BIND(sd_types_BleGapChMask, sd_types_BleGapChMask, AUTO)


PB_BIND(sd_types_BleGapAdvProperties, sd_types_BleGapAdvProperties, AUTO)


PB_BIND(sd_types_BleGapAdvParams, sd_types_BleGapAdvParams, AUTO)


PB_BIND(sd_types_BleData, sd_types_BleData, 2)


PB_BIND(sd_types_BleGapAdvData, sd_types_BleGapAdvData, 2)


PB_BIND(sd_types_BleGapScanParams, sd_types_BleGapScanParams, AUTO)


PB_BIND(sd_types_BleGapPrivacyParams, sd_types_BleGapPrivacyParams, AUTO)


PB_BIND(sd_types_BleGapSecKdist, sd_types_BleGapSecKdist, AUTO)


PB_BIND(sd_types_BleGapSecParams, sd_types_BleGapSecParams, AUTO)


PB_BIND(sd_types_BleGapEncInfo, sd_types_BleGapEncInfo, AUTO)


PB_BIND(sd_types_BleGapMasterId, sd_types_BleGapMasterId, AUTO)


PB_BIND(sd_types_BleGapSignInfo, sd_types_BleGapSignInfo, AUTO)


PB_BIND(sd_types_BleGapLescP256Pk, sd_types_BleGapLescP256Pk, AUTO)


PB_BIND(sd_types_BleGapLescDhkey, sd_types_BleGapLescDhkey, AUTO)


PB_BIND(sd_types_BleGapLescOobData, sd_types_BleGapLescOobData, AUTO)


PB_BIND(sd_types_BleGapConnSec, sd_types_BleGapConnSec, AUTO)


PB_BIND(sd_types_BleGapEncKey, sd_types_BleGapEncKey, AUTO)


PB_BIND(sd_types_BleGapIdKey, sd_types_BleGapIdKey, AUTO)


PB_BIND(sd_types_BleGapSecKeys, sd_types_BleGapSecKeys, AUTO)


PB_BIND(sd_types_BleGapSecKeyset, sd_types_BleGapSecKeyset, 2)


PB_BIND(sd_types_BleGapDataLengthParams, sd_types_BleGapDataLengthParams, AUTO)


PB_BIND(sd_types_BleGapDataLengthLimitation, sd_types_BleGapDataLengthLimitation, AUTO)


PB_BIND(sd_types_BleGapConnEventTrigger, sd_types_BleGapConnEventTrigger, AUTO)


PB_BIND(sd_types_BleUuid, sd_types_BleUuid, AUTO)


PB_BIND(sd_types_BleUuid128, sd_types_BleUuid128, AUTO)


PB_BIND(sd_types_BleGattCharProps, sd_types_BleGattCharProps, AUTO)


PB_BIND(sd_types_BleGattcHandleRange, sd_types_BleGattcHandleRange, AUTO)


PB_BIND(sd_types_BleGattcWriteParams, sd_types_BleGattcWriteParams, 2)


PB_BIND(sd_types_BleGattcService, sd_types_BleGattcService, AUTO)


PB_BIND(sd_types_BleGattcInclude, sd_types_BleGattcInclude, AUTO)


PB_BIND(sd_types_BleGattcChar, sd_types_BleGattcChar, AUTO)


PB_BIND(sd_types_BleGattcDesc, sd_types_BleGattcDesc, AUTO)


PB_BIND(sd_types_BleGattcAttrInfo16, sd_types_BleGattcAttrInfo16, AUTO)


PB_BIND(sd_types_BleGattcAttrInfo128, sd_types_BleGattcAttrInfo128, AUTO)


PB_BIND(sd_types_BleGattcHandleValue, sd_types_BleGattcHandleValue, 2)


PB_BIND(sd_types_BleGattsAttrMd, sd_types_BleGattsAttrMd, AUTO)


PB_BIND(sd_types_BleGattsAttr, sd_types_BleGattsAttr, 2)


PB_BIND(sd_types_BleGattsValue, sd_types_BleGattsValue, 2)


PB_BIND(sd_types_BleGattsCharPf, sd_types_BleGattsCharPf, AUTO)


PB_BIND(sd_types_BleGattCharExtProps, sd_types_BleGattCharExtProps, AUTO)


PB_BIND(sd_types_BleGattsCharMd, sd_types_BleGattsCharMd, 2)


PB_BIND(sd_types_BleGattsCharHandles, sd_types_BleGattsCharHandles, AUTO)


PB_BIND(sd_types_BleGattsHvxParams, sd_types_BleGattsHvxParams, 2)


PB_BIND(sd_types_BleGapSecLevelsT, sd_types_BleGapSecLevelsT, AUTO)


PB_BIND(sd_types_BleGapAdvReportTypeT, sd_types_BleGapAdvReportTypeT, AUTO)


PB_BIND(sd_types_BleGapAuxPointer, sd_types_BleGapAuxPointer, AUTO)


PB_BIND(sd_types_BleGattsAuthorizeParams, sd_types_BleGattsAuthorizeParams, 2)


PB_BIND(sd_types_BleGattsRwAuthorizeReplyParams, sd_types_BleGattsRwAuthorizeReplyParams, 2)













































