/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "protocol/softdevice_gatts.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(sd_GattsServiceAddCmd, sd_GattsServiceAddCmd, AUTO)


PB_BIND(sd_GattsIncludeAddCmd, sd_GattsIncludeAddCmd, AUTO)


PB_BIND(sd_GattsCharacteristicAddCmd, sd_GattsCharacteristicAddCmd, 2)


PB_BIND(sd_GattsDescriptorAddCmd, sd_GattsDescriptorAddCmd, 2)


PB_BIND(sd_GattsValueSetCmd, sd_GattsValueSetCmd, 2)


PB_BIND(sd_GattsValueGetCmd, sd_GattsValueGetCmd, 2)


PB_BIND(sd_GattsHvxCmd, sd_GattsHvxCmd, 2)


PB_BIND(sd_GattsServiceChangedCmd, sd_GattsServiceChangedCmd, AUTO)


PB_BIND(sd_GattsRwAuthorizeReplyCmd, sd_GattsRwAuthorizeReplyCmd, 2)


PB_BIND(sd_GattsSysAttrSetCmd, sd_GattsSysAttrSetCmd, 2)


PB_BIND(sd_GattsSysAttrGetCmd, sd_GattsSysAttrGetCmd, 2)


PB_BIND(sd_GattsInitialUserHandleGetCmd, sd_GattsInitialUserHandleGetCmd, AUTO)


PB_BIND(sd_GattsAttrGetCmd, sd_GattsAttrGetCmd, AUTO)


PB_BIND(sd_GattsExchangeMtuReplyCmd, sd_GattsExchangeMtuReplyCmd, AUTO)


PB_BIND(sd_GattsServiceAddRsp, sd_GattsServiceAddRsp, AUTO)


PB_BIND(sd_GattsIncludeAddRsp, sd_GattsIncludeAddRsp, AUTO)


PB_BIND(sd_GattsCharacteristicAddRsp, sd_GattsCharacteristicAddRsp, AUTO)


PB_BIND(sd_GattsDescriptorAddRsp, sd_GattsDescriptorAddRsp, AUTO)


PB_BIND(sd_GattsValueSetRsp, sd_GattsValueSetRsp, AUTO)


PB_BIND(sd_GattsValueGetRsp, sd_GattsValueGetRsp, 2)


PB_BIND(sd_GattsHvxRsp, sd_GattsHvxRsp, 2)


PB_BIND(sd_GattsServiceChangedRsp, sd_GattsServiceChangedRsp, AUTO)


PB_BIND(sd_GattsRwAuthorizeReplyRsp, sd_GattsRwAuthorizeReplyRsp, AUTO)


PB_BIND(sd_GattsSysAttrSetRsp, sd_GattsSysAttrSetRsp, AUTO)


PB_BIND(sd_GattsSysAttrGetRsp, sd_GattsSysAttrGetRsp, 2)


PB_BIND(sd_GattsInitialUserHandleGetRsp, sd_GattsInitialUserHandleGetRsp, AUTO)


PB_BIND(sd_GattsAttrGetRsp, sd_GattsAttrGetRsp, AUTO)


PB_BIND(sd_GattsExchangeMtuReplyRsp, sd_GattsExchangeMtuReplyRsp, AUTO)


PB_BIND(sd_GattsEvtWrite, sd_GattsEvtWrite, 2)


PB_BIND(sd_GattsEvtRead, sd_GattsEvtRead, AUTO)


PB_BIND(sd_GattsEvtRwAuthorizeRequest, sd_GattsEvtRwAuthorizeRequest, 2)


PB_BIND(sd_GattsEvtSysAttrMissing, sd_GattsEvtSysAttrMissing, AUTO)


PB_BIND(sd_GattsEvtHvc, sd_GattsEvtHvc, AUTO)


PB_BIND(sd_GattsEvtExchangeMtuRequest, sd_GattsEvtExchangeMtuRequest, AUTO)


PB_BIND(sd_GattsEvtTimeout, sd_GattsEvtTimeout, AUTO)


PB_BIND(sd_GattsEvtHvnTxComplete, sd_GattsEvtHvnTxComplete, AUTO)



