/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SD_TYPES_SOFTDEVICE_TYPES_PB_H_INCLUDED
#define PB_SD_TYPES_SOFTDEVICE_TYPES_PB_H_INCLUDED
#include "nanopb/pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Enums for GAP constants */
typedef enum _sd_types_BleGapAddrType {
    sd_types_BleGapAddrType_BLE_GAP_ADDR_TYPE_PUBLIC = 0,
    sd_types_BleGapAddrType_BLE_GAP_ADDR_TYPE_RANDOM_STATIC = 1,
    sd_types_BleGapAddrType_BLE_GAP_ADDR_TYPE_RANDOM_PRIVATE_RESOLVABLE = 2,
    sd_types_BleGapAddrType_BLE_GAP_ADDR_TYPE_RANDOM_PRIVATE_NON_RESOLVABLE = 3,
    sd_types_BleGapAddrType_BLE_GAP_ADDR_TYPE_ANONYMOUS = 127
} sd_types_BleGapAddrType;

typedef enum _sd_types_BleGapPrivacyMode {
    sd_types_BleGapPrivacyMode_BLE_GAP_PRIVACY_MODE_OFF = 0,
    sd_types_BleGapPrivacyMode_BLE_GAP_PRIVACY_MODE_DEVICE_PRIVACY = 1,
    sd_types_BleGapPrivacyMode_BLE_GAP_PRIVACY_MODE_NETWORK_PRIVACY = 2
} sd_types_BleGapPrivacyMode;

typedef enum _sd_types_BleGapAdvType {
    sd_types_BleGapAdvType_BLE_GAP_ADV_TYPE_UNKNOWN = 0,
    sd_types_BleGapAdvType_BLE_GAP_ADV_TYPE_CONNECTABLE_SCANNABLE_UNDIRECTED = 1,
    sd_types_BleGapAdvType_BLE_GAP_ADV_TYPE_CONNECTABLE_NONSCANNABLE_DIRECTED_HIGH_DUTY_CYCLE = 2,
    sd_types_BleGapAdvType_BLE_GAP_ADV_TYPE_CONNECTABLE_NONSCANNABLE_DIRECTED = 3,
    sd_types_BleGapAdvType_BLE_GAP_ADV_TYPE_NONCONNECTABLE_SCANNABLE_UNDIRECTED = 4,
    sd_types_BleGapAdvType_BLE_GAP_ADV_TYPE_NONCONNECTABLE_NONSCANNABLE_UNDIRECTED = 5,
    sd_types_BleGapAdvType_BLE_GAP_ADV_TYPE_EXTENDED_CONNECTABLE_NONSCANNABLE_UNDIRECTED = 6,
    sd_types_BleGapAdvType_BLE_GAP_ADV_TYPE_EXTENDED_CONNECTABLE_NONSCANNABLE_DIRECTED = 7,
    sd_types_BleGapAdvType_BLE_GAP_ADV_TYPE_EXTENDED_NONCONNECTABLE_SCANNABLE_UNDIRECTED = 8,
    sd_types_BleGapAdvType_BLE_GAP_ADV_TYPE_EXTENDED_NONCONNECTABLE_SCANNABLE_DIRECTED = 9,
    sd_types_BleGapAdvType_BLE_GAP_ADV_TYPE_EXTENDED_NONCONNECTABLE_NONSCANNABLE_UNDIRECTED = 10,
    sd_types_BleGapAdvType_BLE_GAP_ADV_TYPE_EXTENDED_NONCONNECTABLE_NONSCANNABLE_DIRECTED = 11
} sd_types_BleGapAdvType;

typedef enum _sd_types_BleGapAdvFilterPolicy {
    sd_types_BleGapAdvFilterPolicy_BLE_GAP_ADV_FP_ANY = 0,
    sd_types_BleGapAdvFilterPolicy_BLE_GAP_ADV_FP_FILTER_SCANREQ = 1,
    sd_types_BleGapAdvFilterPolicy_BLE_GAP_ADV_FP_FILTER_CONNREQ = 2,
    sd_types_BleGapAdvFilterPolicy_BLE_GAP_ADV_FP_FILTER_BOTH = 3
} sd_types_BleGapAdvFilterPolicy;

typedef enum _sd_types_BleGapPhy {
    sd_types_BleGapPhy_BLE_GAP_PHY_AUTO = 0,
    sd_types_BleGapPhy_BLE_GAP_PHY_1MBPS = 1,
    sd_types_BleGapPhy_BLE_GAP_PHY_2MBPS = 2,
    sd_types_BleGapPhy_BLE_GAP_PHY_CODED = 4,
    sd_types_BleGapPhy_BLE_GAP_PHY_NOT_SET = 255
} sd_types_BleGapPhy;

typedef enum _sd_types_BleGapIoCaps {
    sd_types_BleGapIoCaps_BLE_GAP_IO_CAPS_DISPLAY_ONLY = 0,
    sd_types_BleGapIoCaps_BLE_GAP_IO_CAPS_DISPLAY_YESNO = 1,
    sd_types_BleGapIoCaps_BLE_GAP_IO_CAPS_KEYBOARD_ONLY = 2,
    sd_types_BleGapIoCaps_BLE_GAP_IO_CAPS_NONE = 3,
    sd_types_BleGapIoCaps_BLE_GAP_IO_CAPS_KEYBOARD_DISPLAY = 4
} sd_types_BleGapIoCaps;

typedef enum _sd_types_BleGapAuthKeyType {
    sd_types_BleGapAuthKeyType_BLE_GAP_AUTH_KEY_TYPE_NONE = 0,
    sd_types_BleGapAuthKeyType_BLE_GAP_AUTH_KEY_TYPE_PASSKEY = 1,
    sd_types_BleGapAuthKeyType_BLE_GAP_AUTH_KEY_TYPE_OOB = 2
} sd_types_BleGapAuthKeyType;

typedef enum _sd_types_BleGapKpNotType {
    sd_types_BleGapKpNotType_BLE_GAP_KP_NOT_TYPE_PASSKEY_START = 0,
    sd_types_BleGapKpNotType_BLE_GAP_KP_NOT_TYPE_PASSKEY_DIGIT_IN = 1,
    sd_types_BleGapKpNotType_BLE_GAP_KP_NOT_TYPE_PASSKEY_DIGIT_OUT = 2,
    sd_types_BleGapKpNotType_BLE_GAP_KP_NOT_TYPE_PASSKEY_CLEAR = 3,
    sd_types_BleGapKpNotType_BLE_GAP_KP_NOT_TYPE_PASSKEY_END = 4
} sd_types_BleGapKpNotType;

typedef enum _sd_types_BleGapTimeoutSrc {
    sd_types_BleGapTimeoutSrc_BLE_GAP_TIMEOUT_SRC_INVALID = 0,
    sd_types_BleGapTimeoutSrc_BLE_GAP_TIMEOUT_SRC_SCAN = 1,
    sd_types_BleGapTimeoutSrc_BLE_GAP_TIMEOUT_SRC_CONN = 2,
    sd_types_BleGapTimeoutSrc_BLE_GAP_TIMEOUT_SRC_AUTH_PAYLOAD = 3
} sd_types_BleGapTimeoutSrc;

typedef enum _sd_types_BleGapAdvReportType {
    sd_types_BleGapAdvReportType_BLE_GAP_ADV_DATA_STATUS_COMPLETE = 0,
    sd_types_BleGapAdvReportType_BLE_GAP_ADV_DATA_STATUS_INCOMPLETE_MORE_DATA = 1,
    sd_types_BleGapAdvReportType_BLE_GAP_ADV_DATA_STATUS_INCOMPLETE_TRUNCATED = 2,
    sd_types_BleGapAdvReportType_BLE_GAP_ADV_DATA_STATUS_INCOMPLETE_MISSED = 3
} sd_types_BleGapAdvReportType;

typedef enum _sd_types_BleGapAdvSetTerminatedReason {
    sd_types_BleGapAdvSetTerminatedReason_BLE_GAP_EVT_ADV_SET_TERMINATED_REASON_INVALID = 0,
    sd_types_BleGapAdvSetTerminatedReason_BLE_GAP_EVT_ADV_SET_TERMINATED_REASON_TIMEOUT = 1,
    sd_types_BleGapAdvSetTerminatedReason_BLE_GAP_EVT_ADV_SET_TERMINATED_REASON_LIMIT_REACHED = 2
} sd_types_BleGapAdvSetTerminatedReason;

typedef enum _sd_types_BleGapSecLevels {
    sd_types_BleGapSecLevels_BLE_GAP_SEC_LEVEL_INVALID = 0,
    sd_types_BleGapSecLevels_BLE_GAP_SEC_LEVEL_1 = 1,
    sd_types_BleGapSecLevels_BLE_GAP_SEC_LEVEL_2 = 2,
    sd_types_BleGapSecLevels_BLE_GAP_SEC_LEVEL_3 = 3,
    sd_types_BleGapSecLevels_BLE_GAP_SEC_LEVEL_4 = 4
} sd_types_BleGapSecLevels;

/* GATT Timeout Sources */
typedef enum _sd_types_BleGattTimeoutSrc {
    sd_types_BleGattTimeoutSrc_BLE_GATT_TIMEOUT_SRC_PROTOCOL = 0
} sd_types_BleGattTimeoutSrc;

/* GATT Write Operations */
typedef enum _sd_types_BleGattWriteOp {
    sd_types_BleGattWriteOp_BLE_GATT_OP_INVALID = 0,
    sd_types_BleGattWriteOp_BLE_GATT_OP_WRITE_REQ = 1,
    sd_types_BleGattWriteOp_BLE_GATT_OP_WRITE_CMD = 2,
    sd_types_BleGattWriteOp_BLE_GATT_OP_SIGN_WRITE_CMD = 3,
    sd_types_BleGattWriteOp_BLE_GATT_OP_PREP_WRITE_REQ = 4,
    sd_types_BleGattWriteOp_BLE_GATT_OP_EXEC_WRITE_REQ_CANCEL = 5,
    sd_types_BleGattWriteOp_BLE_GATT_OP_EXEC_WRITE_REQ_NOW = 6
} sd_types_BleGattWriteOp;

/* GATT Execute Write Flags */
typedef enum _sd_types_BleGattExecWriteFlag {
    sd_types_BleGattExecWriteFlag_BLE_GATT_EXEC_WRITE_FLAG_PREPARED_CANCEL = 0,
    sd_types_BleGattExecWriteFlag_BLE_GATT_EXEC_WRITE_FLAG_PREPARED_WRITE = 1
} sd_types_BleGattExecWriteFlag;

/* GATT HVx Types */
typedef enum _sd_types_BleGattHvxType {
    sd_types_BleGattHvxType_BLE_GATT_HVX_INVALID = 0,
    sd_types_BleGattHvxType_BLE_GATT_HVX_NOTIFICATION = 1,
    sd_types_BleGattHvxType_BLE_GATT_HVX_INDICATION = 2
} sd_types_BleGattHvxType;

/* GATTC Attribute Information Formats */
typedef enum _sd_types_BleGattcAttrInfoFormat {
    sd_types_BleGattcAttrInfoFormat_BLE_GATTC_ATTR_INFO_FORMAT_INVALID = 0,
    sd_types_BleGattcAttrInfoFormat_BLE_GATTC_ATTR_INFO_FORMAT_16BIT = 1,
    sd_types_BleGattcAttrInfoFormat_BLE_GATTC_ATTR_INFO_FORMAT_128BIT = 2
} sd_types_BleGattcAttrInfoFormat;

/* GATTS Operations */
typedef enum _sd_types_BleGattsOp {
    sd_types_BleGattsOp_BLE_GATTS_OP_INVALID = 0,
    sd_types_BleGattsOp_BLE_GATTS_OP_WRITE_REQ = 1,
    sd_types_BleGattsOp_BLE_GATTS_OP_WRITE_CMD = 2,
    sd_types_BleGattsOp_BLE_GATTS_OP_SIGN_WRITE_CMD = 3,
    sd_types_BleGattsOp_BLE_GATTS_OP_PREP_WRITE_REQ = 4,
    sd_types_BleGattsOp_BLE_GATTS_OP_EXEC_WRITE_REQ_CANCEL = 5,
    sd_types_BleGattsOp_BLE_GATTS_OP_EXEC_WRITE_REQ_NOW = 6
} sd_types_BleGattsOp;

/* GATTS Authorize Types */
typedef enum _sd_types_BleGattsAuthorizeType {
    sd_types_BleGattsAuthorizeType_BLE_GATTS_AUTHORIZE_TYPE_INVALID = 0,
    sd_types_BleGattsAuthorizeType_BLE_GATTS_AUTHORIZE_TYPE_READ = 1,
    sd_types_BleGattsAuthorizeType_BLE_GATTS_AUTHORIZE_TYPE_WRITE = 2
} sd_types_BleGattsAuthorizeType;

/* GATTS Value Locations */
typedef enum _sd_types_BleGattsVloc {
    sd_types_BleGattsVloc_BLE_GATTS_VLOC_INVALID = 0,
    sd_types_BleGattsVloc_BLE_GATTS_VLOC_STACK = 1,
    sd_types_BleGattsVloc_BLE_GATTS_VLOC_USER = 2
} sd_types_BleGattsVloc;

typedef enum _sd_types_BleGapSecStatus {
    sd_types_BleGapSecStatus_BLE_GAP_SEC_STATUS_SUCCESS = 0,
    sd_types_BleGapSecStatus_BLE_GAP_SEC_STATUS_TIMEOUT = 1,
    sd_types_BleGapSecStatus_BLE_GAP_SEC_STATUS_PDU_INVALID = 2,
    sd_types_BleGapSecStatus_BLE_GAP_SEC_STATUS_PASSKEY_ENTRY_FAILED = 129,
    sd_types_BleGapSecStatus_BLE_GAP_SEC_STATUS_OOB_NOT_AVAILABLE = 130,
    sd_types_BleGapSecStatus_BLE_GAP_SEC_STATUS_AUTH_REQ = 131,
    sd_types_BleGapSecStatus_BLE_GAP_SEC_STATUS_CONFIRM_VALUE = 132,
    sd_types_BleGapSecStatus_BLE_GAP_SEC_STATUS_PAIRING_NOT_SUPP = 133,
    sd_types_BleGapSecStatus_BLE_GAP_SEC_STATUS_ENC_KEY_SIZE = 134,
    sd_types_BleGapSecStatus_BLE_GAP_SEC_STATUS_SMP_CMD_UNSUPPORTED = 135,
    sd_types_BleGapSecStatus_BLE_GAP_SEC_STATUS_UNSPECIFIED = 136,
    sd_types_BleGapSecStatus_BLE_GAP_SEC_STATUS_REPEATED_ATTEMPTS = 137,
    sd_types_BleGapSecStatus_BLE_GAP_SEC_STATUS_INVALID_PARAMS = 138,
    sd_types_BleGapSecStatus_BLE_GAP_SEC_STATUS_DHKEY_FAILURE = 139,
    sd_types_BleGapSecStatus_BLE_GAP_SEC_STATUS_NUM_COMP_FAILURE = 140,
    sd_types_BleGapSecStatus_BLE_GAP_SEC_STATUS_BR_EDR_IN_PROG = 141,
    sd_types_BleGapSecStatus_BLE_GAP_SEC_STATUS_X_TRANS_KEY_DISALLOWED = 142
} sd_types_BleGapSecStatus;

/* Struct definitions */
/* GAP address structure */
typedef struct _sd_types_BleGapAddr {
    bool addr_id_peer;
    sd_types_BleGapAddrType addr_type;
    pb_byte_t addr[6]; /* BLE_GAP_ADDR_LEN = 6 */
} sd_types_BleGapAddr;

/* GAP connection parameters */
typedef struct _sd_types_BleGapConnParams {
    uint16_t min_conn_interval;
    uint16_t max_conn_interval;
    uint16_t slave_latency;
    uint16_t conn_sup_timeout;
} sd_types_BleGapConnParams;

/* GAP connection security mode */
typedef struct _sd_types_BleGapConnSecMode {
    uint8_t sm; /* 4-bit field */
    uint8_t lv; /* 4-bit field */
} sd_types_BleGapConnSecMode;

/* GAP identity resolving key */
typedef struct _sd_types_BleGapIrk {
    pb_byte_t irk[16]; /* BLE_GAP_SEC_KEY_LEN = 16 */
} sd_types_BleGapIrk;

/* GAP channel mask */
typedef struct _sd_types_BleGapChMask {
    pb_byte_t ch_mask[5]; /* 5 bytes */
} sd_types_BleGapChMask;

/* Advertising properties */
typedef struct _sd_types_BleGapAdvProperties {
    sd_types_BleGapAdvType type;
    bool anonymous;
    bool include_tx_power;
} sd_types_BleGapAdvProperties;

/* Advertising parameters */
typedef struct _sd_types_BleGapAdvParams {
    bool has_properties;
    sd_types_BleGapAdvProperties properties;
    bool has_peer_addr;
    sd_types_BleGapAddr peer_addr; /* Optional */
    uint32_t interval;
    uint16_t duration;
    uint8_t max_adv_evts;
    bool has_channel_mask;
    sd_types_BleGapChMask channel_mask;
    sd_types_BleGapAdvFilterPolicy filter_policy;
    sd_types_BleGapPhy primary_phy;
    sd_types_BleGapPhy secondary_phy;
    uint8_t set_id; /* 4-bit field */
    bool scan_req_notification;
} sd_types_BleGapAdvParams;

typedef PB_BYTES_ARRAY_T(255) sd_types_BleData_data_t;
/* Data buffer */
typedef struct _sd_types_BleData {
    sd_types_BleData_data_t data; /* Max for extended advertising */
    uint16_t len;
} sd_types_BleData;

/* Advertising data */
typedef struct _sd_types_BleGapAdvData {
    bool has_adv_data;
    sd_types_BleData adv_data; /* Optional */
    bool has_scan_rsp_data;
    sd_types_BleData scan_rsp_data; /* Optional */
} sd_types_BleGapAdvData;

/* Scan parameters */
typedef struct _sd_types_BleGapScanParams {
    bool extended;
    bool report_incomplete_evts;
    bool active;
    uint8_t filter_policy; /* 2-bit field */
    sd_types_BleGapPhy scan_phys;
    uint16_t interval;
    uint16_t window;
    uint16_t timeout;
    bool has_channel_mask;
    sd_types_BleGapChMask channel_mask;
} sd_types_BleGapScanParams;

/* Privacy parameters */
typedef struct _sd_types_BleGapPrivacyParams {
    sd_types_BleGapPrivacyMode privacy_mode;
    sd_types_BleGapAddrType private_addr_type;
    uint16_t private_addr_cycle_s;
    bool has_device_irk;
    sd_types_BleGapIrk device_irk; /* Optional */
} sd_types_BleGapPrivacyParams;

/* Security key distribution */
typedef struct _sd_types_BleGapSecKdist {
    bool enc;
    bool id;
    bool sign;
    bool link;
} sd_types_BleGapSecKdist;

/* Security parameters */
typedef struct _sd_types_BleGapSecParams {
    bool bond;
    bool mitm;
    bool lesc;
    bool keypress;
    sd_types_BleGapIoCaps io_caps;
    bool oob;
    uint8_t min_key_size;
    uint8_t max_key_size;
    bool has_kdist_own;
    sd_types_BleGapSecKdist kdist_own;
    bool has_kdist_peer;
    sd_types_BleGapSecKdist kdist_peer;
} sd_types_BleGapSecParams;

/* Encryption information */
typedef struct _sd_types_BleGapEncInfo {
    pb_byte_t ltk[16]; /* BLE_GAP_SEC_KEY_LEN = 16 */
    bool lesc;
    bool auth;
    uint8_t ltk_len; /* 6-bit field */
} sd_types_BleGapEncInfo;

/* Master identification */
typedef struct _sd_types_BleGapMasterId {
    uint16_t ediv;
    pb_byte_t rand[8]; /* BLE_GAP_SEC_RAND_LEN = 8 */
} sd_types_BleGapMasterId;

/* Signing information */
typedef struct _sd_types_BleGapSignInfo {
    pb_byte_t csrk[16]; /* BLE_GAP_SEC_KEY_LEN = 16 */
} sd_types_BleGapSignInfo;

/* LE Secure Connections public key */
typedef struct _sd_types_BleGapLescP256Pk {
    pb_byte_t pk[64]; /* BLE_GAP_LESC_P256_PK_LEN = 64 */
} sd_types_BleGapLescP256Pk;

/* LE Secure Connections DHKey */
typedef struct _sd_types_BleGapLescDhkey {
    pb_byte_t key[32]; /* BLE_GAP_LESC_DHKEY_LEN = 32 */
} sd_types_BleGapLescDhkey;

/* LE Secure Connections OOB data */
typedef struct _sd_types_BleGapLescOobData {
    bool has_addr;
    sd_types_BleGapAddr addr;
    pb_byte_t r[16]; /* BLE_GAP_SEC_KEY_LEN = 16 */
    pb_byte_t c[16]; /* BLE_GAP_SEC_KEY_LEN = 16 */
} sd_types_BleGapLescOobData;

/* Connection security */
typedef struct _sd_types_BleGapConnSec {
    bool has_sec_mode;
    sd_types_BleGapConnSecMode sec_mode;
    uint8_t encr_key_size;
} sd_types_BleGapConnSec;

/* Encryption key */
typedef struct _sd_types_BleGapEncKey {
    bool has_enc_info;
    sd_types_BleGapEncInfo enc_info;
    bool has_master_id;
    sd_types_BleGapMasterId master_id;
} sd_types_BleGapEncKey;

/* Identity key */
typedef struct _sd_types_BleGapIdKey {
    bool has_id_info;
    sd_types_BleGapIrk id_info;
    bool has_id_addr_info;
    sd_types_BleGapAddr id_addr_info;
} sd_types_BleGapIdKey;

/* Security keys */
typedef struct _sd_types_BleGapSecKeys {
    bool has_enc_key;
    sd_types_BleGapEncKey enc_key; /* Optional */
    bool has_id_key;
    sd_types_BleGapIdKey id_key; /* Optional */
    bool has_sign_key;
    sd_types_BleGapSignInfo sign_key; /* Optional */
    bool has_pk;
    sd_types_BleGapLescP256Pk pk; /* Optional */
} sd_types_BleGapSecKeys;

/* Security keyset */
typedef struct _sd_types_BleGapSecKeyset {
    bool has_keys_own;
    sd_types_BleGapSecKeys keys_own;
    bool has_keys_peer;
    sd_types_BleGapSecKeys keys_peer;
} sd_types_BleGapSecKeyset;

/* Data length parameters */
typedef struct _sd_types_BleGapDataLengthParams {
    uint16_t max_tx_octets;
    uint16_t max_rx_octets;
    uint16_t max_tx_time_us;
    uint16_t max_rx_time_us;
} sd_types_BleGapDataLengthParams;

/* Data length limitation */
typedef struct _sd_types_BleGapDataLengthLimitation {
    uint16_t tx_payload_limited_octets;
    uint16_t rx_payload_limited_octets;
    uint16_t tx_rx_time_limited_us;
} sd_types_BleGapDataLengthLimitation;

/* Connection event trigger parameters */
typedef struct _sd_types_BleGapConnEventTrigger {
    uint8_t ppi_ch_id;
    uint32_t task_endpoint;
    uint16_t conn_evt_counter_start;
    uint16_t period_in_events;
} sd_types_BleGapConnEventTrigger;

/* UUID types */
typedef struct _sd_types_BleUuid {
    uint16_t uuid; /* 16-bit UUID value or octets 12-13 of 128-bit UUID */
    uint8_t type; /* UUID type */
} sd_types_BleUuid;

typedef struct _sd_types_BleUuid128 {
    pb_byte_t uuid128[16]; /* 16 bytes, little-endian */
} sd_types_BleUuid128;

/* GATT Characteristic Properties */
typedef struct _sd_types_BleGattCharProps {
    bool broadcast;
    bool read;
    bool write_wo_resp;
    bool write;
    bool notify;
    bool indicate;
    bool auth_signed_wr;
} sd_types_BleGattCharProps;

/* GATTC Handle Range */
typedef struct _sd_types_BleGattcHandleRange {
    uint16_t start_handle;
    uint16_t end_handle;
} sd_types_BleGattcHandleRange;

typedef PB_BYTES_ARRAY_T(512) sd_types_BleGattcWriteParams_p_value_t;
/* GATTC Write Parameters */
typedef struct _sd_types_BleGattcWriteParams {
    uint8_t write_op; /* BLE_GATT_WRITE_OPS */
    uint8_t flags; /* BLE_GATT_EXEC_WRITE_FLAGS */
    uint16_t handle;
    uint16_t offset;
    uint16_t len;
    sd_types_BleGattcWriteParams_p_value_t p_value; /* Max ATT MTU size */
} sd_types_BleGattcWriteParams;

/* GATTC Service */
typedef struct _sd_types_BleGattcService {
    bool has_uuid;
    sd_types_BleUuid uuid;
    bool has_handle_range;
    sd_types_BleGattcHandleRange handle_range;
} sd_types_BleGattcService;

/* GATTC Include */
typedef struct _sd_types_BleGattcInclude {
    uint16_t handle;
    bool has_included_srvc;
    sd_types_BleGattcService included_srvc;
} sd_types_BleGattcInclude;

/* GATTC Characteristic */
typedef struct _sd_types_BleGattcChar {
    bool has_uuid;
    sd_types_BleUuid uuid;
    bool has_char_props;
    sd_types_BleGattCharProps char_props;
    uint8_t char_ext_props; /* 1-bit field */
    uint16_t handle_decl;
    uint16_t handle_value;
} sd_types_BleGattcChar;

/* GATTC Descriptor */
typedef struct _sd_types_BleGattcDesc {
    uint16_t handle;
    bool has_uuid;
    sd_types_BleUuid uuid;
} sd_types_BleGattcDesc;

/* GATTC Attribute Information (16-bit) */
typedef struct _sd_types_BleGattcAttrInfo16 {
    uint16_t handle;
    bool has_uuid;
    sd_types_BleUuid uuid;
} sd_types_BleGattcAttrInfo16;

/* GATTC Attribute Information (128-bit) */
typedef struct _sd_types_BleGattcAttrInfo128 {
    uint16_t handle;
    bool has_uuid;
    sd_types_BleUuid128 uuid;
} sd_types_BleGattcAttrInfo128;

typedef PB_BYTES_ARRAY_T(512) sd_types_BleGattcHandleValue_p_value_t;
/* GATTC Handle-Value Pair */
typedef struct _sd_types_BleGattcHandleValue {
    uint16_t handle;
    sd_types_BleGattcHandleValue_p_value_t p_value; /* Max ATT MTU size */
} sd_types_BleGattcHandleValue;

/* GATTS Attribute Metadata */
typedef struct _sd_types_BleGattsAttrMd {
    bool has_read_perm;
    sd_types_BleGapConnSecMode read_perm;
    bool has_write_perm;
    sd_types_BleGapConnSecMode write_perm;
    bool vlen; /* 1-bit field */
    sd_types_BleGattsVloc vloc; /* 2-bit field */
    bool rd_auth; /* 1-bit field */
    bool wr_auth; /* 1-bit field */
} sd_types_BleGattsAttrMd;

typedef PB_BYTES_ARRAY_T(512) sd_types_BleGattsAttr_p_value_t;
/* GATTS Attribute */
typedef struct _sd_types_BleGattsAttr {
    bool has_uuid;
    sd_types_BleUuid uuid; /* Optional */
    bool has_attr_md;
    sd_types_BleGattsAttrMd attr_md; /* Optional */
    uint16_t init_len;
    uint16_t init_offs;
    uint16_t max_len;
    sd_types_BleGattsAttr_p_value_t p_value; /* Max attribute value size */
} sd_types_BleGattsAttr;

typedef PB_BYTES_ARRAY_T(512) sd_types_BleGattsValue_p_value_t;
/* GATTS Attribute Value */
typedef struct _sd_types_BleGattsValue {
    uint16_t len;
    uint16_t offset;
    sd_types_BleGattsValue_p_value_t p_value; /* Optional */
} sd_types_BleGattsValue;

/* GATTS Characteristic Presentation Format */
typedef struct _sd_types_BleGattsCharPf {
    uint8_t format; /* BLE_GATT_CPF_FORMATS */
    int8_t exponent;
    uint16_t unit;
    uint8_t name_space; /* BLE_GATT_CPF_NAMESPACES */
    uint16_t desc;
} sd_types_BleGattsCharPf;

/* GATTS Characteristic Extended Properties */
typedef struct _sd_types_BleGattCharExtProps {
    bool reliable_wr;
    bool wr_aux;
} sd_types_BleGattCharExtProps;

typedef PB_BYTES_ARRAY_T(512) sd_types_BleGattsCharMd_p_char_user_desc_t;
/* GATTS Characteristic Metadata */
typedef struct _sd_types_BleGattsCharMd {
    bool has_char_props;
    sd_types_BleGattCharProps char_props;
    bool has_char_ext_props;
    sd_types_BleGattCharExtProps char_ext_props;
    sd_types_BleGattsCharMd_p_char_user_desc_t p_char_user_desc; /* UTF-8 string */
    uint16_t char_user_desc_max_size;
    uint16_t char_user_desc_size;
    bool has_char_pf;
    sd_types_BleGattsCharPf char_pf; /* Optional */
    bool has_user_desc_md;
    sd_types_BleGattsAttrMd user_desc_md; /* Optional */
    bool has_cccd_md;
    sd_types_BleGattsAttrMd cccd_md; /* Optional */
    bool has_sccd_md;
    sd_types_BleGattsAttrMd sccd_md; /* Optional */
} sd_types_BleGattsCharMd;

/* GATTS Characteristic Handles */
typedef struct _sd_types_BleGattsCharHandles {
    uint16_t value_handle;
    uint16_t user_desc_handle;
    uint16_t cccd_handle;
    uint16_t sccd_handle;
} sd_types_BleGattsCharHandles;

typedef PB_BYTES_ARRAY_T(512) sd_types_BleGattsHvxParams_p_data_t;
/* GATTS HVx Parameters */
typedef struct _sd_types_BleGattsHvxParams {
    uint16_t handle;
    uint8_t type; /* BLE_GATT_HVX_TYPES */
    uint16_t offset;
    uint16_t len; /* Output */
    sd_types_BleGattsHvxParams_p_data_t p_data; /* Optional */
} sd_types_BleGattsHvxParams;

/* GAP Security Levels */
typedef struct _sd_types_BleGapSecLevelsT {
    bool lv1;
    bool lv2;
    bool lv3;
    bool lv4;
} sd_types_BleGapSecLevelsT;

/* GAP Advertising Report Type */
typedef struct _sd_types_BleGapAdvReportTypeT {
    bool connectable;
    bool scannable;
    bool directed;
    bool scan_response;
    bool extended_pdu;
    sd_types_BleGapAdvReportType status; /* 2-bit field */
    uint16_t reserved; /* 9-bit field */
} sd_types_BleGapAdvReportTypeT;

/* GAP Auxiliary Pointer */
typedef struct _sd_types_BleGapAuxPointer {
    uint16_t aux_offset;
    sd_types_BleGapPhy aux_phy;
} sd_types_BleGapAuxPointer;

typedef PB_BYTES_ARRAY_T(512) sd_types_BleGattsAuthorizeParams_p_data_t;
/* GATTS Authorize Parameters */
typedef struct _sd_types_BleGattsAuthorizeParams {
    uint16_t gatt_status; /* BLE_GATT_STATUS_CODES */
    bool update; /* 1-bit field */
    uint16_t offset;
    uint16_t len;
    sd_types_BleGattsAuthorizeParams_p_data_t p_data; /* Optional */
} sd_types_BleGattsAuthorizeParams;

/* GATTS Read/Write Authorize Reply Parameters */
typedef struct _sd_types_BleGattsRwAuthorizeReplyParams {
    uint8_t type; /* BLE_GATTS_AUTHORIZE_TYPES */
    bool has_read;
    sd_types_BleGattsAuthorizeParams read; /* Optional */
    bool has_write;
    sd_types_BleGattsAuthorizeParams write; /* Optional */
} sd_types_BleGattsRwAuthorizeReplyParams;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _sd_types_BleGapAddrType_MIN sd_types_BleGapAddrType_BLE_GAP_ADDR_TYPE_PUBLIC
#define _sd_types_BleGapAddrType_MAX sd_types_BleGapAddrType_BLE_GAP_ADDR_TYPE_ANONYMOUS
#define _sd_types_BleGapAddrType_ARRAYSIZE ((sd_types_BleGapAddrType)(sd_types_BleGapAddrType_BLE_GAP_ADDR_TYPE_ANONYMOUS+1))

#define _sd_types_BleGapPrivacyMode_MIN sd_types_BleGapPrivacyMode_BLE_GAP_PRIVACY_MODE_OFF
#define _sd_types_BleGapPrivacyMode_MAX sd_types_BleGapPrivacyMode_BLE_GAP_PRIVACY_MODE_NETWORK_PRIVACY
#define _sd_types_BleGapPrivacyMode_ARRAYSIZE ((sd_types_BleGapPrivacyMode)(sd_types_BleGapPrivacyMode_BLE_GAP_PRIVACY_MODE_NETWORK_PRIVACY+1))

#define _sd_types_BleGapAdvType_MIN sd_types_BleGapAdvType_BLE_GAP_ADV_TYPE_UNKNOWN
#define _sd_types_BleGapAdvType_MAX sd_types_BleGapAdvType_BLE_GAP_ADV_TYPE_EXTENDED_NONCONNECTABLE_NONSCANNABLE_DIRECTED
#define _sd_types_BleGapAdvType_ARRAYSIZE ((sd_types_BleGapAdvType)(sd_types_BleGapAdvType_BLE_GAP_ADV_TYPE_EXTENDED_NONCONNECTABLE_NONSCANNABLE_DIRECTED+1))

#define _sd_types_BleGapAdvFilterPolicy_MIN sd_types_BleGapAdvFilterPolicy_BLE_GAP_ADV_FP_ANY
#define _sd_types_BleGapAdvFilterPolicy_MAX sd_types_BleGapAdvFilterPolicy_BLE_GAP_ADV_FP_FILTER_BOTH
#define _sd_types_BleGapAdvFilterPolicy_ARRAYSIZE ((sd_types_BleGapAdvFilterPolicy)(sd_types_BleGapAdvFilterPolicy_BLE_GAP_ADV_FP_FILTER_BOTH+1))

#define _sd_types_BleGapPhy_MIN sd_types_BleGapPhy_BLE_GAP_PHY_AUTO
#define _sd_types_BleGapPhy_MAX sd_types_BleGapPhy_BLE_GAP_PHY_NOT_SET
#define _sd_types_BleGapPhy_ARRAYSIZE ((sd_types_BleGapPhy)(sd_types_BleGapPhy_BLE_GAP_PHY_NOT_SET+1))

#define _sd_types_BleGapIoCaps_MIN sd_types_BleGapIoCaps_BLE_GAP_IO_CAPS_DISPLAY_ONLY
#define _sd_types_BleGapIoCaps_MAX sd_types_BleGapIoCaps_BLE_GAP_IO_CAPS_KEYBOARD_DISPLAY
#define _sd_types_BleGapIoCaps_ARRAYSIZE ((sd_types_BleGapIoCaps)(sd_types_BleGapIoCaps_BLE_GAP_IO_CAPS_KEYBOARD_DISPLAY+1))

#define _sd_types_BleGapAuthKeyType_MIN sd_types_BleGapAuthKeyType_BLE_GAP_AUTH_KEY_TYPE_NONE
#define _sd_types_BleGapAuthKeyType_MAX sd_types_BleGapAuthKeyType_BLE_GAP_AUTH_KEY_TYPE_OOB
#define _sd_types_BleGapAuthKeyType_ARRAYSIZE ((sd_types_BleGapAuthKeyType)(sd_types_BleGapAuthKeyType_BLE_GAP_AUTH_KEY_TYPE_OOB+1))

#define _sd_types_BleGapKpNotType_MIN sd_types_BleGapKpNotType_BLE_GAP_KP_NOT_TYPE_PASSKEY_START
#define _sd_types_BleGapKpNotType_MAX sd_types_BleGapKpNotType_BLE_GAP_KP_NOT_TYPE_PASSKEY_END
#define _sd_types_BleGapKpNotType_ARRAYSIZE ((sd_types_BleGapKpNotType)(sd_types_BleGapKpNotType_BLE_GAP_KP_NOT_TYPE_PASSKEY_END+1))

#define _sd_types_BleGapTimeoutSrc_MIN sd_types_BleGapTimeoutSrc_BLE_GAP_TIMEOUT_SRC_INVALID
#define _sd_types_BleGapTimeoutSrc_MAX sd_types_BleGapTimeoutSrc_BLE_GAP_TIMEOUT_SRC_AUTH_PAYLOAD
#define _sd_types_BleGapTimeoutSrc_ARRAYSIZE ((sd_types_BleGapTimeoutSrc)(sd_types_BleGapTimeoutSrc_BLE_GAP_TIMEOUT_SRC_AUTH_PAYLOAD+1))

#define _sd_types_BleGapAdvReportType_MIN sd_types_BleGapAdvReportType_BLE_GAP_ADV_DATA_STATUS_COMPLETE
#define _sd_types_BleGapAdvReportType_MAX sd_types_BleGapAdvReportType_BLE_GAP_ADV_DATA_STATUS_INCOMPLETE_MISSED
#define _sd_types_BleGapAdvReportType_ARRAYSIZE ((sd_types_BleGapAdvReportType)(sd_types_BleGapAdvReportType_BLE_GAP_ADV_DATA_STATUS_INCOMPLETE_MISSED+1))

#define _sd_types_BleGapAdvSetTerminatedReason_MIN sd_types_BleGapAdvSetTerminatedReason_BLE_GAP_EVT_ADV_SET_TERMINATED_REASON_INVALID
#define _sd_types_BleGapAdvSetTerminatedReason_MAX sd_types_BleGapAdvSetTerminatedReason_BLE_GAP_EVT_ADV_SET_TERMINATED_REASON_LIMIT_REACHED
#define _sd_types_BleGapAdvSetTerminatedReason_ARRAYSIZE ((sd_types_BleGapAdvSetTerminatedReason)(sd_types_BleGapAdvSetTerminatedReason_BLE_GAP_EVT_ADV_SET_TERMINATED_REASON_LIMIT_REACHED+1))

#define _sd_types_BleGapSecLevels_MIN sd_types_BleGapSecLevels_BLE_GAP_SEC_LEVEL_INVALID
#define _sd_types_BleGapSecLevels_MAX sd_types_BleGapSecLevels_BLE_GAP_SEC_LEVEL_4
#define _sd_types_BleGapSecLevels_ARRAYSIZE ((sd_types_BleGapSecLevels)(sd_types_BleGapSecLevels_BLE_GAP_SEC_LEVEL_4+1))

#define _sd_types_BleGattTimeoutSrc_MIN sd_types_BleGattTimeoutSrc_BLE_GATT_TIMEOUT_SRC_PROTOCOL
#define _sd_types_BleGattTimeoutSrc_MAX sd_types_BleGattTimeoutSrc_BLE_GATT_TIMEOUT_SRC_PROTOCOL
#define _sd_types_BleGattTimeoutSrc_ARRAYSIZE ((sd_types_BleGattTimeoutSrc)(sd_types_BleGattTimeoutSrc_BLE_GATT_TIMEOUT_SRC_PROTOCOL+1))

#define _sd_types_BleGattWriteOp_MIN sd_types_BleGattWriteOp_BLE_GATT_OP_INVALID
#define _sd_types_BleGattWriteOp_MAX sd_types_BleGattWriteOp_BLE_GATT_OP_EXEC_WRITE_REQ_NOW
#define _sd_types_BleGattWriteOp_ARRAYSIZE ((sd_types_BleGattWriteOp)(sd_types_BleGattWriteOp_BLE_GATT_OP_EXEC_WRITE_REQ_NOW+1))

#define _sd_types_BleGattExecWriteFlag_MIN sd_types_BleGattExecWriteFlag_BLE_GATT_EXEC_WRITE_FLAG_PREPARED_CANCEL
#define _sd_types_BleGattExecWriteFlag_MAX sd_types_BleGattExecWriteFlag_BLE_GATT_EXEC_WRITE_FLAG_PREPARED_WRITE
#define _sd_types_BleGattExecWriteFlag_ARRAYSIZE ((sd_types_BleGattExecWriteFlag)(sd_types_BleGattExecWriteFlag_BLE_GATT_EXEC_WRITE_FLAG_PREPARED_WRITE+1))

#define _sd_types_BleGattHvxType_MIN sd_types_BleGattHvxType_BLE_GATT_HVX_INVALID
#define _sd_types_BleGattHvxType_MAX sd_types_BleGattHvxType_BLE_GATT_HVX_INDICATION
#define _sd_types_BleGattHvxType_ARRAYSIZE ((sd_types_BleGattHvxType)(sd_types_BleGattHvxType_BLE_GATT_HVX_INDICATION+1))

#define _sd_types_BleGattcAttrInfoFormat_MIN sd_types_BleGattcAttrInfoFormat_BLE_GATTC_ATTR_INFO_FORMAT_INVALID
#define _sd_types_BleGattcAttrInfoFormat_MAX sd_types_BleGattcAttrInfoFormat_BLE_GATTC_ATTR_INFO_FORMAT_128BIT
#define _sd_types_BleGattcAttrInfoFormat_ARRAYSIZE ((sd_types_BleGattcAttrInfoFormat)(sd_types_BleGattcAttrInfoFormat_BLE_GATTC_ATTR_INFO_FORMAT_128BIT+1))

#define _sd_types_BleGattsOp_MIN sd_types_BleGattsOp_BLE_GATTS_OP_INVALID
#define _sd_types_BleGattsOp_MAX sd_types_BleGattsOp_BLE_GATTS_OP_EXEC_WRITE_REQ_NOW
#define _sd_types_BleGattsOp_ARRAYSIZE ((sd_types_BleGattsOp)(sd_types_BleGattsOp_BLE_GATTS_OP_EXEC_WRITE_REQ_NOW+1))

#define _sd_types_BleGattsAuthorizeType_MIN sd_types_BleGattsAuthorizeType_BLE_GATTS_AUTHORIZE_TYPE_INVALID
#define _sd_types_BleGattsAuthorizeType_MAX sd_types_BleGattsAuthorizeType_BLE_GATTS_AUTHORIZE_TYPE_WRITE
#define _sd_types_BleGattsAuthorizeType_ARRAYSIZE ((sd_types_BleGattsAuthorizeType)(sd_types_BleGattsAuthorizeType_BLE_GATTS_AUTHORIZE_TYPE_WRITE+1))

#define _sd_types_BleGattsVloc_MIN sd_types_BleGattsVloc_BLE_GATTS_VLOC_INVALID
#define _sd_types_BleGattsVloc_MAX sd_types_BleGattsVloc_BLE_GATTS_VLOC_USER
#define _sd_types_BleGattsVloc_ARRAYSIZE ((sd_types_BleGattsVloc)(sd_types_BleGattsVloc_BLE_GATTS_VLOC_USER+1))

#define _sd_types_BleGapSecStatus_MIN sd_types_BleGapSecStatus_BLE_GAP_SEC_STATUS_SUCCESS
#define _sd_types_BleGapSecStatus_MAX sd_types_BleGapSecStatus_BLE_GAP_SEC_STATUS_X_TRANS_KEY_DISALLOWED
#define _sd_types_BleGapSecStatus_ARRAYSIZE ((sd_types_BleGapSecStatus)(sd_types_BleGapSecStatus_BLE_GAP_SEC_STATUS_X_TRANS_KEY_DISALLOWED+1))

#define sd_types_BleGapAddr_addr_type_ENUMTYPE sd_types_BleGapAddrType





#define sd_types_BleGapAdvProperties_type_ENUMTYPE sd_types_BleGapAdvType

#define sd_types_BleGapAdvParams_filter_policy_ENUMTYPE sd_types_BleGapAdvFilterPolicy
#define sd_types_BleGapAdvParams_primary_phy_ENUMTYPE sd_types_BleGapPhy
#define sd_types_BleGapAdvParams_secondary_phy_ENUMTYPE sd_types_BleGapPhy



#define sd_types_BleGapScanParams_scan_phys_ENUMTYPE sd_types_BleGapPhy

#define sd_types_BleGapPrivacyParams_privacy_mode_ENUMTYPE sd_types_BleGapPrivacyMode
#define sd_types_BleGapPrivacyParams_private_addr_type_ENUMTYPE sd_types_BleGapAddrType


#define sd_types_BleGapSecParams_io_caps_ENUMTYPE sd_types_BleGapIoCaps



























#define sd_types_BleGattsAttrMd_vloc_ENUMTYPE sd_types_BleGattsVloc









#define sd_types_BleGapAdvReportTypeT_status_ENUMTYPE sd_types_BleGapAdvReportType

#define sd_types_BleGapAuxPointer_aux_phy_ENUMTYPE sd_types_BleGapPhy




/* Initializer values for message structs */
#define sd_types_BleGapAddr_init_default         {0, _sd_types_BleGapAddrType_MIN, {0}}
#define sd_types_BleGapConnParams_init_default   {0, 0, 0, 0}
#define sd_types_BleGapConnSecMode_init_default  {0, 0}
#define sd_types_BleGapIrk_init_default          {{0}}
#define sd_types_BleGapChMask_init_default       {{0}}
#define sd_types_BleGapAdvProperties_init_default {_sd_types_BleGapAdvType_MIN, 0, 0}
#define sd_types_BleGapAdvParams_init_default    {false, sd_types_BleGapAdvProperties_init_default, false, sd_types_BleGapAddr_init_default, 0, 0, 0, false, sd_types_BleGapChMask_init_default, _sd_types_BleGapAdvFilterPolicy_MIN, _sd_types_BleGapPhy_MIN, _sd_types_BleGapPhy_MIN, 0, 0}
#define sd_types_BleData_init_default            {{0, {0}}, 0}
#define sd_types_BleGapAdvData_init_default      {false, sd_types_BleData_init_default, false, sd_types_BleData_init_default}
#define sd_types_BleGapScanParams_init_default   {0, 0, 0, 0, _sd_types_BleGapPhy_MIN, 0, 0, 0, false, sd_types_BleGapChMask_init_default}
#define sd_types_BleGapPrivacyParams_init_default {_sd_types_BleGapPrivacyMode_MIN, _sd_types_BleGapAddrType_MIN, 0, false, sd_types_BleGapIrk_init_default}
#define sd_types_BleGapSecKdist_init_default     {0, 0, 0, 0}
#define sd_types_BleGapSecParams_init_default    {0, 0, 0, 0, _sd_types_BleGapIoCaps_MIN, 0, 0, 0, false, sd_types_BleGapSecKdist_init_default, false, sd_types_BleGapSecKdist_init_default}
#define sd_types_BleGapEncInfo_init_default      {{0}, 0, 0, 0}
#define sd_types_BleGapMasterId_init_default     {0, {0}}
#define sd_types_BleGapSignInfo_init_default     {{0}}
#define sd_types_BleGapLescP256Pk_init_default   {{0}}
#define sd_types_BleGapLescDhkey_init_default    {{0}}
#define sd_types_BleGapLescOobData_init_default  {false, sd_types_BleGapAddr_init_default, {0}, {0}}
#define sd_types_BleGapConnSec_init_default      {false, sd_types_BleGapConnSecMode_init_default, 0}
#define sd_types_BleGapEncKey_init_default       {false, sd_types_BleGapEncInfo_init_default, false, sd_types_BleGapMasterId_init_default}
#define sd_types_BleGapIdKey_init_default        {false, sd_types_BleGapIrk_init_default, false, sd_types_BleGapAddr_init_default}
#define sd_types_BleGapSecKeys_init_default      {false, sd_types_BleGapEncKey_init_default, false, sd_types_BleGapIdKey_init_default, false, sd_types_BleGapSignInfo_init_default, false, sd_types_BleGapLescP256Pk_init_default}
#define sd_types_BleGapSecKeyset_init_default    {false, sd_types_BleGapSecKeys_init_default, false, sd_types_BleGapSecKeys_init_default}
#define sd_types_BleGapDataLengthParams_init_default {0, 0, 0, 0}
#define sd_types_BleGapDataLengthLimitation_init_default {0, 0, 0}
#define sd_types_BleGapConnEventTrigger_init_default {0, 0, 0, 0}
#define sd_types_BleUuid_init_default            {0, 0}
#define sd_types_BleUuid128_init_default         {{0}}
#define sd_types_BleGattCharProps_init_default   {0, 0, 0, 0, 0, 0, 0}
#define sd_types_BleGattcHandleRange_init_default {0, 0}
#define sd_types_BleGattcWriteParams_init_default {0, 0, 0, 0, 0, {0, {0}}}
#define sd_types_BleGattcService_init_default    {false, sd_types_BleUuid_init_default, false, sd_types_BleGattcHandleRange_init_default}
#define sd_types_BleGattcInclude_init_default    {0, false, sd_types_BleGattcService_init_default}
#define sd_types_BleGattcChar_init_default       {false, sd_types_BleUuid_init_default, false, sd_types_BleGattCharProps_init_default, 0, 0, 0}
#define sd_types_BleGattcDesc_init_default       {0, false, sd_types_BleUuid_init_default}
#define sd_types_BleGattcAttrInfo16_init_default {0, false, sd_types_BleUuid_init_default}
#define sd_types_BleGattcAttrInfo128_init_default {0, false, sd_types_BleUuid128_init_default}
#define sd_types_BleGattcHandleValue_init_default {0, {0, {0}}}
#define sd_types_BleGattsAttrMd_init_default     {false, sd_types_BleGapConnSecMode_init_default, false, sd_types_BleGapConnSecMode_init_default, 0, _sd_types_BleGattsVloc_MIN, 0, 0}
#define sd_types_BleGattsAttr_init_default       {false, sd_types_BleUuid_init_default, false, sd_types_BleGattsAttrMd_init_default, 0, 0, 0, {0, {0}}}
#define sd_types_BleGattsValue_init_default      {0, 0, {0, {0}}}
#define sd_types_BleGattsCharPf_init_default     {0, 0, 0, 0, 0}
#define sd_types_BleGattCharExtProps_init_default {0, 0}
#define sd_types_BleGattsCharMd_init_default     {false, sd_types_BleGattCharProps_init_default, false, sd_types_BleGattCharExtProps_init_default, {0, {0}}, 0, 0, false, sd_types_BleGattsCharPf_init_default, false, sd_types_BleGattsAttrMd_init_default, false, sd_types_BleGattsAttrMd_init_default, false, sd_types_BleGattsAttrMd_init_default}
#define sd_types_BleGattsCharHandles_init_default {0, 0, 0, 0}
#define sd_types_BleGattsHvxParams_init_default  {0, 0, 0, 0, {0, {0}}}
#define sd_types_BleGapSecLevelsT_init_default   {0, 0, 0, 0}
#define sd_types_BleGapAdvReportTypeT_init_default {0, 0, 0, 0, 0, _sd_types_BleGapAdvReportType_MIN, 0}
#define sd_types_BleGapAuxPointer_init_default   {0, _sd_types_BleGapPhy_MIN}
#define sd_types_BleGattsAuthorizeParams_init_default {0, 0, 0, 0, {0, {0}}}
#define sd_types_BleGattsRwAuthorizeReplyParams_init_default {0, false, sd_types_BleGattsAuthorizeParams_init_default, false, sd_types_BleGattsAuthorizeParams_init_default}
#define sd_types_BleGapAddr_init_zero            {0, _sd_types_BleGapAddrType_MIN, {0}}
#define sd_types_BleGapConnParams_init_zero      {0, 0, 0, 0}
#define sd_types_BleGapConnSecMode_init_zero     {0, 0}
#define sd_types_BleGapIrk_init_zero             {{0}}
#define sd_types_BleGapChMask_init_zero          {{0}}
#define sd_types_BleGapAdvProperties_init_zero   {_sd_types_BleGapAdvType_MIN, 0, 0}
#define sd_types_BleGapAdvParams_init_zero       {false, sd_types_BleGapAdvProperties_init_zero, false, sd_types_BleGapAddr_init_zero, 0, 0, 0, false, sd_types_BleGapChMask_init_zero, _sd_types_BleGapAdvFilterPolicy_MIN, _sd_types_BleGapPhy_MIN, _sd_types_BleGapPhy_MIN, 0, 0}
#define sd_types_BleData_init_zero               {{0, {0}}, 0}
#define sd_types_BleGapAdvData_init_zero         {false, sd_types_BleData_init_zero, false, sd_types_BleData_init_zero}
#define sd_types_BleGapScanParams_init_zero      {0, 0, 0, 0, _sd_types_BleGapPhy_MIN, 0, 0, 0, false, sd_types_BleGapChMask_init_zero}
#define sd_types_BleGapPrivacyParams_init_zero   {_sd_types_BleGapPrivacyMode_MIN, _sd_types_BleGapAddrType_MIN, 0, false, sd_types_BleGapIrk_init_zero}
#define sd_types_BleGapSecKdist_init_zero        {0, 0, 0, 0}
#define sd_types_BleGapSecParams_init_zero       {0, 0, 0, 0, _sd_types_BleGapIoCaps_MIN, 0, 0, 0, false, sd_types_BleGapSecKdist_init_zero, false, sd_types_BleGapSecKdist_init_zero}
#define sd_types_BleGapEncInfo_init_zero         {{0}, 0, 0, 0}
#define sd_types_BleGapMasterId_init_zero        {0, {0}}
#define sd_types_BleGapSignInfo_init_zero        {{0}}
#define sd_types_BleGapLescP256Pk_init_zero      {{0}}
#define sd_types_BleGapLescDhkey_init_zero       {{0}}
#define sd_types_BleGapLescOobData_init_zero     {false, sd_types_BleGapAddr_init_zero, {0}, {0}}
#define sd_types_BleGapConnSec_init_zero         {false, sd_types_BleGapConnSecMode_init_zero, 0}
#define sd_types_BleGapEncKey_init_zero          {false, sd_types_BleGapEncInfo_init_zero, false, sd_types_BleGapMasterId_init_zero}
#define sd_types_BleGapIdKey_init_zero           {false, sd_types_BleGapIrk_init_zero, false, sd_types_BleGapAddr_init_zero}
#define sd_types_BleGapSecKeys_init_zero         {false, sd_types_BleGapEncKey_init_zero, false, sd_types_BleGapIdKey_init_zero, false, sd_types_BleGapSignInfo_init_zero, false, sd_types_BleGapLescP256Pk_init_zero}
#define sd_types_BleGapSecKeyset_init_zero       {false, sd_types_BleGapSecKeys_init_zero, false, sd_types_BleGapSecKeys_init_zero}
#define sd_types_BleGapDataLengthParams_init_zero {0, 0, 0, 0}
#define sd_types_BleGapDataLengthLimitation_init_zero {0, 0, 0}
#define sd_types_BleGapConnEventTrigger_init_zero {0, 0, 0, 0}
#define sd_types_BleUuid_init_zero               {0, 0}
#define sd_types_BleUuid128_init_zero            {{0}}
#define sd_types_BleGattCharProps_init_zero      {0, 0, 0, 0, 0, 0, 0}
#define sd_types_BleGattcHandleRange_init_zero   {0, 0}
#define sd_types_BleGattcWriteParams_init_zero   {0, 0, 0, 0, 0, {0, {0}}}
#define sd_types_BleGattcService_init_zero       {false, sd_types_BleUuid_init_zero, false, sd_types_BleGattcHandleRange_init_zero}
#define sd_types_BleGattcInclude_init_zero       {0, false, sd_types_BleGattcService_init_zero}
#define sd_types_BleGattcChar_init_zero          {false, sd_types_BleUuid_init_zero, false, sd_types_BleGattCharProps_init_zero, 0, 0, 0}
#define sd_types_BleGattcDesc_init_zero          {0, false, sd_types_BleUuid_init_zero}
#define sd_types_BleGattcAttrInfo16_init_zero    {0, false, sd_types_BleUuid_init_zero}
#define sd_types_BleGattcAttrInfo128_init_zero   {0, false, sd_types_BleUuid128_init_zero}
#define sd_types_BleGattcHandleValue_init_zero   {0, {0, {0}}}
#define sd_types_BleGattsAttrMd_init_zero        {false, sd_types_BleGapConnSecMode_init_zero, false, sd_types_BleGapConnSecMode_init_zero, 0, _sd_types_BleGattsVloc_MIN, 0, 0}
#define sd_types_BleGattsAttr_init_zero          {false, sd_types_BleUuid_init_zero, false, sd_types_BleGattsAttrMd_init_zero, 0, 0, 0, {0, {0}}}
#define sd_types_BleGattsValue_init_zero         {0, 0, {0, {0}}}
#define sd_types_BleGattsCharPf_init_zero        {0, 0, 0, 0, 0}
#define sd_types_BleGattCharExtProps_init_zero   {0, 0}
#define sd_types_BleGattsCharMd_init_zero        {false, sd_types_BleGattCharProps_init_zero, false, sd_types_BleGattCharExtProps_init_zero, {0, {0}}, 0, 0, false, sd_types_BleGattsCharPf_init_zero, false, sd_types_BleGattsAttrMd_init_zero, false, sd_types_BleGattsAttrMd_init_zero, false, sd_types_BleGattsAttrMd_init_zero}
#define sd_types_BleGattsCharHandles_init_zero   {0, 0, 0, 0}
#define sd_types_BleGattsHvxParams_init_zero     {0, 0, 0, 0, {0, {0}}}
#define sd_types_BleGapSecLevelsT_init_zero      {0, 0, 0, 0}
#define sd_types_BleGapAdvReportTypeT_init_zero  {0, 0, 0, 0, 0, _sd_types_BleGapAdvReportType_MIN, 0}
#define sd_types_BleGapAuxPointer_init_zero      {0, _sd_types_BleGapPhy_MIN}
#define sd_types_BleGattsAuthorizeParams_init_zero {0, 0, 0, 0, {0, {0}}}
#define sd_types_BleGattsRwAuthorizeReplyParams_init_zero {0, false, sd_types_BleGattsAuthorizeParams_init_zero, false, sd_types_BleGattsAuthorizeParams_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define sd_types_BleGapAddr_addr_id_peer_tag     1
#define sd_types_BleGapAddr_addr_type_tag        2
#define sd_types_BleGapAddr_addr_tag             3
#define sd_types_BleGapConnParams_min_conn_interval_tag 1
#define sd_types_BleGapConnParams_max_conn_interval_tag 2
#define sd_types_BleGapConnParams_slave_latency_tag 3
#define sd_types_BleGapConnParams_conn_sup_timeout_tag 4
#define sd_types_BleGapConnSecMode_sm_tag        1
#define sd_types_BleGapConnSecMode_lv_tag        2
#define sd_types_BleGapIrk_irk_tag               1
#define sd_types_BleGapChMask_ch_mask_tag        1
#define sd_types_BleGapAdvProperties_type_tag    1
#define sd_types_BleGapAdvProperties_anonymous_tag 2
#define sd_types_BleGapAdvProperties_include_tx_power_tag 3
#define sd_types_BleGapAdvParams_properties_tag  1
#define sd_types_BleGapAdvParams_peer_addr_tag   2
#define sd_types_BleGapAdvParams_interval_tag    3
#define sd_types_BleGapAdvParams_duration_tag    4
#define sd_types_BleGapAdvParams_max_adv_evts_tag 5
#define sd_types_BleGapAdvParams_channel_mask_tag 6
#define sd_types_BleGapAdvParams_filter_policy_tag 7
#define sd_types_BleGapAdvParams_primary_phy_tag 8
#define sd_types_BleGapAdvParams_secondary_phy_tag 9
#define sd_types_BleGapAdvParams_set_id_tag      10
#define sd_types_BleGapAdvParams_scan_req_notification_tag 11
#define sd_types_BleData_data_tag                1
#define sd_types_BleData_len_tag                 2
#define sd_types_BleGapAdvData_adv_data_tag      1
#define sd_types_BleGapAdvData_scan_rsp_data_tag 2
#define sd_types_BleGapScanParams_extended_tag   1
#define sd_types_BleGapScanParams_report_incomplete_evts_tag 2
#define sd_types_BleGapScanParams_active_tag     3
#define sd_types_BleGapScanParams_filter_policy_tag 4
#define sd_types_BleGapScanParams_scan_phys_tag  5
#define sd_types_BleGapScanParams_interval_tag   6
#define sd_types_BleGapScanParams_window_tag     7
#define sd_types_BleGapScanParams_timeout_tag    8
#define sd_types_BleGapScanParams_channel_mask_tag 9
#define sd_types_BleGapPrivacyParams_privacy_mode_tag 1
#define sd_types_BleGapPrivacyParams_private_addr_type_tag 2
#define sd_types_BleGapPrivacyParams_private_addr_cycle_s_tag 3
#define sd_types_BleGapPrivacyParams_device_irk_tag 4
#define sd_types_BleGapSecKdist_enc_tag          1
#define sd_types_BleGapSecKdist_id_tag           2
#define sd_types_BleGapSecKdist_sign_tag         3
#define sd_types_BleGapSecKdist_link_tag         4
#define sd_types_BleGapSecParams_bond_tag        1
#define sd_types_BleGapSecParams_mitm_tag        2
#define sd_types_BleGapSecParams_lesc_tag        3
#define sd_types_BleGapSecParams_keypress_tag    4
#define sd_types_BleGapSecParams_io_caps_tag     5
#define sd_types_BleGapSecParams_oob_tag         6
#define sd_types_BleGapSecParams_min_key_size_tag 7
#define sd_types_BleGapSecParams_max_key_size_tag 8
#define sd_types_BleGapSecParams_kdist_own_tag   9
#define sd_types_BleGapSecParams_kdist_peer_tag  10
#define sd_types_BleGapEncInfo_ltk_tag           1
#define sd_types_BleGapEncInfo_lesc_tag          2
#define sd_types_BleGapEncInfo_auth_tag          3
#define sd_types_BleGapEncInfo_ltk_len_tag       4
#define sd_types_BleGapMasterId_ediv_tag         1
#define sd_types_BleGapMasterId_rand_tag         2
#define sd_types_BleGapSignInfo_csrk_tag         1
#define sd_types_BleGapLescP256Pk_pk_tag         1
#define sd_types_BleGapLescDhkey_key_tag         1
#define sd_types_BleGapLescOobData_addr_tag      1
#define sd_types_BleGapLescOobData_r_tag         2
#define sd_types_BleGapLescOobData_c_tag         3
#define sd_types_BleGapConnSec_sec_mode_tag      1
#define sd_types_BleGapConnSec_encr_key_size_tag 2
#define sd_types_BleGapEncKey_enc_info_tag       1
#define sd_types_BleGapEncKey_master_id_tag      2
#define sd_types_BleGapIdKey_id_info_tag         1
#define sd_types_BleGapIdKey_id_addr_info_tag    2
#define sd_types_BleGapSecKeys_enc_key_tag       1
#define sd_types_BleGapSecKeys_id_key_tag        2
#define sd_types_BleGapSecKeys_sign_key_tag      3
#define sd_types_BleGapSecKeys_pk_tag            4
#define sd_types_BleGapSecKeyset_keys_own_tag    1
#define sd_types_BleGapSecKeyset_keys_peer_tag   2
#define sd_types_BleGapDataLengthParams_max_tx_octets_tag 1
#define sd_types_BleGapDataLengthParams_max_rx_octets_tag 2
#define sd_types_BleGapDataLengthParams_max_tx_time_us_tag 3
#define sd_types_BleGapDataLengthParams_max_rx_time_us_tag 4
#define sd_types_BleGapDataLengthLimitation_tx_payload_limited_octets_tag 1
#define sd_types_BleGapDataLengthLimitation_rx_payload_limited_octets_tag 2
#define sd_types_BleGapDataLengthLimitation_tx_rx_time_limited_us_tag 3
#define sd_types_BleGapConnEventTrigger_ppi_ch_id_tag 1
#define sd_types_BleGapConnEventTrigger_task_endpoint_tag 2
#define sd_types_BleGapConnEventTrigger_conn_evt_counter_start_tag 3
#define sd_types_BleGapConnEventTrigger_period_in_events_tag 4
#define sd_types_BleUuid_uuid_tag                1
#define sd_types_BleUuid_type_tag                2
#define sd_types_BleUuid128_uuid128_tag          1
#define sd_types_BleGattCharProps_broadcast_tag  1
#define sd_types_BleGattCharProps_read_tag       2
#define sd_types_BleGattCharProps_write_wo_resp_tag 3
#define sd_types_BleGattCharProps_write_tag      4
#define sd_types_BleGattCharProps_notify_tag     5
#define sd_types_BleGattCharProps_indicate_tag   6
#define sd_types_BleGattCharProps_auth_signed_wr_tag 7
#define sd_types_BleGattcHandleRange_start_handle_tag 1
#define sd_types_BleGattcHandleRange_end_handle_tag 2
#define sd_types_BleGattcWriteParams_write_op_tag 1
#define sd_types_BleGattcWriteParams_flags_tag   2
#define sd_types_BleGattcWriteParams_handle_tag  3
#define sd_types_BleGattcWriteParams_offset_tag  4
#define sd_types_BleGattcWriteParams_len_tag     5
#define sd_types_BleGattcWriteParams_p_value_tag 6
#define sd_types_BleGattcService_uuid_tag        1
#define sd_types_BleGattcService_handle_range_tag 2
#define sd_types_BleGattcInclude_handle_tag      1
#define sd_types_BleGattcInclude_included_srvc_tag 2
#define sd_types_BleGattcChar_uuid_tag           1
#define sd_types_BleGattcChar_char_props_tag     2
#define sd_types_BleGattcChar_char_ext_props_tag 3
#define sd_types_BleGattcChar_handle_decl_tag    4
#define sd_types_BleGattcChar_handle_value_tag   5
#define sd_types_BleGattcDesc_handle_tag         1
#define sd_types_BleGattcDesc_uuid_tag           2
#define sd_types_BleGattcAttrInfo16_handle_tag   1
#define sd_types_BleGattcAttrInfo16_uuid_tag     2
#define sd_types_BleGattcAttrInfo128_handle_tag  1
#define sd_types_BleGattcAttrInfo128_uuid_tag    2
#define sd_types_BleGattcHandleValue_handle_tag  1
#define sd_types_BleGattcHandleValue_p_value_tag 2
#define sd_types_BleGattsAttrMd_read_perm_tag    1
#define sd_types_BleGattsAttrMd_write_perm_tag   2
#define sd_types_BleGattsAttrMd_vlen_tag         3
#define sd_types_BleGattsAttrMd_vloc_tag         4
#define sd_types_BleGattsAttrMd_rd_auth_tag      5
#define sd_types_BleGattsAttrMd_wr_auth_tag      6
#define sd_types_BleGattsAttr_uuid_tag           1
#define sd_types_BleGattsAttr_attr_md_tag        2
#define sd_types_BleGattsAttr_init_len_tag       3
#define sd_types_BleGattsAttr_init_offs_tag      4
#define sd_types_BleGattsAttr_max_len_tag        5
#define sd_types_BleGattsAttr_p_value_tag        6
#define sd_types_BleGattsValue_len_tag           1
#define sd_types_BleGattsValue_offset_tag        2
#define sd_types_BleGattsValue_p_value_tag       3
#define sd_types_BleGattsCharPf_format_tag       1
#define sd_types_BleGattsCharPf_exponent_tag     2
#define sd_types_BleGattsCharPf_unit_tag         3
#define sd_types_BleGattsCharPf_name_space_tag   4
#define sd_types_BleGattsCharPf_desc_tag         5
#define sd_types_BleGattCharExtProps_reliable_wr_tag 1
#define sd_types_BleGattCharExtProps_wr_aux_tag  2
#define sd_types_BleGattsCharMd_char_props_tag   1
#define sd_types_BleGattsCharMd_char_ext_props_tag 2
#define sd_types_BleGattsCharMd_p_char_user_desc_tag 3
#define sd_types_BleGattsCharMd_char_user_desc_max_size_tag 4
#define sd_types_BleGattsCharMd_char_user_desc_size_tag 5
#define sd_types_BleGattsCharMd_char_pf_tag      6
#define sd_types_BleGattsCharMd_user_desc_md_tag 7
#define sd_types_BleGattsCharMd_cccd_md_tag      8
#define sd_types_BleGattsCharMd_sccd_md_tag      9
#define sd_types_BleGattsCharHandles_value_handle_tag 1
#define sd_types_BleGattsCharHandles_user_desc_handle_tag 2
#define sd_types_BleGattsCharHandles_cccd_handle_tag 3
#define sd_types_BleGattsCharHandles_sccd_handle_tag 4
#define sd_types_BleGattsHvxParams_handle_tag    1
#define sd_types_BleGattsHvxParams_type_tag      2
#define sd_types_BleGattsHvxParams_offset_tag    3
#define sd_types_BleGattsHvxParams_len_tag       4
#define sd_types_BleGattsHvxParams_p_data_tag    5
#define sd_types_BleGapSecLevelsT_lv1_tag        1
#define sd_types_BleGapSecLevelsT_lv2_tag        2
#define sd_types_BleGapSecLevelsT_lv3_tag        3
#define sd_types_BleGapSecLevelsT_lv4_tag        4
#define sd_types_BleGapAdvReportTypeT_connectable_tag 1
#define sd_types_BleGapAdvReportTypeT_scannable_tag 2
#define sd_types_BleGapAdvReportTypeT_directed_tag 3
#define sd_types_BleGapAdvReportTypeT_scan_response_tag 4
#define sd_types_BleGapAdvReportTypeT_extended_pdu_tag 5
#define sd_types_BleGapAdvReportTypeT_status_tag 6
#define sd_types_BleGapAdvReportTypeT_reserved_tag 7
#define sd_types_BleGapAuxPointer_aux_offset_tag 1
#define sd_types_BleGapAuxPointer_aux_phy_tag    2
#define sd_types_BleGattsAuthorizeParams_gatt_status_tag 1
#define sd_types_BleGattsAuthorizeParams_update_tag 2
#define sd_types_BleGattsAuthorizeParams_offset_tag 3
#define sd_types_BleGattsAuthorizeParams_len_tag 4
#define sd_types_BleGattsAuthorizeParams_p_data_tag 5
#define sd_types_BleGattsRwAuthorizeReplyParams_type_tag 1
#define sd_types_BleGattsRwAuthorizeReplyParams_read_tag 2
#define sd_types_BleGattsRwAuthorizeReplyParams_write_tag 3

/* Struct field encoding specification for nanopb */
#define sd_types_BleGapAddr_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     addr_id_peer,      1) \
X(a, STATIC,   SINGULAR, UENUM,    addr_type,         2) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, addr,              3)
#define sd_types_BleGapAddr_CALLBACK NULL
#define sd_types_BleGapAddr_DEFAULT NULL

#define sd_types_BleGapConnParams_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   min_conn_interval,   1) \
X(a, STATIC,   SINGULAR, UINT32,   max_conn_interval,   2) \
X(a, STATIC,   SINGULAR, UINT32,   slave_latency,     3) \
X(a, STATIC,   SINGULAR, UINT32,   conn_sup_timeout,   4)
#define sd_types_BleGapConnParams_CALLBACK NULL
#define sd_types_BleGapConnParams_DEFAULT NULL

#define sd_types_BleGapConnSecMode_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sm,                1) \
X(a, STATIC,   SINGULAR, UINT32,   lv,                2)
#define sd_types_BleGapConnSecMode_CALLBACK NULL
#define sd_types_BleGapConnSecMode_DEFAULT NULL

#define sd_types_BleGapIrk_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, irk,               1)
#define sd_types_BleGapIrk_CALLBACK NULL
#define sd_types_BleGapIrk_DEFAULT NULL

#define sd_types_BleGapChMask_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, ch_mask,           1)
#define sd_types_BleGapChMask_CALLBACK NULL
#define sd_types_BleGapChMask_DEFAULT NULL

#define sd_types_BleGapAdvProperties_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, BOOL,     anonymous,         2) \
X(a, STATIC,   SINGULAR, BOOL,     include_tx_power,   3)
#define sd_types_BleGapAdvProperties_CALLBACK NULL
#define sd_types_BleGapAdvProperties_DEFAULT NULL

#define sd_types_BleGapAdvParams_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  properties,        1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  peer_addr,         2) \
X(a, STATIC,   SINGULAR, UINT32,   interval,          3) \
X(a, STATIC,   SINGULAR, UINT32,   duration,          4) \
X(a, STATIC,   SINGULAR, UINT32,   max_adv_evts,      5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  channel_mask,      6) \
X(a, STATIC,   SINGULAR, UENUM,    filter_policy,     7) \
X(a, STATIC,   SINGULAR, UENUM,    primary_phy,       8) \
X(a, STATIC,   SINGULAR, UENUM,    secondary_phy,     9) \
X(a, STATIC,   SINGULAR, UINT32,   set_id,           10) \
X(a, STATIC,   SINGULAR, BOOL,     scan_req_notification,  11)
#define sd_types_BleGapAdvParams_CALLBACK NULL
#define sd_types_BleGapAdvParams_DEFAULT NULL
#define sd_types_BleGapAdvParams_properties_MSGTYPE sd_types_BleGapAdvProperties
#define sd_types_BleGapAdvParams_peer_addr_MSGTYPE sd_types_BleGapAddr
#define sd_types_BleGapAdvParams_channel_mask_MSGTYPE sd_types_BleGapChMask

#define sd_types_BleData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    data,              1) \
X(a, STATIC,   SINGULAR, UINT32,   len,               2)
#define sd_types_BleData_CALLBACK NULL
#define sd_types_BleData_DEFAULT NULL

#define sd_types_BleGapAdvData_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  adv_data,          1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  scan_rsp_data,     2)
#define sd_types_BleGapAdvData_CALLBACK NULL
#define sd_types_BleGapAdvData_DEFAULT NULL
#define sd_types_BleGapAdvData_adv_data_MSGTYPE sd_types_BleData
#define sd_types_BleGapAdvData_scan_rsp_data_MSGTYPE sd_types_BleData

#define sd_types_BleGapScanParams_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     extended,          1) \
X(a, STATIC,   SINGULAR, BOOL,     report_incomplete_evts,   2) \
X(a, STATIC,   SINGULAR, BOOL,     active,            3) \
X(a, STATIC,   SINGULAR, UINT32,   filter_policy,     4) \
X(a, STATIC,   SINGULAR, UENUM,    scan_phys,         5) \
X(a, STATIC,   SINGULAR, UINT32,   interval,          6) \
X(a, STATIC,   SINGULAR, UINT32,   window,            7) \
X(a, STATIC,   SINGULAR, UINT32,   timeout,           8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  channel_mask,      9)
#define sd_types_BleGapScanParams_CALLBACK NULL
#define sd_types_BleGapScanParams_DEFAULT NULL
#define sd_types_BleGapScanParams_channel_mask_MSGTYPE sd_types_BleGapChMask

#define sd_types_BleGapPrivacyParams_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    privacy_mode,      1) \
X(a, STATIC,   SINGULAR, UENUM,    private_addr_type,   2) \
X(a, STATIC,   SINGULAR, UINT32,   private_addr_cycle_s,   3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  device_irk,        4)
#define sd_types_BleGapPrivacyParams_CALLBACK NULL
#define sd_types_BleGapPrivacyParams_DEFAULT NULL
#define sd_types_BleGapPrivacyParams_device_irk_MSGTYPE sd_types_BleGapIrk

#define sd_types_BleGapSecKdist_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     enc,               1) \
X(a, STATIC,   SINGULAR, BOOL,     id,                2) \
X(a, STATIC,   SINGULAR, BOOL,     sign,              3) \
X(a, STATIC,   SINGULAR, BOOL,     link,              4)
#define sd_types_BleGapSecKdist_CALLBACK NULL
#define sd_types_BleGapSecKdist_DEFAULT NULL

#define sd_types_BleGapSecParams_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     bond,              1) \
X(a, STATIC,   SINGULAR, BOOL,     mitm,              2) \
X(a, STATIC,   SINGULAR, BOOL,     lesc,              3) \
X(a, STATIC,   SINGULAR, BOOL,     keypress,          4) \
X(a, STATIC,   SINGULAR, UENUM,    io_caps,           5) \
X(a, STATIC,   SINGULAR, BOOL,     oob,               6) \
X(a, STATIC,   SINGULAR, UINT32,   min_key_size,      7) \
X(a, STATIC,   SINGULAR, UINT32,   max_key_size,      8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  kdist_own,         9) \
X(a, STATIC,   OPTIONAL, MESSAGE,  kdist_peer,       10)
#define sd_types_BleGapSecParams_CALLBACK NULL
#define sd_types_BleGapSecParams_DEFAULT NULL
#define sd_types_BleGapSecParams_kdist_own_MSGTYPE sd_types_BleGapSecKdist
#define sd_types_BleGapSecParams_kdist_peer_MSGTYPE sd_types_BleGapSecKdist

#define sd_types_BleGapEncInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, ltk,               1) \
X(a, STATIC,   SINGULAR, BOOL,     lesc,              2) \
X(a, STATIC,   SINGULAR, BOOL,     auth,              3) \
X(a, STATIC,   SINGULAR, UINT32,   ltk_len,           4)
#define sd_types_BleGapEncInfo_CALLBACK NULL
#define sd_types_BleGapEncInfo_DEFAULT NULL

#define sd_types_BleGapMasterId_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ediv,              1) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, rand,              2)
#define sd_types_BleGapMasterId_CALLBACK NULL
#define sd_types_BleGapMasterId_DEFAULT NULL

#define sd_types_BleGapSignInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, csrk,              1)
#define sd_types_BleGapSignInfo_CALLBACK NULL
#define sd_types_BleGapSignInfo_DEFAULT NULL

#define sd_types_BleGapLescP256Pk_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, pk,                1)
#define sd_types_BleGapLescP256Pk_CALLBACK NULL
#define sd_types_BleGapLescP256Pk_DEFAULT NULL

#define sd_types_BleGapLescDhkey_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, key,               1)
#define sd_types_BleGapLescDhkey_CALLBACK NULL
#define sd_types_BleGapLescDhkey_DEFAULT NULL

#define sd_types_BleGapLescOobData_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  addr,              1) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, r,                 2) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, c,                 3)
#define sd_types_BleGapLescOobData_CALLBACK NULL
#define sd_types_BleGapLescOobData_DEFAULT NULL
#define sd_types_BleGapLescOobData_addr_MSGTYPE sd_types_BleGapAddr

#define sd_types_BleGapConnSec_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sec_mode,          1) \
X(a, STATIC,   SINGULAR, UINT32,   encr_key_size,     2)
#define sd_types_BleGapConnSec_CALLBACK NULL
#define sd_types_BleGapConnSec_DEFAULT NULL
#define sd_types_BleGapConnSec_sec_mode_MSGTYPE sd_types_BleGapConnSecMode

#define sd_types_BleGapEncKey_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  enc_info,          1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  master_id,         2)
#define sd_types_BleGapEncKey_CALLBACK NULL
#define sd_types_BleGapEncKey_DEFAULT NULL
#define sd_types_BleGapEncKey_enc_info_MSGTYPE sd_types_BleGapEncInfo
#define sd_types_BleGapEncKey_master_id_MSGTYPE sd_types_BleGapMasterId

#define sd_types_BleGapIdKey_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  id_info,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  id_addr_info,      2)
#define sd_types_BleGapIdKey_CALLBACK NULL
#define sd_types_BleGapIdKey_DEFAULT NULL
#define sd_types_BleGapIdKey_id_info_MSGTYPE sd_types_BleGapIrk
#define sd_types_BleGapIdKey_id_addr_info_MSGTYPE sd_types_BleGapAddr

#define sd_types_BleGapSecKeys_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  enc_key,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  id_key,            2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sign_key,          3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pk,                4)
#define sd_types_BleGapSecKeys_CALLBACK NULL
#define sd_types_BleGapSecKeys_DEFAULT NULL
#define sd_types_BleGapSecKeys_enc_key_MSGTYPE sd_types_BleGapEncKey
#define sd_types_BleGapSecKeys_id_key_MSGTYPE sd_types_BleGapIdKey
#define sd_types_BleGapSecKeys_sign_key_MSGTYPE sd_types_BleGapSignInfo
#define sd_types_BleGapSecKeys_pk_MSGTYPE sd_types_BleGapLescP256Pk

#define sd_types_BleGapSecKeyset_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  keys_own,          1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  keys_peer,         2)
#define sd_types_BleGapSecKeyset_CALLBACK NULL
#define sd_types_BleGapSecKeyset_DEFAULT NULL
#define sd_types_BleGapSecKeyset_keys_own_MSGTYPE sd_types_BleGapSecKeys
#define sd_types_BleGapSecKeyset_keys_peer_MSGTYPE sd_types_BleGapSecKeys

#define sd_types_BleGapDataLengthParams_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   max_tx_octets,     1) \
X(a, STATIC,   SINGULAR, UINT32,   max_rx_octets,     2) \
X(a, STATIC,   SINGULAR, UINT32,   max_tx_time_us,    3) \
X(a, STATIC,   SINGULAR, UINT32,   max_rx_time_us,    4)
#define sd_types_BleGapDataLengthParams_CALLBACK NULL
#define sd_types_BleGapDataLengthParams_DEFAULT NULL

#define sd_types_BleGapDataLengthLimitation_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   tx_payload_limited_octets,   1) \
X(a, STATIC,   SINGULAR, UINT32,   rx_payload_limited_octets,   2) \
X(a, STATIC,   SINGULAR, UINT32,   tx_rx_time_limited_us,   3)
#define sd_types_BleGapDataLengthLimitation_CALLBACK NULL
#define sd_types_BleGapDataLengthLimitation_DEFAULT NULL

#define sd_types_BleGapConnEventTrigger_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ppi_ch_id,         1) \
X(a, STATIC,   SINGULAR, UINT32,   task_endpoint,     2) \
X(a, STATIC,   SINGULAR, UINT32,   conn_evt_counter_start,   3) \
X(a, STATIC,   SINGULAR, UINT32,   period_in_events,   4)
#define sd_types_BleGapConnEventTrigger_CALLBACK NULL
#define sd_types_BleGapConnEventTrigger_DEFAULT NULL

#define sd_types_BleUuid_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   uuid,              1) \
X(a, STATIC,   SINGULAR, UINT32,   type,              2)
#define sd_types_BleUuid_CALLBACK NULL
#define sd_types_BleUuid_DEFAULT NULL

#define sd_types_BleUuid128_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, uuid128,           1)
#define sd_types_BleUuid128_CALLBACK NULL
#define sd_types_BleUuid128_DEFAULT NULL

#define sd_types_BleGattCharProps_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     broadcast,         1) \
X(a, STATIC,   SINGULAR, BOOL,     read,              2) \
X(a, STATIC,   SINGULAR, BOOL,     write_wo_resp,     3) \
X(a, STATIC,   SINGULAR, BOOL,     write,             4) \
X(a, STATIC,   SINGULAR, BOOL,     notify,            5) \
X(a, STATIC,   SINGULAR, BOOL,     indicate,          6) \
X(a, STATIC,   SINGULAR, BOOL,     auth_signed_wr,    7)
#define sd_types_BleGattCharProps_CALLBACK NULL
#define sd_types_BleGattCharProps_DEFAULT NULL

#define sd_types_BleGattcHandleRange_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   start_handle,      1) \
X(a, STATIC,   SINGULAR, UINT32,   end_handle,        2)
#define sd_types_BleGattcHandleRange_CALLBACK NULL
#define sd_types_BleGattcHandleRange_DEFAULT NULL

#define sd_types_BleGattcWriteParams_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   write_op,          1) \
X(a, STATIC,   SINGULAR, UINT32,   flags,             2) \
X(a, STATIC,   SINGULAR, UINT32,   handle,            3) \
X(a, STATIC,   SINGULAR, UINT32,   offset,            4) \
X(a, STATIC,   SINGULAR, UINT32,   len,               5) \
X(a, STATIC,   SINGULAR, BYTES,    p_value,           6)
#define sd_types_BleGattcWriteParams_CALLBACK NULL
#define sd_types_BleGattcWriteParams_DEFAULT NULL

#define sd_types_BleGattcService_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  uuid,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  handle_range,      2)
#define sd_types_BleGattcService_CALLBACK NULL
#define sd_types_BleGattcService_DEFAULT NULL
#define sd_types_BleGattcService_uuid_MSGTYPE sd_types_BleUuid
#define sd_types_BleGattcService_handle_range_MSGTYPE sd_types_BleGattcHandleRange

#define sd_types_BleGattcInclude_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   handle,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  included_srvc,     2)
#define sd_types_BleGattcInclude_CALLBACK NULL
#define sd_types_BleGattcInclude_DEFAULT NULL
#define sd_types_BleGattcInclude_included_srvc_MSGTYPE sd_types_BleGattcService

#define sd_types_BleGattcChar_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  uuid,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  char_props,        2) \
X(a, STATIC,   SINGULAR, UINT32,   char_ext_props,    3) \
X(a, STATIC,   SINGULAR, UINT32,   handle_decl,       4) \
X(a, STATIC,   SINGULAR, UINT32,   handle_value,      5)
#define sd_types_BleGattcChar_CALLBACK NULL
#define sd_types_BleGattcChar_DEFAULT NULL
#define sd_types_BleGattcChar_uuid_MSGTYPE sd_types_BleUuid
#define sd_types_BleGattcChar_char_props_MSGTYPE sd_types_BleGattCharProps

#define sd_types_BleGattcDesc_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   handle,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  uuid,              2)
#define sd_types_BleGattcDesc_CALLBACK NULL
#define sd_types_BleGattcDesc_DEFAULT NULL
#define sd_types_BleGattcDesc_uuid_MSGTYPE sd_types_BleUuid

#define sd_types_BleGattcAttrInfo16_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   handle,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  uuid,              2)
#define sd_types_BleGattcAttrInfo16_CALLBACK NULL
#define sd_types_BleGattcAttrInfo16_DEFAULT NULL
#define sd_types_BleGattcAttrInfo16_uuid_MSGTYPE sd_types_BleUuid

#define sd_types_BleGattcAttrInfo128_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   handle,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  uuid,              2)
#define sd_types_BleGattcAttrInfo128_CALLBACK NULL
#define sd_types_BleGattcAttrInfo128_DEFAULT NULL
#define sd_types_BleGattcAttrInfo128_uuid_MSGTYPE sd_types_BleUuid128

#define sd_types_BleGattcHandleValue_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   handle,            1) \
X(a, STATIC,   SINGULAR, BYTES,    p_value,           2)
#define sd_types_BleGattcHandleValue_CALLBACK NULL
#define sd_types_BleGattcHandleValue_DEFAULT NULL

#define sd_types_BleGattsAttrMd_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  read_perm,         1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  write_perm,        2) \
X(a, STATIC,   SINGULAR, BOOL,     vlen,              3) \
X(a, STATIC,   SINGULAR, UENUM,    vloc,              4) \
X(a, STATIC,   SINGULAR, BOOL,     rd_auth,           5) \
X(a, STATIC,   SINGULAR, BOOL,     wr_auth,           6)
#define sd_types_BleGattsAttrMd_CALLBACK NULL
#define sd_types_BleGattsAttrMd_DEFAULT NULL
#define sd_types_BleGattsAttrMd_read_perm_MSGTYPE sd_types_BleGapConnSecMode
#define sd_types_BleGattsAttrMd_write_perm_MSGTYPE sd_types_BleGapConnSecMode

#define sd_types_BleGattsAttr_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  uuid,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  attr_md,           2) \
X(a, STATIC,   SINGULAR, UINT32,   init_len,          3) \
X(a, STATIC,   SINGULAR, UINT32,   init_offs,         4) \
X(a, STATIC,   SINGULAR, UINT32,   max_len,           5) \
X(a, STATIC,   SINGULAR, BYTES,    p_value,           6)
#define sd_types_BleGattsAttr_CALLBACK NULL
#define sd_types_BleGattsAttr_DEFAULT NULL
#define sd_types_BleGattsAttr_uuid_MSGTYPE sd_types_BleUuid
#define sd_types_BleGattsAttr_attr_md_MSGTYPE sd_types_BleGattsAttrMd

#define sd_types_BleGattsValue_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   len,               1) \
X(a, STATIC,   SINGULAR, UINT32,   offset,            2) \
X(a, STATIC,   SINGULAR, BYTES,    p_value,           3)
#define sd_types_BleGattsValue_CALLBACK NULL
#define sd_types_BleGattsValue_DEFAULT NULL

#define sd_types_BleGattsCharPf_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   format,            1) \
X(a, STATIC,   SINGULAR, SINT32,   exponent,          2) \
X(a, STATIC,   SINGULAR, UINT32,   unit,              3) \
X(a, STATIC,   SINGULAR, UINT32,   name_space,        4) \
X(a, STATIC,   SINGULAR, UINT32,   desc,              5)
#define sd_types_BleGattsCharPf_CALLBACK NULL
#define sd_types_BleGattsCharPf_DEFAULT NULL

#define sd_types_BleGattCharExtProps_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     reliable_wr,       1) \
X(a, STATIC,   SINGULAR, BOOL,     wr_aux,            2)
#define sd_types_BleGattCharExtProps_CALLBACK NULL
#define sd_types_BleGattCharExtProps_DEFAULT NULL

#define sd_types_BleGattsCharMd_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  char_props,        1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  char_ext_props,    2) \
X(a, STATIC,   SINGULAR, BYTES,    p_char_user_desc,   3) \
X(a, STATIC,   SINGULAR, UINT32,   char_user_desc_max_size,   4) \
X(a, STATIC,   SINGULAR, UINT32,   char_user_desc_size,   5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  char_pf,           6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  user_desc_md,      7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  cccd_md,           8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sccd_md,           9)
#define sd_types_BleGattsCharMd_CALLBACK NULL
#define sd_types_BleGattsCharMd_DEFAULT NULL
#define sd_types_BleGattsCharMd_char_props_MSGTYPE sd_types_BleGattCharProps
#define sd_types_BleGattsCharMd_char_ext_props_MSGTYPE sd_types_BleGattCharExtProps
#define sd_types_BleGattsCharMd_char_pf_MSGTYPE sd_types_BleGattsCharPf
#define sd_types_BleGattsCharMd_user_desc_md_MSGTYPE sd_types_BleGattsAttrMd
#define sd_types_BleGattsCharMd_cccd_md_MSGTYPE sd_types_BleGattsAttrMd
#define sd_types_BleGattsCharMd_sccd_md_MSGTYPE sd_types_BleGattsAttrMd

#define sd_types_BleGattsCharHandles_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   value_handle,      1) \
X(a, STATIC,   SINGULAR, UINT32,   user_desc_handle,   2) \
X(a, STATIC,   SINGULAR, UINT32,   cccd_handle,       3) \
X(a, STATIC,   SINGULAR, UINT32,   sccd_handle,       4)
#define sd_types_BleGattsCharHandles_CALLBACK NULL
#define sd_types_BleGattsCharHandles_DEFAULT NULL

#define sd_types_BleGattsHvxParams_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   handle,            1) \
X(a, STATIC,   SINGULAR, UINT32,   type,              2) \
X(a, STATIC,   SINGULAR, UINT32,   offset,            3) \
X(a, STATIC,   SINGULAR, UINT32,   len,               4) \
X(a, STATIC,   SINGULAR, BYTES,    p_data,            5)
#define sd_types_BleGattsHvxParams_CALLBACK NULL
#define sd_types_BleGattsHvxParams_DEFAULT NULL

#define sd_types_BleGapSecLevelsT_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     lv1,               1) \
X(a, STATIC,   SINGULAR, BOOL,     lv2,               2) \
X(a, STATIC,   SINGULAR, BOOL,     lv3,               3) \
X(a, STATIC,   SINGULAR, BOOL,     lv4,               4)
#define sd_types_BleGapSecLevelsT_CALLBACK NULL
#define sd_types_BleGapSecLevelsT_DEFAULT NULL

#define sd_types_BleGapAdvReportTypeT_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     connectable,       1) \
X(a, STATIC,   SINGULAR, BOOL,     scannable,         2) \
X(a, STATIC,   SINGULAR, BOOL,     directed,          3) \
X(a, STATIC,   SINGULAR, BOOL,     scan_response,     4) \
X(a, STATIC,   SINGULAR, BOOL,     extended_pdu,      5) \
X(a, STATIC,   SINGULAR, UENUM,    status,            6) \
X(a, STATIC,   SINGULAR, UINT32,   reserved,          7)
#define sd_types_BleGapAdvReportTypeT_CALLBACK NULL
#define sd_types_BleGapAdvReportTypeT_DEFAULT NULL

#define sd_types_BleGapAuxPointer_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   aux_offset,        1) \
X(a, STATIC,   SINGULAR, UENUM,    aux_phy,           2)
#define sd_types_BleGapAuxPointer_CALLBACK NULL
#define sd_types_BleGapAuxPointer_DEFAULT NULL

#define sd_types_BleGattsAuthorizeParams_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   gatt_status,       1) \
X(a, STATIC,   SINGULAR, BOOL,     update,            2) \
X(a, STATIC,   SINGULAR, UINT32,   offset,            3) \
X(a, STATIC,   SINGULAR, UINT32,   len,               4) \
X(a, STATIC,   SINGULAR, BYTES,    p_data,            5)
#define sd_types_BleGattsAuthorizeParams_CALLBACK NULL
#define sd_types_BleGattsAuthorizeParams_DEFAULT NULL

#define sd_types_BleGattsRwAuthorizeReplyParams_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   type,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  read,              2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  write,             3)
#define sd_types_BleGattsRwAuthorizeReplyParams_CALLBACK NULL
#define sd_types_BleGattsRwAuthorizeReplyParams_DEFAULT NULL
#define sd_types_BleGattsRwAuthorizeReplyParams_read_MSGTYPE sd_types_BleGattsAuthorizeParams
#define sd_types_BleGattsRwAuthorizeReplyParams_write_MSGTYPE sd_types_BleGattsAuthorizeParams

extern const pb_msgdesc_t sd_types_BleGapAddr_msg;
extern const pb_msgdesc_t sd_types_BleGapConnParams_msg;
extern const pb_msgdesc_t sd_types_BleGapConnSecMode_msg;
extern const pb_msgdesc_t sd_types_BleGapIrk_msg;
extern const pb_msgdesc_t sd_types_BleGapChMask_msg;
extern const pb_msgdesc_t sd_types_BleGapAdvProperties_msg;
extern const pb_msgdesc_t sd_types_BleGapAdvParams_msg;
extern const pb_msgdesc_t sd_types_BleData_msg;
extern const pb_msgdesc_t sd_types_BleGapAdvData_msg;
extern const pb_msgdesc_t sd_types_BleGapScanParams_msg;
extern const pb_msgdesc_t sd_types_BleGapPrivacyParams_msg;
extern const pb_msgdesc_t sd_types_BleGapSecKdist_msg;
extern const pb_msgdesc_t sd_types_BleGapSecParams_msg;
extern const pb_msgdesc_t sd_types_BleGapEncInfo_msg;
extern const pb_msgdesc_t sd_types_BleGapMasterId_msg;
extern const pb_msgdesc_t sd_types_BleGapSignInfo_msg;
extern const pb_msgdesc_t sd_types_BleGapLescP256Pk_msg;
extern const pb_msgdesc_t sd_types_BleGapLescDhkey_msg;
extern const pb_msgdesc_t sd_types_BleGapLescOobData_msg;
extern const pb_msgdesc_t sd_types_BleGapConnSec_msg;
extern const pb_msgdesc_t sd_types_BleGapEncKey_msg;
extern const pb_msgdesc_t sd_types_BleGapIdKey_msg;
extern const pb_msgdesc_t sd_types_BleGapSecKeys_msg;
extern const pb_msgdesc_t sd_types_BleGapSecKeyset_msg;
extern const pb_msgdesc_t sd_types_BleGapDataLengthParams_msg;
extern const pb_msgdesc_t sd_types_BleGapDataLengthLimitation_msg;
extern const pb_msgdesc_t sd_types_BleGapConnEventTrigger_msg;
extern const pb_msgdesc_t sd_types_BleUuid_msg;
extern const pb_msgdesc_t sd_types_BleUuid128_msg;
extern const pb_msgdesc_t sd_types_BleGattCharProps_msg;
extern const pb_msgdesc_t sd_types_BleGattcHandleRange_msg;
extern const pb_msgdesc_t sd_types_BleGattcWriteParams_msg;
extern const pb_msgdesc_t sd_types_BleGattcService_msg;
extern const pb_msgdesc_t sd_types_BleGattcInclude_msg;
extern const pb_msgdesc_t sd_types_BleGattcChar_msg;
extern const pb_msgdesc_t sd_types_BleGattcDesc_msg;
extern const pb_msgdesc_t sd_types_BleGattcAttrInfo16_msg;
extern const pb_msgdesc_t sd_types_BleGattcAttrInfo128_msg;
extern const pb_msgdesc_t sd_types_BleGattcHandleValue_msg;
extern const pb_msgdesc_t sd_types_BleGattsAttrMd_msg;
extern const pb_msgdesc_t sd_types_BleGattsAttr_msg;
extern const pb_msgdesc_t sd_types_BleGattsValue_msg;
extern const pb_msgdesc_t sd_types_BleGattsCharPf_msg;
extern const pb_msgdesc_t sd_types_BleGattCharExtProps_msg;
extern const pb_msgdesc_t sd_types_BleGattsCharMd_msg;
extern const pb_msgdesc_t sd_types_BleGattsCharHandles_msg;
extern const pb_msgdesc_t sd_types_BleGattsHvxParams_msg;
extern const pb_msgdesc_t sd_types_BleGapSecLevelsT_msg;
extern const pb_msgdesc_t sd_types_BleGapAdvReportTypeT_msg;
extern const pb_msgdesc_t sd_types_BleGapAuxPointer_msg;
extern const pb_msgdesc_t sd_types_BleGattsAuthorizeParams_msg;
extern const pb_msgdesc_t sd_types_BleGattsRwAuthorizeReplyParams_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define sd_types_BleGapAddr_fields &sd_types_BleGapAddr_msg
#define sd_types_BleGapConnParams_fields &sd_types_BleGapConnParams_msg
#define sd_types_BleGapConnSecMode_fields &sd_types_BleGapConnSecMode_msg
#define sd_types_BleGapIrk_fields &sd_types_BleGapIrk_msg
#define sd_types_BleGapChMask_fields &sd_types_BleGapChMask_msg
#define sd_types_BleGapAdvProperties_fields &sd_types_BleGapAdvProperties_msg
#define sd_types_BleGapAdvParams_fields &sd_types_BleGapAdvParams_msg
#define sd_types_BleData_fields &sd_types_BleData_msg
#define sd_types_BleGapAdvData_fields &sd_types_BleGapAdvData_msg
#define sd_types_BleGapScanParams_fields &sd_types_BleGapScanParams_msg
#define sd_types_BleGapPrivacyParams_fields &sd_types_BleGapPrivacyParams_msg
#define sd_types_BleGapSecKdist_fields &sd_types_BleGapSecKdist_msg
#define sd_types_BleGapSecParams_fields &sd_types_BleGapSecParams_msg
#define sd_types_BleGapEncInfo_fields &sd_types_BleGapEncInfo_msg
#define sd_types_BleGapMasterId_fields &sd_types_BleGapMasterId_msg
#define sd_types_BleGapSignInfo_fields &sd_types_BleGapSignInfo_msg
#define sd_types_BleGapLescP256Pk_fields &sd_types_BleGapLescP256Pk_msg
#define sd_types_BleGapLescDhkey_fields &sd_types_BleGapLescDhkey_msg
#define sd_types_BleGapLescOobData_fields &sd_types_BleGapLescOobData_msg
#define sd_types_BleGapConnSec_fields &sd_types_BleGapConnSec_msg
#define sd_types_BleGapEncKey_fields &sd_types_BleGapEncKey_msg
#define sd_types_BleGapIdKey_fields &sd_types_BleGapIdKey_msg
#define sd_types_BleGapSecKeys_fields &sd_types_BleGapSecKeys_msg
#define sd_types_BleGapSecKeyset_fields &sd_types_BleGapSecKeyset_msg
#define sd_types_BleGapDataLengthParams_fields &sd_types_BleGapDataLengthParams_msg
#define sd_types_BleGapDataLengthLimitation_fields &sd_types_BleGapDataLengthLimitation_msg
#define sd_types_BleGapConnEventTrigger_fields &sd_types_BleGapConnEventTrigger_msg
#define sd_types_BleUuid_fields &sd_types_BleUuid_msg
#define sd_types_BleUuid128_fields &sd_types_BleUuid128_msg
#define sd_types_BleGattCharProps_fields &sd_types_BleGattCharProps_msg
#define sd_types_BleGattcHandleRange_fields &sd_types_BleGattcHandleRange_msg
#define sd_types_BleGattcWriteParams_fields &sd_types_BleGattcWriteParams_msg
#define sd_types_BleGattcService_fields &sd_types_BleGattcService_msg
#define sd_types_BleGattcInclude_fields &sd_types_BleGattcInclude_msg
#define sd_types_BleGattcChar_fields &sd_types_BleGattcChar_msg
#define sd_types_BleGattcDesc_fields &sd_types_BleGattcDesc_msg
#define sd_types_BleGattcAttrInfo16_fields &sd_types_BleGattcAttrInfo16_msg
#define sd_types_BleGattcAttrInfo128_fields &sd_types_BleGattcAttrInfo128_msg
#define sd_types_BleGattcHandleValue_fields &sd_types_BleGattcHandleValue_msg
#define sd_types_BleGattsAttrMd_fields &sd_types_BleGattsAttrMd_msg
#define sd_types_BleGattsAttr_fields &sd_types_BleGattsAttr_msg
#define sd_types_BleGattsValue_fields &sd_types_BleGattsValue_msg
#define sd_types_BleGattsCharPf_fields &sd_types_BleGattsCharPf_msg
#define sd_types_BleGattCharExtProps_fields &sd_types_BleGattCharExtProps_msg
#define sd_types_BleGattsCharMd_fields &sd_types_BleGattsCharMd_msg
#define sd_types_BleGattsCharHandles_fields &sd_types_BleGattsCharHandles_msg
#define sd_types_BleGattsHvxParams_fields &sd_types_BleGattsHvxParams_msg
#define sd_types_BleGapSecLevelsT_fields &sd_types_BleGapSecLevelsT_msg
#define sd_types_BleGapAdvReportTypeT_fields &sd_types_BleGapAdvReportTypeT_msg
#define sd_types_BleGapAuxPointer_fields &sd_types_BleGapAuxPointer_msg
#define sd_types_BleGattsAuthorizeParams_fields &sd_types_BleGattsAuthorizeParams_msg
#define sd_types_BleGattsRwAuthorizeReplyParams_fields &sd_types_BleGattsRwAuthorizeReplyParams_msg

/* Maximum encoded size of messages (where known) */
#define SD_TYPES_SOFTDEVICE_TYPES_PB_H_MAX_SIZE  sd_types_BleGattsRwAuthorizeReplyParams_size
#define sd_types_BleData_size                    262
#define sd_types_BleGapAddr_size                 12
#define sd_types_BleGapAdvData_size              530
#define sd_types_BleGapAdvParams_size            57
#define sd_types_BleGapAdvProperties_size        6
#define sd_types_BleGapAdvReportTypeT_size       16
#define sd_types_BleGapAuxPointer_size           7
#define sd_types_BleGapChMask_size               7
#define sd_types_BleGapConnEventTrigger_size     17
#define sd_types_BleGapConnParams_size           16
#define sd_types_BleGapConnSecMode_size          6
#define sd_types_BleGapConnSec_size              11
#define sd_types_BleGapDataLengthLimitation_size 12
#define sd_types_BleGapDataLengthParams_size     16
#define sd_types_BleGapEncInfo_size              25
#define sd_types_BleGapEncKey_size               43
#define sd_types_BleGapIdKey_size                34
#define sd_types_BleGapIrk_size                  18
#define sd_types_BleGapLescDhkey_size            34
#define sd_types_BleGapLescOobData_size          50
#define sd_types_BleGapLescP256Pk_size           66
#define sd_types_BleGapMasterId_size             14
#define sd_types_BleGapPrivacyParams_size        28
#define sd_types_BleGapScanParams_size           33
#define sd_types_BleGapSecKdist_size             8
#define sd_types_BleGapSecKeys_size              169
#define sd_types_BleGapSecKeyset_size            344
#define sd_types_BleGapSecLevelsT_size           8
#define sd_types_BleGapSecParams_size            38
#define sd_types_BleGapSignInfo_size             18
#define sd_types_BleGattCharExtProps_size        4
#define sd_types_BleGattCharProps_size           14
#define sd_types_BleGattcAttrInfo128_size        24
#define sd_types_BleGattcAttrInfo16_size         13
#define sd_types_BleGattcChar_size               36
#define sd_types_BleGattcDesc_size               13
#define sd_types_BleGattcHandleRange_size        8
#define sd_types_BleGattcHandleValue_size        519
#define sd_types_BleGattcInclude_size            25
#define sd_types_BleGattcService_size            19
#define sd_types_BleGattcWriteParams_size        533
#define sd_types_BleGattsAttrMd_size             24
#define sd_types_BleGattsAttr_size               562
#define sd_types_BleGattsAuthorizeParams_size    529
#define sd_types_BleGattsCharHandles_size        16
#define sd_types_BleGattsCharMd_size             642
#define sd_types_BleGattsCharPf_size             17
#define sd_types_BleGattsHvxParams_size          530
#define sd_types_BleGattsRwAuthorizeReplyParams_size 1067
#define sd_types_BleGattsValue_size              523
#define sd_types_BleUuid128_size                 18
#define sd_types_BleUuid_size                    7

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
