/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SD_SOFTDEVICE_GATTC_PB_H_INCLUDED
#define PB_SD_SOFTDEVICE_GATTC_PB_H_INCLUDED
#include "nanopb/pb.h"
#include "protocol/softdevice_types.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* SoftDevice GATTC command messages */
typedef struct _sd_GattcPrimaryServicesDiscoverCmd {
    uint16_t conn_handle;
    uint16_t start_handle;
    bool has_srvc_uuid;
    sd_types_BleUuid srvc_uuid; /* Optional */
} sd_GattcPrimaryServicesDiscoverCmd;

typedef struct _sd_GattcRelationshipsDiscoverCmd {
    uint16_t conn_handle;
    bool has_handle_range;
    sd_types_BleGattcHandleRange handle_range;
} sd_GattcRelationshipsDiscoverCmd;

typedef struct _sd_GattcCharacteristicsDiscoverCmd {
    uint16_t conn_handle;
    bool has_handle_range;
    sd_types_BleGattcHandleRange handle_range;
} sd_GattcCharacteristicsDiscoverCmd;

typedef struct _sd_GattcDescriptorsDiscoverCmd {
    uint16_t conn_handle;
    bool has_handle_range;
    sd_types_BleGattcHandleRange handle_range;
} sd_GattcDescriptorsDiscoverCmd;

typedef struct _sd_GattcAttrInfoDiscoverCmd {
    uint16_t conn_handle;
    bool has_handle_range;
    sd_types_BleGattcHandleRange handle_range;
} sd_GattcAttrInfoDiscoverCmd;

typedef struct _sd_GattcCharValueByUuidReadCmd {
    uint16_t conn_handle;
    bool has_uuid;
    sd_types_BleUuid uuid; /* Optional */
    bool has_handle_range;
    sd_types_BleGattcHandleRange handle_range;
} sd_GattcCharValueByUuidReadCmd;

typedef struct _sd_GattcReadCmd {
    uint16_t conn_handle;
    uint16_t handle;
    uint16_t offset;
} sd_GattcReadCmd;

typedef struct _sd_GattcCharValuesReadCmd {
    uint16_t conn_handle;
    pb_callback_t handles; /* BLE_GATTC_READ_MAX_HANDLES = 8 */
    uint8_t handle_count;
} sd_GattcCharValuesReadCmd;

typedef struct _sd_GattcWriteCmd {
    uint16_t conn_handle;
    bool has_write_params;
    sd_types_BleGattcWriteParams write_params;
} sd_GattcWriteCmd;

typedef struct _sd_GattcHvConfirmCmd {
    uint16_t conn_handle;
    uint16_t handle;
} sd_GattcHvConfirmCmd;

typedef struct _sd_GattcExchangeMtuRequestCmd {
    uint16_t conn_handle;
    uint16_t client_rx_mtu;
} sd_GattcExchangeMtuRequestCmd;

/* SoftDevice GATTC response messages */
typedef struct _sd_GattcPrimaryServicesDiscoverRsp {
    uint32_t ret_code;
} sd_GattcPrimaryServicesDiscoverRsp;

typedef struct _sd_GattcRelationshipsDiscoverRsp {
    uint32_t ret_code;
} sd_GattcRelationshipsDiscoverRsp;

typedef struct _sd_GattcCharacteristicsDiscoverRsp {
    uint32_t ret_code;
} sd_GattcCharacteristicsDiscoverRsp;

typedef struct _sd_GattcDescriptorsDiscoverRsp {
    uint32_t ret_code;
} sd_GattcDescriptorsDiscoverRsp;

typedef struct _sd_GattcAttrInfoDiscoverRsp {
    uint32_t ret_code;
} sd_GattcAttrInfoDiscoverRsp;

typedef struct _sd_GattcCharValueByUuidReadRsp {
    uint32_t ret_code;
} sd_GattcCharValueByUuidReadRsp;

typedef struct _sd_GattcReadRsp {
    uint32_t ret_code;
} sd_GattcReadRsp;

typedef struct _sd_GattcCharValuesReadRsp {
    uint32_t ret_code;
} sd_GattcCharValuesReadRsp;

typedef struct _sd_GattcWriteRsp {
    uint32_t ret_code;
} sd_GattcWriteRsp;

typedef struct _sd_GattcHvConfirmRsp {
    uint32_t ret_code;
} sd_GattcHvConfirmRsp;

typedef struct _sd_GattcExchangeMtuRequestRsp {
    uint32_t ret_code;
} sd_GattcExchangeMtuRequestRsp;

/* SoftDevice GATTC event messages */
typedef struct _sd_GattcEvtPrimSrvcDiscRsp {
    uint16_t gatt_status;
    uint16_t error_handle;
    uint16_t count;
    pb_callback_t services; /* Variable length */
} sd_GattcEvtPrimSrvcDiscRsp;

typedef struct _sd_GattcEvtRelDiscRsp {
    uint16_t gatt_status;
    uint16_t error_handle;
    uint16_t count;
    pb_callback_t includes; /* Variable length */
} sd_GattcEvtRelDiscRsp;

typedef struct _sd_GattcEvtCharDiscRsp {
    uint16_t gatt_status;
    uint16_t error_handle;
    uint16_t count;
    pb_callback_t chars; /* Variable length */
} sd_GattcEvtCharDiscRsp;

typedef struct _sd_GattcEvtDescDiscRsp {
    uint16_t gatt_status;
    uint16_t error_handle;
    uint16_t count;
    pb_callback_t descs; /* Variable length */
} sd_GattcEvtDescDiscRsp;

typedef struct _sd_GattcEvtAttrInfoDiscRsp {
    uint16_t gatt_status;
    uint16_t error_handle;
    uint16_t count;
    sd_types_BleGattcAttrInfoFormat format;
    pb_callback_t attr_info16; /* Variable length */
    pb_callback_t attr_info128; /* Variable length */
} sd_GattcEvtAttrInfoDiscRsp;

typedef PB_BYTES_ARRAY_T(512) sd_GattcEvtCharValByUuidReadRsp_handle_value_t;
typedef struct _sd_GattcEvtCharValByUuidReadRsp {
    uint16_t gatt_status;
    uint16_t error_handle;
    uint16_t count;
    uint16_t value_len;
    sd_GattcEvtCharValByUuidReadRsp_handle_value_t handle_value; /* Variable length data */
} sd_GattcEvtCharValByUuidReadRsp;

typedef PB_BYTES_ARRAY_T(512) sd_GattcEvtReadRsp_data_t;
typedef struct _sd_GattcEvtReadRsp {
    uint16_t gatt_status;
    uint16_t error_handle;
    uint16_t handle;
    uint16_t offset;
    uint16_t len;
    sd_GattcEvtReadRsp_data_t data; /* Variable length */
} sd_GattcEvtReadRsp;

typedef PB_BYTES_ARRAY_T(512) sd_GattcEvtCharValsReadRsp_values_t;
typedef struct _sd_GattcEvtCharValsReadRsp {
    uint16_t gatt_status;
    uint16_t error_handle;
    uint16_t len;
    sd_GattcEvtCharValsReadRsp_values_t values; /* Variable length */
} sd_GattcEvtCharValsReadRsp;

typedef PB_BYTES_ARRAY_T(512) sd_GattcEvtWriteRsp_data_t;
typedef struct _sd_GattcEvtWriteRsp {
    uint16_t gatt_status;
    uint16_t error_handle;
    uint16_t handle;
    sd_types_BleGattWriteOp write_op;
    uint16_t offset;
    uint16_t len;
    sd_GattcEvtWriteRsp_data_t data; /* Variable length */
} sd_GattcEvtWriteRsp;

typedef PB_BYTES_ARRAY_T(512) sd_GattcEvtHvx_data_t;
typedef struct _sd_GattcEvtHvx {
    uint16_t gatt_status;
    uint16_t error_handle;
    uint16_t handle;
    sd_types_BleGattHvxType type;
    uint16_t len;
    sd_GattcEvtHvx_data_t data; /* Variable length */
} sd_GattcEvtHvx;

typedef struct _sd_GattcEvtExchangeMtuRsp {
    uint16_t gatt_status;
    uint16_t error_handle;
    uint16_t server_rx_mtu;
} sd_GattcEvtExchangeMtuRsp;

typedef struct _sd_GattcEvtTimeout {
    uint16_t gatt_status;
    uint16_t error_handle;
    sd_types_BleGattTimeoutSrc src;
} sd_GattcEvtTimeout;

typedef struct _sd_GattcEvtWriteCmdTxComplete {
    uint16_t gatt_status;
    uint16_t error_handle;
    uint8_t count;
} sd_GattcEvtWriteCmdTxComplete;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define sd_GattcPrimaryServicesDiscoverCmd_init_default {0, 0, false, sd_types_BleUuid_init_default}
#define sd_GattcRelationshipsDiscoverCmd_init_default {0, false, sd_types_BleGattcHandleRange_init_default}
#define sd_GattcCharacteristicsDiscoverCmd_init_default {0, false, sd_types_BleGattcHandleRange_init_default}
#define sd_GattcDescriptorsDiscoverCmd_init_default {0, false, sd_types_BleGattcHandleRange_init_default}
#define sd_GattcAttrInfoDiscoverCmd_init_default {0, false, sd_types_BleGattcHandleRange_init_default}
#define sd_GattcCharValueByUuidReadCmd_init_default {0, false, sd_types_BleUuid_init_default, false, sd_types_BleGattcHandleRange_init_default}
#define sd_GattcReadCmd_init_default             {0, 0, 0}
#define sd_GattcCharValuesReadCmd_init_default   {0, {{NULL}, NULL}, 0}
#define sd_GattcWriteCmd_init_default            {0, false, sd_types_BleGattcWriteParams_init_default}
#define sd_GattcHvConfirmCmd_init_default        {0, 0}
#define sd_GattcExchangeMtuRequestCmd_init_default {0, 0}
#define sd_GattcPrimaryServicesDiscoverRsp_init_default {0}
#define sd_GattcRelationshipsDiscoverRsp_init_default {0}
#define sd_GattcCharacteristicsDiscoverRsp_init_default {0}
#define sd_GattcDescriptorsDiscoverRsp_init_default {0}
#define sd_GattcAttrInfoDiscoverRsp_init_default {0}
#define sd_GattcCharValueByUuidReadRsp_init_default {0}
#define sd_GattcReadRsp_init_default             {0}
#define sd_GattcCharValuesReadRsp_init_default   {0}
#define sd_GattcWriteRsp_init_default            {0}
#define sd_GattcHvConfirmRsp_init_default        {0}
#define sd_GattcExchangeMtuRequestRsp_init_default {0}
#define sd_GattcEvtPrimSrvcDiscRsp_init_default  {0, 0, 0, {{NULL}, NULL}}
#define sd_GattcEvtRelDiscRsp_init_default       {0, 0, 0, {{NULL}, NULL}}
#define sd_GattcEvtCharDiscRsp_init_default      {0, 0, 0, {{NULL}, NULL}}
#define sd_GattcEvtDescDiscRsp_init_default      {0, 0, 0, {{NULL}, NULL}}
#define sd_GattcEvtAttrInfoDiscRsp_init_default  {0, 0, 0, _sd_types_BleGattcAttrInfoFormat_MIN, {{NULL}, NULL}, {{NULL}, NULL}}
#define sd_GattcEvtCharValByUuidReadRsp_init_default {0, 0, 0, 0, {0, {0}}}
#define sd_GattcEvtReadRsp_init_default          {0, 0, 0, 0, 0, {0, {0}}}
#define sd_GattcEvtCharValsReadRsp_init_default  {0, 0, 0, {0, {0}}}
#define sd_GattcEvtWriteRsp_init_default         {0, 0, 0, _sd_types_BleGattWriteOp_MIN, 0, 0, {0, {0}}}
#define sd_GattcEvtHvx_init_default              {0, 0, 0, _sd_types_BleGattHvxType_MIN, 0, {0, {0}}}
#define sd_GattcEvtExchangeMtuRsp_init_default   {0, 0, 0}
#define sd_GattcEvtTimeout_init_default          {0, 0, _sd_types_BleGattTimeoutSrc_MIN}
#define sd_GattcEvtWriteCmdTxComplete_init_default {0, 0, 0}
#define sd_GattcPrimaryServicesDiscoverCmd_init_zero {0, 0, false, sd_types_BleUuid_init_zero}
#define sd_GattcRelationshipsDiscoverCmd_init_zero {0, false, sd_types_BleGattcHandleRange_init_zero}
#define sd_GattcCharacteristicsDiscoverCmd_init_zero {0, false, sd_types_BleGattcHandleRange_init_zero}
#define sd_GattcDescriptorsDiscoverCmd_init_zero {0, false, sd_types_BleGattcHandleRange_init_zero}
#define sd_GattcAttrInfoDiscoverCmd_init_zero    {0, false, sd_types_BleGattcHandleRange_init_zero}
#define sd_GattcCharValueByUuidReadCmd_init_zero {0, false, sd_types_BleUuid_init_zero, false, sd_types_BleGattcHandleRange_init_zero}
#define sd_GattcReadCmd_init_zero                {0, 0, 0}
#define sd_GattcCharValuesReadCmd_init_zero      {0, {{NULL}, NULL}, 0}
#define sd_GattcWriteCmd_init_zero               {0, false, sd_types_BleGattcWriteParams_init_zero}
#define sd_GattcHvConfirmCmd_init_zero           {0, 0}
#define sd_GattcExchangeMtuRequestCmd_init_zero  {0, 0}
#define sd_GattcPrimaryServicesDiscoverRsp_init_zero {0}
#define sd_GattcRelationshipsDiscoverRsp_init_zero {0}
#define sd_GattcCharacteristicsDiscoverRsp_init_zero {0}
#define sd_GattcDescriptorsDiscoverRsp_init_zero {0}
#define sd_GattcAttrInfoDiscoverRsp_init_zero    {0}
#define sd_GattcCharValueByUuidReadRsp_init_zero {0}
#define sd_GattcReadRsp_init_zero                {0}
#define sd_GattcCharValuesReadRsp_init_zero      {0}
#define sd_GattcWriteRsp_init_zero               {0}
#define sd_GattcHvConfirmRsp_init_zero           {0}
#define sd_GattcExchangeMtuRequestRsp_init_zero  {0}
#define sd_GattcEvtPrimSrvcDiscRsp_init_zero     {0, 0, 0, {{NULL}, NULL}}
#define sd_GattcEvtRelDiscRsp_init_zero          {0, 0, 0, {{NULL}, NULL}}
#define sd_GattcEvtCharDiscRsp_init_zero         {0, 0, 0, {{NULL}, NULL}}
#define sd_GattcEvtDescDiscRsp_init_zero         {0, 0, 0, {{NULL}, NULL}}
#define sd_GattcEvtAttrInfoDiscRsp_init_zero     {0, 0, 0, _sd_types_BleGattcAttrInfoFormat_MIN, {{NULL}, NULL}, {{NULL}, NULL}}
#define sd_GattcEvtCharValByUuidReadRsp_init_zero {0, 0, 0, 0, {0, {0}}}
#define sd_GattcEvtReadRsp_init_zero             {0, 0, 0, 0, 0, {0, {0}}}
#define sd_GattcEvtCharValsReadRsp_init_zero     {0, 0, 0, {0, {0}}}
#define sd_GattcEvtWriteRsp_init_zero            {0, 0, 0, _sd_types_BleGattWriteOp_MIN, 0, 0, {0, {0}}}
#define sd_GattcEvtHvx_init_zero                 {0, 0, 0, _sd_types_BleGattHvxType_MIN, 0, {0, {0}}}
#define sd_GattcEvtExchangeMtuRsp_init_zero      {0, 0, 0}
#define sd_GattcEvtTimeout_init_zero             {0, 0, _sd_types_BleGattTimeoutSrc_MIN}
#define sd_GattcEvtWriteCmdTxComplete_init_zero  {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define sd_GattcPrimaryServicesDiscoverCmd_conn_handle_tag 1
#define sd_GattcPrimaryServicesDiscoverCmd_start_handle_tag 2
#define sd_GattcPrimaryServicesDiscoverCmd_srvc_uuid_tag 3
#define sd_GattcRelationshipsDiscoverCmd_conn_handle_tag 1
#define sd_GattcRelationshipsDiscoverCmd_handle_range_tag 2
#define sd_GattcCharacteristicsDiscoverCmd_conn_handle_tag 1
#define sd_GattcCharacteristicsDiscoverCmd_handle_range_tag 2
#define sd_GattcDescriptorsDiscoverCmd_conn_handle_tag 1
#define sd_GattcDescriptorsDiscoverCmd_handle_range_tag 2
#define sd_GattcAttrInfoDiscoverCmd_conn_handle_tag 1
#define sd_GattcAttrInfoDiscoverCmd_handle_range_tag 2
#define sd_GattcCharValueByUuidReadCmd_conn_handle_tag 1
#define sd_GattcCharValueByUuidReadCmd_uuid_tag  2
#define sd_GattcCharValueByUuidReadCmd_handle_range_tag 3
#define sd_GattcReadCmd_conn_handle_tag          1
#define sd_GattcReadCmd_handle_tag               2
#define sd_GattcReadCmd_offset_tag               3
#define sd_GattcCharValuesReadCmd_conn_handle_tag 1
#define sd_GattcCharValuesReadCmd_handles_tag    2
#define sd_GattcCharValuesReadCmd_handle_count_tag 3
#define sd_GattcWriteCmd_conn_handle_tag         1
#define sd_GattcWriteCmd_write_params_tag        2
#define sd_GattcHvConfirmCmd_conn_handle_tag     1
#define sd_GattcHvConfirmCmd_handle_tag          2
#define sd_GattcExchangeMtuRequestCmd_conn_handle_tag 1
#define sd_GattcExchangeMtuRequestCmd_client_rx_mtu_tag 2
#define sd_GattcPrimaryServicesDiscoverRsp_ret_code_tag 1
#define sd_GattcRelationshipsDiscoverRsp_ret_code_tag 1
#define sd_GattcCharacteristicsDiscoverRsp_ret_code_tag 1
#define sd_GattcDescriptorsDiscoverRsp_ret_code_tag 1
#define sd_GattcAttrInfoDiscoverRsp_ret_code_tag 1
#define sd_GattcCharValueByUuidReadRsp_ret_code_tag 1
#define sd_GattcReadRsp_ret_code_tag             1
#define sd_GattcCharValuesReadRsp_ret_code_tag   1
#define sd_GattcWriteRsp_ret_code_tag            1
#define sd_GattcHvConfirmRsp_ret_code_tag        1
#define sd_GattcExchangeMtuRequestRsp_ret_code_tag 1
#define sd_GattcEvtPrimSrvcDiscRsp_gatt_status_tag 1
#define sd_GattcEvtPrimSrvcDiscRsp_error_handle_tag 2
#define sd_GattcEvtPrimSrvcDiscRsp_count_tag     3
#define sd_GattcEvtPrimSrvcDiscRsp_services_tag  4
#define sd_GattcEvtRelDiscRsp_gatt_status_tag    1
#define sd_GattcEvtRelDiscRsp_error_handle_tag   2
#define sd_GattcEvtRelDiscRsp_count_tag          3
#define sd_GattcEvtRelDiscRsp_includes_tag       4
#define sd_GattcEvtCharDiscRsp_gatt_status_tag   1
#define sd_GattcEvtCharDiscRsp_error_handle_tag  2
#define sd_GattcEvtCharDiscRsp_count_tag         3
#define sd_GattcEvtCharDiscRsp_chars_tag         4
#define sd_GattcEvtDescDiscRsp_gatt_status_tag   1
#define sd_GattcEvtDescDiscRsp_error_handle_tag  2
#define sd_GattcEvtDescDiscRsp_count_tag         3
#define sd_GattcEvtDescDiscRsp_descs_tag         4
#define sd_GattcEvtAttrInfoDiscRsp_gatt_status_tag 1
#define sd_GattcEvtAttrInfoDiscRsp_error_handle_tag 2
#define sd_GattcEvtAttrInfoDiscRsp_count_tag     3
#define sd_GattcEvtAttrInfoDiscRsp_format_tag    4
#define sd_GattcEvtAttrInfoDiscRsp_attr_info16_tag 5
#define sd_GattcEvtAttrInfoDiscRsp_attr_info128_tag 6
#define sd_GattcEvtCharValByUuidReadRsp_gatt_status_tag 1
#define sd_GattcEvtCharValByUuidReadRsp_error_handle_tag 2
#define sd_GattcEvtCharValByUuidReadRsp_count_tag 3
#define sd_GattcEvtCharValByUuidReadRsp_value_len_tag 4
#define sd_GattcEvtCharValByUuidReadRsp_handle_value_tag 5
#define sd_GattcEvtReadRsp_gatt_status_tag       1
#define sd_GattcEvtReadRsp_error_handle_tag      2
#define sd_GattcEvtReadRsp_handle_tag            3
#define sd_GattcEvtReadRsp_offset_tag            4
#define sd_GattcEvtReadRsp_len_tag               5
#define sd_GattcEvtReadRsp_data_tag              6
#define sd_GattcEvtCharValsReadRsp_gatt_status_tag 1
#define sd_GattcEvtCharValsReadRsp_error_handle_tag 2
#define sd_GattcEvtCharValsReadRsp_len_tag       3
#define sd_GattcEvtCharValsReadRsp_values_tag    4
#define sd_GattcEvtWriteRsp_gatt_status_tag      1
#define sd_GattcEvtWriteRsp_error_handle_tag     2
#define sd_GattcEvtWriteRsp_handle_tag           3
#define sd_GattcEvtWriteRsp_write_op_tag         4
#define sd_GattcEvtWriteRsp_offset_tag           5
#define sd_GattcEvtWriteRsp_len_tag              6
#define sd_GattcEvtWriteRsp_data_tag             7
#define sd_GattcEvtHvx_gatt_status_tag           1
#define sd_GattcEvtHvx_error_handle_tag          2
#define sd_GattcEvtHvx_handle_tag                3
#define sd_GattcEvtHvx_type_tag                  4
#define sd_GattcEvtHvx_len_tag                   5
#define sd_GattcEvtHvx_data_tag                  6
#define sd_GattcEvtExchangeMtuRsp_gatt_status_tag 1
#define sd_GattcEvtExchangeMtuRsp_error_handle_tag 2
#define sd_GattcEvtExchangeMtuRsp_server_rx_mtu_tag 3
#define sd_GattcEvtTimeout_gatt_status_tag       1
#define sd_GattcEvtTimeout_error_handle_tag      2
#define sd_GattcEvtTimeout_src_tag               3
#define sd_GattcEvtWriteCmdTxComplete_gatt_status_tag 1
#define sd_GattcEvtWriteCmdTxComplete_error_handle_tag 2
#define sd_GattcEvtWriteCmdTxComplete_count_tag  3

/* Struct field encoding specification for nanopb */
#define sd_GattcPrimaryServicesDiscoverCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   conn_handle,       1) \
X(a, STATIC,   SINGULAR, UINT32,   start_handle,      2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  srvc_uuid,         3)
#define sd_GattcPrimaryServicesDiscoverCmd_CALLBACK NULL
#define sd_GattcPrimaryServicesDiscoverCmd_DEFAULT NULL
#define sd_GattcPrimaryServicesDiscoverCmd_srvc_uuid_MSGTYPE sd_types_BleUuid

#define sd_GattcRelationshipsDiscoverCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   conn_handle,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  handle_range,      2)
#define sd_GattcRelationshipsDiscoverCmd_CALLBACK NULL
#define sd_GattcRelationshipsDiscoverCmd_DEFAULT NULL
#define sd_GattcRelationshipsDiscoverCmd_handle_range_MSGTYPE sd_types_BleGattcHandleRange

#define sd_GattcCharacteristicsDiscoverCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   conn_handle,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  handle_range,      2)
#define sd_GattcCharacteristicsDiscoverCmd_CALLBACK NULL
#define sd_GattcCharacteristicsDiscoverCmd_DEFAULT NULL
#define sd_GattcCharacteristicsDiscoverCmd_handle_range_MSGTYPE sd_types_BleGattcHandleRange

#define sd_GattcDescriptorsDiscoverCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   conn_handle,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  handle_range,      2)
#define sd_GattcDescriptorsDiscoverCmd_CALLBACK NULL
#define sd_GattcDescriptorsDiscoverCmd_DEFAULT NULL
#define sd_GattcDescriptorsDiscoverCmd_handle_range_MSGTYPE sd_types_BleGattcHandleRange

#define sd_GattcAttrInfoDiscoverCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   conn_handle,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  handle_range,      2)
#define sd_GattcAttrInfoDiscoverCmd_CALLBACK NULL
#define sd_GattcAttrInfoDiscoverCmd_DEFAULT NULL
#define sd_GattcAttrInfoDiscoverCmd_handle_range_MSGTYPE sd_types_BleGattcHandleRange

#define sd_GattcCharValueByUuidReadCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   conn_handle,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  uuid,              2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  handle_range,      3)
#define sd_GattcCharValueByUuidReadCmd_CALLBACK NULL
#define sd_GattcCharValueByUuidReadCmd_DEFAULT NULL
#define sd_GattcCharValueByUuidReadCmd_uuid_MSGTYPE sd_types_BleUuid
#define sd_GattcCharValueByUuidReadCmd_handle_range_MSGTYPE sd_types_BleGattcHandleRange

#define sd_GattcReadCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   conn_handle,       1) \
X(a, STATIC,   SINGULAR, UINT32,   handle,            2) \
X(a, STATIC,   SINGULAR, UINT32,   offset,            3)
#define sd_GattcReadCmd_CALLBACK NULL
#define sd_GattcReadCmd_DEFAULT NULL

#define sd_GattcCharValuesReadCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   conn_handle,       1) \
X(a, CALLBACK, REPEATED, UINT32,   handles,           2) \
X(a, STATIC,   SINGULAR, UINT32,   handle_count,      3)
#define sd_GattcCharValuesReadCmd_CALLBACK pb_default_field_callback
#define sd_GattcCharValuesReadCmd_DEFAULT NULL

#define sd_GattcWriteCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   conn_handle,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  write_params,      2)
#define sd_GattcWriteCmd_CALLBACK NULL
#define sd_GattcWriteCmd_DEFAULT NULL
#define sd_GattcWriteCmd_write_params_MSGTYPE sd_types_BleGattcWriteParams

#define sd_GattcHvConfirmCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   conn_handle,       1) \
X(a, STATIC,   SINGULAR, UINT32,   handle,            2)
#define sd_GattcHvConfirmCmd_CALLBACK NULL
#define sd_GattcHvConfirmCmd_DEFAULT NULL

#define sd_GattcExchangeMtuRequestCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   conn_handle,       1) \
X(a, STATIC,   SINGULAR, UINT32,   client_rx_mtu,     2)
#define sd_GattcExchangeMtuRequestCmd_CALLBACK NULL
#define sd_GattcExchangeMtuRequestCmd_DEFAULT NULL

#define sd_GattcPrimaryServicesDiscoverRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GattcPrimaryServicesDiscoverRsp_CALLBACK NULL
#define sd_GattcPrimaryServicesDiscoverRsp_DEFAULT NULL

#define sd_GattcRelationshipsDiscoverRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GattcRelationshipsDiscoverRsp_CALLBACK NULL
#define sd_GattcRelationshipsDiscoverRsp_DEFAULT NULL

#define sd_GattcCharacteristicsDiscoverRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GattcCharacteristicsDiscoverRsp_CALLBACK NULL
#define sd_GattcCharacteristicsDiscoverRsp_DEFAULT NULL

#define sd_GattcDescriptorsDiscoverRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GattcDescriptorsDiscoverRsp_CALLBACK NULL
#define sd_GattcDescriptorsDiscoverRsp_DEFAULT NULL

#define sd_GattcAttrInfoDiscoverRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GattcAttrInfoDiscoverRsp_CALLBACK NULL
#define sd_GattcAttrInfoDiscoverRsp_DEFAULT NULL

#define sd_GattcCharValueByUuidReadRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GattcCharValueByUuidReadRsp_CALLBACK NULL
#define sd_GattcCharValueByUuidReadRsp_DEFAULT NULL

#define sd_GattcReadRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GattcReadRsp_CALLBACK NULL
#define sd_GattcReadRsp_DEFAULT NULL

#define sd_GattcCharValuesReadRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GattcCharValuesReadRsp_CALLBACK NULL
#define sd_GattcCharValuesReadRsp_DEFAULT NULL

#define sd_GattcWriteRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GattcWriteRsp_CALLBACK NULL
#define sd_GattcWriteRsp_DEFAULT NULL

#define sd_GattcHvConfirmRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GattcHvConfirmRsp_CALLBACK NULL
#define sd_GattcHvConfirmRsp_DEFAULT NULL

#define sd_GattcExchangeMtuRequestRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ret_code,          1)
#define sd_GattcExchangeMtuRequestRsp_CALLBACK NULL
#define sd_GattcExchangeMtuRequestRsp_DEFAULT NULL

#define sd_GattcEvtPrimSrvcDiscRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   gatt_status,       1) \
X(a, STATIC,   SINGULAR, UINT32,   error_handle,      2) \
X(a, STATIC,   SINGULAR, UINT32,   count,             3) \
X(a, CALLBACK, REPEATED, MESSAGE,  services,          4)
#define sd_GattcEvtPrimSrvcDiscRsp_CALLBACK pb_default_field_callback
#define sd_GattcEvtPrimSrvcDiscRsp_DEFAULT NULL
#define sd_GattcEvtPrimSrvcDiscRsp_services_MSGTYPE sd_types_BleGattcService

#define sd_GattcEvtRelDiscRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   gatt_status,       1) \
X(a, STATIC,   SINGULAR, UINT32,   error_handle,      2) \
X(a, STATIC,   SINGULAR, UINT32,   count,             3) \
X(a, CALLBACK, REPEATED, MESSAGE,  includes,          4)
#define sd_GattcEvtRelDiscRsp_CALLBACK pb_default_field_callback
#define sd_GattcEvtRelDiscRsp_DEFAULT NULL
#define sd_GattcEvtRelDiscRsp_includes_MSGTYPE sd_types_BleGattcInclude

#define sd_GattcEvtCharDiscRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   gatt_status,       1) \
X(a, STATIC,   SINGULAR, UINT32,   error_handle,      2) \
X(a, STATIC,   SINGULAR, UINT32,   count,             3) \
X(a, CALLBACK, REPEATED, MESSAGE,  chars,             4)
#define sd_GattcEvtCharDiscRsp_CALLBACK pb_default_field_callback
#define sd_GattcEvtCharDiscRsp_DEFAULT NULL
#define sd_GattcEvtCharDiscRsp_chars_MSGTYPE sd_types_BleGattcChar

#define sd_GattcEvtDescDiscRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   gatt_status,       1) \
X(a, STATIC,   SINGULAR, UINT32,   error_handle,      2) \
X(a, STATIC,   SINGULAR, UINT32,   count,             3) \
X(a, CALLBACK, REPEATED, MESSAGE,  descs,             4)
#define sd_GattcEvtDescDiscRsp_CALLBACK pb_default_field_callback
#define sd_GattcEvtDescDiscRsp_DEFAULT NULL
#define sd_GattcEvtDescDiscRsp_descs_MSGTYPE sd_types_BleGattcDesc

#define sd_GattcEvtAttrInfoDiscRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   gatt_status,       1) \
X(a, STATIC,   SINGULAR, UINT32,   error_handle,      2) \
X(a, STATIC,   SINGULAR, UINT32,   count,             3) \
X(a, STATIC,   SINGULAR, UENUM,    format,            4) \
X(a, CALLBACK, REPEATED, MESSAGE,  attr_info16,       5) \
X(a, CALLBACK, REPEATED, MESSAGE,  attr_info128,      6)
#define sd_GattcEvtAttrInfoDiscRsp_CALLBACK pb_default_field_callback
#define sd_GattcEvtAttrInfoDiscRsp_DEFAULT NULL
#define sd_GattcEvtAttrInfoDiscRsp_attr_info16_MSGTYPE sd_types_BleGattcAttrInfo16
#define sd_GattcEvtAttrInfoDiscRsp_attr_info128_MSGTYPE sd_types_BleGattcAttrInfo128

#define sd_GattcEvtCharValByUuidReadRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   gatt_status,       1) \
X(a, STATIC,   SINGULAR, UINT32,   error_handle,      2) \
X(a, STATIC,   SINGULAR, UINT32,   count,             3) \
X(a, STATIC,   SINGULAR, UINT32,   value_len,         4) \
X(a, STATIC,   SINGULAR, BYTES,    handle_value,      5)
#define sd_GattcEvtCharValByUuidReadRsp_CALLBACK NULL
#define sd_GattcEvtCharValByUuidReadRsp_DEFAULT NULL

#define sd_GattcEvtReadRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   gatt_status,       1) \
X(a, STATIC,   SINGULAR, UINT32,   error_handle,      2) \
X(a, STATIC,   SINGULAR, UINT32,   handle,            3) \
X(a, STATIC,   SINGULAR, UINT32,   offset,            4) \
X(a, STATIC,   SINGULAR, UINT32,   len,               5) \
X(a, STATIC,   SINGULAR, BYTES,    data,              6)
#define sd_GattcEvtReadRsp_CALLBACK NULL
#define sd_GattcEvtReadRsp_DEFAULT NULL

#define sd_GattcEvtCharValsReadRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   gatt_status,       1) \
X(a, STATIC,   SINGULAR, UINT32,   error_handle,      2) \
X(a, STATIC,   SINGULAR, UINT32,   len,               3) \
X(a, STATIC,   SINGULAR, BYTES,    values,            4)
#define sd_GattcEvtCharValsReadRsp_CALLBACK NULL
#define sd_GattcEvtCharValsReadRsp_DEFAULT NULL

#define sd_GattcEvtWriteRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   gatt_status,       1) \
X(a, STATIC,   SINGULAR, UINT32,   error_handle,      2) \
X(a, STATIC,   SINGULAR, UINT32,   handle,            3) \
X(a, STATIC,   SINGULAR, UENUM,    write_op,          4) \
X(a, STATIC,   SINGULAR, UINT32,   offset,            5) \
X(a, STATIC,   SINGULAR, UINT32,   len,               6) \
X(a, STATIC,   SINGULAR, BYTES,    data,              7)
#define sd_GattcEvtWriteRsp_CALLBACK NULL
#define sd_GattcEvtWriteRsp_DEFAULT NULL

#define sd_GattcEvtHvx_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   gatt_status,       1) \
X(a, STATIC,   SINGULAR, UINT32,   error_handle,      2) \
X(a, STATIC,   SINGULAR, UINT32,   handle,            3) \
X(a, STATIC,   SINGULAR, UENUM,    type,              4) \
X(a, STATIC,   SINGULAR, UINT32,   len,               5) \
X(a, STATIC,   SINGULAR, BYTES,    data,              6)
#define sd_GattcEvtHvx_CALLBACK NULL
#define sd_GattcEvtHvx_DEFAULT NULL

#define sd_GattcEvtExchangeMtuRsp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   gatt_status,       1) \
X(a, STATIC,   SINGULAR, UINT32,   error_handle,      2) \
X(a, STATIC,   SINGULAR, UINT32,   server_rx_mtu,     3)
#define sd_GattcEvtExchangeMtuRsp_CALLBACK NULL
#define sd_GattcEvtExchangeMtuRsp_DEFAULT NULL

#define sd_GattcEvtTimeout_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   gatt_status,       1) \
X(a, STATIC,   SINGULAR, UINT32,   error_handle,      2) \
X(a, STATIC,   SINGULAR, UENUM,    src,               3)
#define sd_GattcEvtTimeout_CALLBACK NULL
#define sd_GattcEvtTimeout_DEFAULT NULL

#define sd_GattcEvtWriteCmdTxComplete_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   gatt_status,       1) \
X(a, STATIC,   SINGULAR, UINT32,   error_handle,      2) \
X(a, STATIC,   SINGULAR, UINT32,   count,             3)
#define sd_GattcEvtWriteCmdTxComplete_CALLBACK NULL
#define sd_GattcEvtWriteCmdTxComplete_DEFAULT NULL

extern const pb_msgdesc_t sd_GattcPrimaryServicesDiscoverCmd_msg;
extern const pb_msgdesc_t sd_GattcRelationshipsDiscoverCmd_msg;
extern const pb_msgdesc_t sd_GattcCharacteristicsDiscoverCmd_msg;
extern const pb_msgdesc_t sd_GattcDescriptorsDiscoverCmd_msg;
extern const pb_msgdesc_t sd_GattcAttrInfoDiscoverCmd_msg;
extern const pb_msgdesc_t sd_GattcCharValueByUuidReadCmd_msg;
extern const pb_msgdesc_t sd_GattcReadCmd_msg;
extern const pb_msgdesc_t sd_GattcCharValuesReadCmd_msg;
extern const pb_msgdesc_t sd_GattcWriteCmd_msg;
extern const pb_msgdesc_t sd_GattcHvConfirmCmd_msg;
extern const pb_msgdesc_t sd_GattcExchangeMtuRequestCmd_msg;
extern const pb_msgdesc_t sd_GattcPrimaryServicesDiscoverRsp_msg;
extern const pb_msgdesc_t sd_GattcRelationshipsDiscoverRsp_msg;
extern const pb_msgdesc_t sd_GattcCharacteristicsDiscoverRsp_msg;
extern const pb_msgdesc_t sd_GattcDescriptorsDiscoverRsp_msg;
extern const pb_msgdesc_t sd_GattcAttrInfoDiscoverRsp_msg;
extern const pb_msgdesc_t sd_GattcCharValueByUuidReadRsp_msg;
extern const pb_msgdesc_t sd_GattcReadRsp_msg;
extern const pb_msgdesc_t sd_GattcCharValuesReadRsp_msg;
extern const pb_msgdesc_t sd_GattcWriteRsp_msg;
extern const pb_msgdesc_t sd_GattcHvConfirmRsp_msg;
extern const pb_msgdesc_t sd_GattcExchangeMtuRequestRsp_msg;
extern const pb_msgdesc_t sd_GattcEvtPrimSrvcDiscRsp_msg;
extern const pb_msgdesc_t sd_GattcEvtRelDiscRsp_msg;
extern const pb_msgdesc_t sd_GattcEvtCharDiscRsp_msg;
extern const pb_msgdesc_t sd_GattcEvtDescDiscRsp_msg;
extern const pb_msgdesc_t sd_GattcEvtAttrInfoDiscRsp_msg;
extern const pb_msgdesc_t sd_GattcEvtCharValByUuidReadRsp_msg;
extern const pb_msgdesc_t sd_GattcEvtReadRsp_msg;
extern const pb_msgdesc_t sd_GattcEvtCharValsReadRsp_msg;
extern const pb_msgdesc_t sd_GattcEvtWriteRsp_msg;
extern const pb_msgdesc_t sd_GattcEvtHvx_msg;
extern const pb_msgdesc_t sd_GattcEvtExchangeMtuRsp_msg;
extern const pb_msgdesc_t sd_GattcEvtTimeout_msg;
extern const pb_msgdesc_t sd_GattcEvtWriteCmdTxComplete_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define sd_GattcPrimaryServicesDiscoverCmd_fields &sd_GattcPrimaryServicesDiscoverCmd_msg
#define sd_GattcRelationshipsDiscoverCmd_fields &sd_GattcRelationshipsDiscoverCmd_msg
#define sd_GattcCharacteristicsDiscoverCmd_fields &sd_GattcCharacteristicsDiscoverCmd_msg
#define sd_GattcDescriptorsDiscoverCmd_fields &sd_GattcDescriptorsDiscoverCmd_msg
#define sd_GattcAttrInfoDiscoverCmd_fields &sd_GattcAttrInfoDiscoverCmd_msg
#define sd_GattcCharValueByUuidReadCmd_fields &sd_GattcCharValueByUuidReadCmd_msg
#define sd_GattcReadCmd_fields &sd_GattcReadCmd_msg
#define sd_GattcCharValuesReadCmd_fields &sd_GattcCharValuesReadCmd_msg
#define sd_GattcWriteCmd_fields &sd_GattcWriteCmd_msg
#define sd_GattcHvConfirmCmd_fields &sd_GattcHvConfirmCmd_msg
#define sd_GattcExchangeMtuRequestCmd_fields &sd_GattcExchangeMtuRequestCmd_msg
#define sd_GattcPrimaryServicesDiscoverRsp_fields &sd_GattcPrimaryServicesDiscoverRsp_msg
#define sd_GattcRelationshipsDiscoverRsp_fields &sd_GattcRelationshipsDiscoverRsp_msg
#define sd_GattcCharacteristicsDiscoverRsp_fields &sd_GattcCharacteristicsDiscoverRsp_msg
#define sd_GattcDescriptorsDiscoverRsp_fields &sd_GattcDescriptorsDiscoverRsp_msg
#define sd_GattcAttrInfoDiscoverRsp_fields &sd_GattcAttrInfoDiscoverRsp_msg
#define sd_GattcCharValueByUuidReadRsp_fields &sd_GattcCharValueByUuidReadRsp_msg
#define sd_GattcReadRsp_fields &sd_GattcReadRsp_msg
#define sd_GattcCharValuesReadRsp_fields &sd_GattcCharValuesReadRsp_msg
#define sd_GattcWriteRsp_fields &sd_GattcWriteRsp_msg
#define sd_GattcHvConfirmRsp_fields &sd_GattcHvConfirmRsp_msg
#define sd_GattcExchangeMtuRequestRsp_fields &sd_GattcExchangeMtuRequestRsp_msg
#define sd_GattcEvtPrimSrvcDiscRsp_fields &sd_GattcEvtPrimSrvcDiscRsp_msg
#define sd_GattcEvtRelDiscRsp_fields &sd_GattcEvtRelDiscRsp_msg
#define sd_GattcEvtCharDiscRsp_fields &sd_GattcEvtCharDiscRsp_msg
#define sd_GattcEvtDescDiscRsp_fields &sd_GattcEvtDescDiscRsp_msg
#define sd_GattcEvtAttrInfoDiscRsp_fields &sd_GattcEvtAttrInfoDiscRsp_msg
#define sd_GattcEvtCharValByUuidReadRsp_fields &sd_GattcEvtCharValByUuidReadRsp_msg
#define sd_GattcEvtReadRsp_fields &sd_GattcEvtReadRsp_msg
#define sd_GattcEvtCharValsReadRsp_fields &sd_GattcEvtCharValsReadRsp_msg
#define sd_GattcEvtWriteRsp_fields &sd_GattcEvtWriteRsp_msg
#define sd_GattcEvtHvx_fields &sd_GattcEvtHvx_msg
#define sd_GattcEvtExchangeMtuRsp_fields &sd_GattcEvtExchangeMtuRsp_msg
#define sd_GattcEvtTimeout_fields &sd_GattcEvtTimeout_msg
#define sd_GattcEvtWriteCmdTxComplete_fields &sd_GattcEvtWriteCmdTxComplete_msg

/* Maximum encoded size of messages (where known) */
/* sd_GattcCharValuesReadCmd_size depends on runtime parameters */
/* sd_GattcEvtPrimSrvcDiscRsp_size depends on runtime parameters */
/* sd_GattcEvtRelDiscRsp_size depends on runtime parameters */
/* sd_GattcEvtCharDiscRsp_size depends on runtime parameters */
/* sd_GattcEvtDescDiscRsp_size depends on runtime parameters */
/* sd_GattcEvtAttrInfoDiscRsp_size depends on runtime parameters */
#define SD_SOFTDEVICE_GATTC_PB_H_MAX_SIZE        sd_GattcWriteCmd_size
#define sd_GattcAttrInfoDiscoverCmd_size         14
#define sd_GattcAttrInfoDiscoverRsp_size         6
#define sd_GattcCharValueByUuidReadCmd_size      23
#define sd_GattcCharValueByUuidReadRsp_size      6
#define sd_GattcCharValuesReadRsp_size           6
#define sd_GattcCharacteristicsDiscoverCmd_size  14
#define sd_GattcCharacteristicsDiscoverRsp_size  6
#define sd_GattcDescriptorsDiscoverCmd_size      14
#define sd_GattcDescriptorsDiscoverRsp_size      6
#define sd_GattcEvtCharValByUuidReadRsp_size     531
#define sd_GattcEvtCharValsReadRsp_size          527
#define sd_GattcEvtExchangeMtuRsp_size           12
#define sd_GattcEvtHvx_size                      533
#define sd_GattcEvtReadRsp_size                  535
#define sd_GattcEvtTimeout_size                  10
#define sd_GattcEvtWriteCmdTxComplete_size       11
#define sd_GattcEvtWriteRsp_size                 537
#define sd_GattcExchangeMtuRequestCmd_size       8
#define sd_GattcExchangeMtuRequestRsp_size       6
#define sd_GattcHvConfirmCmd_size                8
#define sd_GattcHvConfirmRsp_size                6
#define sd_GattcPrimaryServicesDiscoverCmd_size  17
#define sd_GattcPrimaryServicesDiscoverRsp_size  6
#define sd_GattcReadCmd_size                     12
#define sd_GattcReadRsp_size                     6
#define sd_GattcRelationshipsDiscoverCmd_size    14
#define sd_GattcRelationshipsDiscoverRsp_size    6
#define sd_GattcWriteCmd_size                    540
#define sd_GattcWriteRsp_size                    6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
