/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "protocol/softdevice_gattc.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(sd_GattcPrimaryServicesDiscoverCmd, sd_GattcPrimaryServicesDiscoverCmd, AUTO)


PB_BIND(sd_GattcRelationshipsDiscoverCmd, sd_GattcRelationshipsDiscoverCmd, AUTO)


PB_BIND(sd_GattcCharacteristicsDiscoverCmd, sd_GattcCharacteristicsDiscoverCmd, AUTO)


PB_BIND(sd_GattcDescriptorsDiscoverCmd, sd_GattcDescriptorsDiscoverCmd, AUTO)


PB_BIND(sd_GattcAttrInfoDiscoverCmd, sd_GattcAttrInfoDiscoverCmd, AUTO)


PB_BIND(sd_GattcCharValueByUuidReadCmd, sd_GattcCharValueByUuidReadCmd, AUTO)


PB_BIND(sd_GattcReadCmd, sd_GattcReadCmd, AUTO)


PB_BIND(sd_GattcCharValuesReadCmd, sd_GattcCharValuesReadCmd, AUTO)


PB_BIND(sd_GattcWriteCmd, sd_GattcWriteCmd, 2)


PB_BIND(sd_GattcHvConfirmCmd, sd_GattcHvConfirmCmd, AUTO)


PB_BIND(sd_GattcExchangeMtuRequestCmd, sd_GattcExchangeMtuRequestCmd, AUTO)


PB_BIND(sd_GattcPrimaryServicesDiscoverRsp, sd_GattcPrimaryServicesDiscoverRsp, AUTO)


PB_BIND(sd_GattcRelationshipsDiscoverRsp, sd_GattcRelationshipsDiscoverRsp, AUTO)


PB_BIND(sd_GattcCharacteristicsDiscoverRsp, sd_GattcCharacteristicsDiscoverRsp, AUTO)


PB_BIND(sd_GattcDescriptorsDiscoverRsp, sd_GattcDescriptorsDiscoverRsp, AUTO)


PB_BIND(sd_GattcAttrInfoDiscoverRsp, sd_GattcAttrInfoDiscoverRsp, AUTO)


PB_BIND(sd_GattcCharValueByUuidReadRsp, sd_GattcCharValueByUuidReadRsp, AUTO)


PB_BIND(sd_GattcReadRsp, sd_GattcReadRsp, AUTO)


PB_BIND(sd_GattcCharValuesReadRsp, sd_GattcCharValuesReadRsp, AUTO)


PB_BIND(sd_GattcWriteRsp, sd_GattcWriteRsp, AUTO)


PB_BIND(sd_GattcHvConfirmRsp, sd_GattcHvConfirmRsp, AUTO)


PB_BIND(sd_GattcExchangeMtuRequestRsp, sd_GattcExchangeMtuRequestRsp, AUTO)


PB_BIND(sd_GattcEvtPrimSrvcDiscRsp, sd_GattcEvtPrimSrvcDiscRsp, AUTO)


PB_BIND(sd_GattcEvtRelDiscRsp, sd_GattcEvtRelDiscRsp, AUTO)


PB_BIND(sd_GattcEvtCharDiscRsp, sd_GattcEvtCharDiscRsp, AUTO)


PB_BIND(sd_GattcEvtDescDiscRsp, sd_GattcEvtDescDiscRsp, AUTO)


PB_BIND(sd_GattcEvtAttrInfoDiscRsp, sd_GattcEvtAttrInfoDiscRsp, AUTO)


PB_BIND(sd_GattcEvtCharValByUuidReadRsp, sd_GattcEvtCharValByUuidReadRsp, 2)


PB_BIND(sd_GattcEvtReadRsp, sd_GattcEvtReadRsp, 2)


PB_BIND(sd_GattcEvtCharValsReadRsp, sd_GattcEvtCharValsReadRsp, 2)


PB_BIND(sd_GattcEvtWriteRsp, sd_GattcEvtWriteRsp, 2)


PB_BIND(sd_GattcEvtHvx, sd_GattcEvtHvx, 2)


PB_BIND(sd_GattcEvtExchangeMtuRsp, sd_GattcEvtExchangeMtuRsp, AUTO)


PB_BIND(sd_GattcEvtTimeout, sd_GattcEvtTimeout, AUTO)


PB_BIND(sd_GattcEvtWriteCmdTxComplete, sd_GattcEvtWriteCmdTxComplete, AUTO)



